# frozen_string_literal: true

source 'https://rubygems.org'

gem 'crawlberg', '>= 1.0.0.pre.rc.2'
gem 'rspec', '~> 3.13'
gem 'rubocop', '~> 1.86'
gem 'rubocop-rspec', '~> 3.9'
gem 'faraday', '~> 2.0'
