// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:41a8fa154ebe252fdf712594f9e54e5458aa89990107f63dbd838fa22f0f6a34
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
    globalSetup: "./globalSetup.ts",
  },
});
