// Generated by alef. Do not edit by hand.
// alef:hash:6de2d7a3fff7e34a7488334afa8e014e203513905446c2f051c0110b98c25d84

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "kreuzcrawl-android-e2e"
