# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzcrawl.ResponseMeta do
  @moduledoc "Response metadata extracted from HTTP headers."

  defstruct [
    etag: "",
    last_modified: "",
    cache_control: "",
    server: "",
    x_powered_by: "",
    content_language: "",
    content_encoding: "",
  ]
end
