# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6abc1c12e963598eec5fa892c077a2abafa7801bee199c14a21af7ff82cf7481
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: engine
defmodule E2e.EngineTest do
  use ExUnit.Case, async: false

  describe "engine_batch_basic" do
    @tag :skip
    test "CrawlEngine with defaults batch scrapes like the free function" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "engine_crawl_basic" do
    @tag :skip
    test "CrawlEngine with defaults crawls multiple pages like the free function" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "engine_map_basic" do
    @tag :skip
    test "CrawlEngine with defaults discovers URLs like the free function" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "engine_scrape_basic" do
    @tag :skip
    test "CrawlEngine with defaults scrapes a page identically to the free function" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "engine_stream_basic" do
    @tag :skip
    test "CrawlEngine with defaults streams events like the free function" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end
end
