# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:af43b1b043a1c1f06be49de52080e2e0e55508a994ced4813381b1e6a27575f9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: error
defmodule E2e.ErrorTest do
  use ExUnit.Case, async: false

  describe "error_401_unauthorized" do
    @tag :skip
    test "Handles 401 Unauthorized response correctly" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "error_403_forbidden" do
    @tag :skip
    test "Handles 403 Forbidden response correctly" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "error_404_page" do
    @tag :skip
    test "Handles 404 response correctly" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "error_408_request_timeout" do
    @tag :skip
    test "Handles 408 Request Timeout response correctly" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "error_410_gone" do
    @tag :skip
    test "Handles 410 Gone response correctly" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "error_500_server" do
    @tag :skip
    test "Handles 500 server error" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "error_502_bad_gateway" do
    @tag :skip
    test "Handles 502 Bad Gateway response correctly" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "error_connection_refused" do
    @tag :skip
    test "Handles connection refused error gracefully" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "error_dns_resolution" do
    @tag :skip
    test "Handles DNS resolution failure gracefully" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "error_empty_response" do
    @tag :skip
    test "Handles 200 with completely empty body gracefully" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "error_invalid_proxy" do
    @tag :skip
    test "Proxy pointing to unreachable address causes connection error during scrape" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "error_partial_response" do
    @tag :skip
    test "Handles incomplete or truncated HTTP response" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "error_rate_limited" do
    @tag :skip
    test "Handles 429 rate limiting with Retry-After" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "error_retry_503" do
    @tag :skip
    test "Retries request on 503 Service Unavailable response" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "error_retry_backoff" do
    @tag :skip
    test "Implements exponential backoff when retrying failed requests" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "error_ssl_invalid_cert" do
    @tag :skip
    test "Handles SSL certificate validation error" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "error_timeout" do
    @tag :skip
    test "Handles request timeout" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "error_waf_akamai" do
    @tag :skip
    test "Akamai WAF detection returns WafBlocked error" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "error_waf_false_403" do
    @tag :skip
    test "Detects WAF/bot protection false 403 (Cloudflare challenge page)" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "error_waf_imperva" do
    @tag :skip
    test "Imperva/Incapsula WAF detection" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end
end
