# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f0c32e23addfa91c5abad529092c6a11473023aa9f60c811656f3188e9704282
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: proxy
defmodule E2e.ProxyTest do
  use ExUnit.Case, async: false

  describe "proxy_authenticated" do
    test "proxy_authenticated" do
      engine_config = "{\"proxy\":{\"password\":\"proxypass\",\"url\":\"http://127.0.0.1:8889\",\"username\":\"proxyuser\"},\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/proxy_authenticated"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      assert Enum.at(result.pages, 0).status_code == 200
      assert length(result.pages) == 1
    end
  end

  describe "proxy_basic_success" do
    test "proxy_basic_success" do
      engine_config = "{\"proxy\":{\"url\":\"http://127.0.0.1:8888\"},\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/proxy_basic_success"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      assert Enum.at(result.pages, 0).status_code == 200
      assert length(result.pages) == 1
    end
  end
end
