# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9cb269b0ed2a5c3f6288d3cbbc0f267d59bcad18efb8c8a8ed5643d0f9e2dada
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: proxy
defmodule E2e.ProxyTest do
  use ExUnit.Case, async: false

  describe "proxy_authenticated" do
    test "proxy_authenticated" do
      engine_config = "{\"proxy\":{\"password\":\"proxypass\",\"url\":\"http://127.0.0.1:8889\",\"username\":\"proxyuser\"},\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/proxy_authenticated"
      {:ok, result} = Kreuzcrawl.crawl_async(engine, url)
      assert length(result.pages) == 0
    end
  end

  describe "proxy_basic_success" do
    test "proxy_basic_success" do
      engine_config = "{\"proxy\":{\"url\":\"http://127.0.0.1:8888\"},\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/proxy_basic_success"
      {:ok, result} = Kreuzcrawl.crawl_async(engine, url)
      assert length(result.pages) == 0
    end
  end
end
