# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:755569af2b42861f32165142a5cdf9e9f29615d380c94212ac00ea218a5db003
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: strategy
defmodule E2e.StrategyTest do
  use ExUnit.Case, async: false

  describe "strategy_adaptive_saturation" do
    test "strategy_adaptive_saturation" do
      engine_config = "{\"max_concurrent\":1,\"max_depth\":2,\"respect_robots_txt\":false}"
      {:ok, engine} = Crawlberg.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_STRATEGY_ADAPTIVE_SATURATION") || (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/strategy_adaptive_saturation"
      {:ok, result} = Crawlberg.crawl_async(engine, url)
      # skipped: field 'crawl.pages_crawled' not available on result type
    end
  end

  describe "strategy_adaptive_window" do
    test "strategy_adaptive_window" do
      engine_config = "{\"max_concurrent\":1,\"max_depth\":1,\"respect_robots_txt\":false}"
      {:ok, engine} = Crawlberg.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_STRATEGY_ADAPTIVE_WINDOW") || (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/strategy_adaptive_window"
      {:ok, result} = Crawlberg.crawl_async(engine, url)
      # skipped: field 'crawl.pages_crawled' not available on result type
    end
  end

  describe "strategy_best_first_seed" do
    test "strategy_best_first_seed" do
      engine_config = "{\"max_concurrent\":1,\"max_depth\":1}"
      {:ok, engine} = Crawlberg.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_STRATEGY_BEST_FIRST_SEED") || (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/strategy_best_first_seed"
      {:ok, result} = Crawlberg.crawl_async(engine, url)
      # skipped: field 'crawl.pages_crawled' not available on result type
      # skipped: field 'strategy.first_page_url_contains' not available on result type
    end
  end

  describe "strategy_bfs_default_order" do
    test "strategy_bfs_default_order" do
      engine_config = "{\"max_concurrent\":1,\"max_depth\":2}"
      {:ok, engine} = Crawlberg.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_STRATEGY_BFS_DEFAULT_ORDER") || (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/strategy_bfs_default_order"
      {:ok, result} = Crawlberg.crawl_async(engine, url)
      # skipped: field 'crawl.pages_crawled' not available on result type
      # skipped: field 'strategy.crawl_order' not available on result type
    end
  end

  describe "strategy_dfs_depth_first" do
    test "strategy_dfs_depth_first" do
      engine_config = "{\"max_concurrent\":1,\"max_depth\":2}"
      {:ok, engine} = Crawlberg.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_STRATEGY_DFS_DEPTH_FIRST") || (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/strategy_dfs_depth_first"
      {:ok, result} = Crawlberg.crawl_async(engine, url)
      # skipped: field 'crawl.pages_crawled' not available on result type
      # skipped: field 'strategy.crawl_order' not available on result type
    end
  end
end
