# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e40ebcec5a4e3d6afb0bb1acbee68879655e14d062e6b932876146b3dd1a84b8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: warc
defmodule E2e.WarcTest do
  use ExUnit.Case, async: false

  describe "warc_basic_output" do
    test "warc_basic_output" do
      engine_config = "{\"respect_robots_txt\":false,\"warc_output\":\"/tmp/kreuzcrawl_test.warc\"}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/warc_basic_output"
      {:ok, result} = Kreuzcrawl.crawl_async(engine, url)
      assert Enum.at(result.pages, 0).status_code == 200
      assert length(result.pages) == 1
    end
  end

  describe "warc_multi_page_crawl" do
    test "warc_multi_page_crawl" do
      engine_config = "{\"max_depth\":1,\"respect_robots_txt\":false,\"warc_output\":\"/tmp/kreuzcrawl_crawl.warc\"}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_WARC_MULTI_PAGE_CRAWL") || (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/warc_multi_page_crawl"
      {:ok, result} = Kreuzcrawl.crawl_async(engine, url)
      assert length(result.pages) >= 2
      assert result.stayed_on_domain == true
    end
  end
end
