// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d0875c4eff80f4b4aa7f1d2cc39dfb24e7839258c9b4893ebdd1529c47cba6cc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzcrawl;
using static Kreuzcrawl.KreuzcrawlConverter;

namespace Kreuzcrawl
{
    /// <summary>E2e tests for category: auth.</summary>
    public class AuthTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public async Task Test_AuthBasicHttp()
        {
            // Sends HTTP Basic authentication header
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"auth\":{\"password\":\"testpass\",\"type\":\"basic\",\"username\":\"testuser\"},\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlConverter.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/auth_basic_http";
            var result = await KreuzcrawlConverter.ScrapeAsync(engine, url);
    Assert.True(result.AuthHeaderSent);
    Assert.True(result.StatusCode == 200);

        }

        [Fact]
        public async Task Test_AuthBearerToken()
        {
            // Sends Bearer token in Authorization header
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"auth\":{\"token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.test\",\"type\":\"bearer\"},\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlConverter.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/auth_bearer_token";
            var result = await KreuzcrawlConverter.ScrapeAsync(engine, url);
    Assert.True(result.AuthHeaderSent);
    Assert.True(result.StatusCode == 200);

        }

        [Fact]
        public async Task Test_AuthCustomHeader()
        {
            // Sends authentication via custom header (X-API-Key)
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"auth\":{\"name\":\"X-API-Key\",\"type\":\"header\",\"value\":\"sk-test-key-12345\"},\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlConverter.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/auth_custom_header";
            var result = await KreuzcrawlConverter.ScrapeAsync(engine, url);
    Assert.True(result.AuthHeaderSent);
    Assert.True(result.StatusCode == 200);

        }


    }
}
