// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:221d39435937ffa532a77a14c9198c4efabae7e91fd8732e0057d8babc08b367
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzcrawl;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: map.</summary>
public class MapTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_MapDiscoverUrls()
    {
        // Discovers all URLs on a site without fetching full content
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_MapExcludePatterns()
    {
        // Excludes URLs matching patterns from URL map
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_MapIncludeSubdomains()
    {
        // Includes subdomain URLs in URL map discovery
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_MapLargeSitemap()
    {
        // Handles large sitemap with 100+ URLs
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_MapLimitPagination()
    {
        // Limits map result count to specified maximum
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_MapSearchFilter()
    {
        // Filters map results by search keyword
    }
}
