// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dc8f216642297bf11f87e2b1227dcd760b70d31bab536b9c6d1408cb65b6203d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzcrawl;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: middleware.</summary>
public class MiddlewareTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public async Task Test_MiddlewareEngineCrawlWithDefaults()
    {
        // Engine crawl with default middleware chain produces correct multi-page results
        var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_depth\":1}", ConfigOptions)!;
        var engine = KreuzcrawlLib.CreateEngine(engineConfig);
        var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/middleware_engine_crawl_with_defaults";
        var result = await KreuzcrawlLib.Scrape(engine, url);
        // skipped: field 'crawl.pages_crawled' not available on result type
        // skipped: field 'crawl.min_pages' not available on result type
    }

    [Fact]
    public async Task Test_MiddlewareNoopNoEffect()
    {
        // Default middleware chain does not affect normal scraping
        var engine = KreuzcrawlLib.CreateEngine(null);
        var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/middleware_noop_no_effect";
        var result = await KreuzcrawlLib.Scrape(engine, url);
        Assert.True(result.StatusCode == 200);
        Assert.Equal("Middleware Test", result.Metadata.Title.Trim());
    }
}
