// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8fc3cef2ad0ada08bee1c82c39a437179e273f52f7ca6f2e98164d17d9ec34a4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzcrawl;
using static Kreuzcrawl.KreuzcrawlLib;

namespace Kreuzcrawl
{
    /// <summary>E2e tests for category: proxy.</summary>
    public class ProxyTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public async Task Test_ProxyAuthenticated()
        {
            // Proxy with username and password credentials authenticates successfully
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"proxy\":{\"password\":\"proxypass\",\"url\":\"http://127.0.0.1:8889\",\"username\":\"proxyuser\"},\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/proxy_authenticated";
            var result = await KreuzcrawlLib.CrawlAsync(engine, url);
    Assert.True(result.Pages.Count == 0);

        }

        [Fact]
        public async Task Test_ProxyBasicSuccess()
        {
            // Configure proxy URL and successfully crawl through it
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"proxy\":{\"url\":\"http://127.0.0.1:8888\"},\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/proxy_basic_success";
            var result = await KreuzcrawlLib.CrawlAsync(engine, url);
    Assert.True(result.Pages.Count == 0);

        }


    }
}
