# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f9d5bf4355cabc99814f902ccd44634c189fe4218364aaeafadd757930cc12ca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.ArticleMetadata do
  @moduledoc "Article metadata extracted from `article:*` Open Graph tags."

  defstruct published_time: "",
            modified_time: "",
            author: "",
            section: "",
            tags: []
end
