# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ce7d0852836f953466f527d3ad7e49112985c16055bfb2a88369a14c615d7d5d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.ArticleMetadata do
  @moduledoc "Article metadata extracted from `article:*` Open Graph tags."

  @typedoc "Article metadata extracted from `article:*` Open Graph tags."
  @type t :: %__MODULE__{
          published_time: String.t() | nil,
          modified_time: String.t() | nil,
          author: String.t() | nil,
          section: String.t() | nil,
          tags: [String.t()]
        }

  defstruct published_time: nil,
            modified_time: nil,
            author: nil,
            section: nil,
            tags: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
