# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:aa8c20463c9aec8e53aeabc4d65081bfe7eba38b8b376eb3012ce4e4bc51d78a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.AuthConfig do
  @moduledoc "Authentication configuration."

  @typedoc "Authentication configuration."
  @type t :: term()

  @typedoc "HTTP Basic authentication."
  @type basic :: %{type: :basic, username: String.t(), password: String.t()}
  @typedoc "Bearer token authentication."
  @type bearer :: %{type: :bearer, token: String.t()}
  @typedoc "Custom authentication header."
  @type header :: %{type: :header, name: String.t(), value: String.t()}
end
