# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f63bf6c4de3a1a09c706829a652b6ceb8eb454186714f968a68c163220233d2d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.AuthConfig do
  @moduledoc "Authentication configuration."

  @typedoc "Authentication configuration."
  @type t :: term()

  @typedoc "HTTP Basic authentication."
  @type basic :: %{type: :basic, username: String.t(), password: String.t()}
  @typedoc "Bearer token authentication."
  @type bearer :: %{type: :bearer, token: String.t()}
  @typedoc "Custom authentication header."
  @type header :: %{type: :header, name: String.t(), value: String.t()}
end
