# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4842acb3276c59c85e53f26fd4ba0a2a8333ebb5bee619f91fdbca2998b057b6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.AuthConfig do
  @moduledoc "Authentication configuration."

  @typedoc "Authentication configuration."
  @type t :: term()

  @typedoc "HTTP Basic authentication."
  @type basic :: %{type: :basic, username: String.t(), password: String.t()}
  @typedoc "Bearer token authentication."
  @type bearer :: %{type: :bearer, token: String.t()}
  @typedoc "Custom authentication header."
  @type header :: %{type: :header, name: String.t(), value: String.t()}
end
