# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:281c21f323abbf028be073d3dc787ba76e45481ed5ecd93bf4cf0db39f92332d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.BatchCrawlStreamRequest do
  @moduledoc """
  Request to begin a multi-URL streaming crawl.

  Wraps a set of seed URLs for delivery through the streaming-adapter binding
  surface. Required as a struct because alef's streaming adapter requires a
  named request type — primitives are not supported.
  """

  @typedoc "Request to begin a multi-URL streaming crawl."
  @type t :: %__MODULE__{
          urls: [String.t()]
        }

  defstruct urls: []
end
