# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bcc3d5bd544a6e7593876ab5de51eb8c1f53d0d8d2c8c3d31c436d54ead6b3ec
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.BatchCrawlStreamRequest do
  @moduledoc """
  Request to begin a multi-URL streaming crawl.

  Wraps a set of seed URLs for delivery through the streaming-adapter binding
  surface. Required as a struct because alef's streaming adapter requires a
  named request type — primitives are not supported.
  """

  @typedoc "Request to begin a multi-URL streaming crawl."
  @type t :: %__MODULE__{
          urls: [String.t()]
        }

  defstruct urls: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
