# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d04b4b5f4ae3438e85a46264d4ef4a531f6bbf2b7755b8d00c86052dd44dc34e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.BrowserMode do
  @moduledoc "When to use the headless browser fallback."

  @typedoc "When to use the headless browser fallback."
  @type t :: :auto | :always | :never

  @auto :auto
  @always :always
  @never :never

  @doc "Automatically detect when JS rendering is needed and fall back to browser."
  @spec auto() :: t()
  def auto, do: @auto
  @doc "Always use the browser for every request."
  @spec always() :: t()
  def always, do: @always
  @doc "Never use the browser fallback."
  @spec never() :: t()
  def never, do: @never
end
