# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5e4d7896ac784966833ca07a9e0f5bf0dbaf219e0d4fb95a18b4c8688bef1708
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.BrowserMode do
  @moduledoc "When to use the headless browser fallback."

  @typedoc "When to use the headless browser fallback."
  @type t :: :auto | :always | :never

  @auto :auto
  @always :always
  @never :never

  @doc "Automatically detect when JS rendering is needed and fall back to browser."
  @spec auto() :: t()
  def auto, do: @auto
  @doc "Always use the browser for every request."
  @spec always() :: t()
  def always, do: @always
  @doc "Never use the browser fallback."
  @spec never() :: t()
  def never, do: @never
end
