# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a3be1d7dc457db5a15084b62cfc43c663d045787c11f2df4f4c57c06e12a0104
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.BrowserWait do
  @moduledoc "Wait strategy for browser page rendering."

  @typedoc "Wait strategy for browser page rendering."
  @type t :: :network_idle | :selector | :fixed

  @network_idle :network_idle
  @selector :selector
  @fixed :fixed

  @doc "Wait until network activity is idle."
  @spec network_idle() :: t()
  def network_idle, do: @network_idle
  @doc "Wait for a specific CSS selector to appear in the DOM."
  @spec selector() :: t()
  def selector, do: @selector
  @doc "Wait for a fixed duration after navigation."
  @spec fixed() :: t()
  def fixed, do: @fixed
end
