# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:aa7504a8f66d06e6d06ebc173a17ed5956f42308b0c1c28a391e350e9ff7c302
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.BrowserConfig do
  @moduledoc "Browser fallback configuration."

  @typedoc "Browser fallback configuration."
  @type t :: %__MODULE__{
          mode: String.t() | nil,
          backend: String.t() | nil,
          endpoint: String.t() | nil,
          timeout: non_neg_integer(),
          wait: String.t() | nil,
          wait_selector: String.t() | nil,
          extra_wait: non_neg_integer() | nil,
          proxy: map() | nil,
          block_url_patterns: [String.t()],
          eval_script: String.t() | nil,
          robots_user_agent: String.t() | nil,
          capture_network_events: boolean(),
          session_affinity: boolean()
        }

  defstruct mode: :auto,
            backend: :chromiumoxide,
            endpoint: nil,
            timeout: 30_000,
            wait: :network_idle,
            wait_selector: nil,
            extra_wait: nil,
            proxy: nil,
            block_url_patterns: [],
            eval_script: nil,
            robots_user_agent: nil,
            capture_network_events: false,
            session_affinity: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
