# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5e4d7896ac784966833ca07a9e0f5bf0dbaf219e0d4fb95a18b4c8688bef1708
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.BrowserWait do
  @moduledoc "Wait strategy for browser page rendering."

  @typedoc "Wait strategy for browser page rendering."
  @type t :: :network_idle | :selector | :fixed

  @network_idle :network_idle
  @selector :selector
  @fixed :fixed

  @doc "Wait until network activity is idle."
  @spec network_idle() :: t()
  def network_idle, do: @network_idle
  @doc "Wait for a specific CSS selector to appear in the DOM."
  @spec selector() :: t()
  def selector, do: @selector
  @doc "Wait for a fixed duration after navigation."
  @spec fixed() :: t()
  def fixed, do: @fixed
end
