# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:db46de252880c06ccf608be4231a9ce9a51dc26ac0012d1e1cbf99a5a00f5ea6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.BrowserBackend do
  @moduledoc "Browser backend used for JavaScript rendering."

  @typedoc "Browser backend used for JavaScript rendering."
  @type t :: :chromiumoxide | :native

  @chromiumoxide :chromiumoxide
  @native :native

  @doc "Existing Chromium/CDP backend powered by chromiumoxide."
  @spec chromiumoxide() :: t()
  def chromiumoxide, do: @chromiumoxide
  @doc "Kreuzcrawl-owned native browser backend derived from Obscura."
  @spec native() :: t()
  def native, do: @native
end
