# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c9b0d2a3dfb56b9e78a20f2176a3a0d25f8268f22862f6596fca4b7dc0041e17
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzcrawl.BrowserBackend do
  @moduledoc "Browser backend used for JavaScript rendering."

  @typedoc "Browser backend used for JavaScript rendering."
  @type t :: :chromiumoxide | :native

  @chromiumoxide :chromiumoxide
  @native :native

  @doc "Existing Chromium/CDP backend powered by chromiumoxide."
  @spec chromiumoxide() :: t()
  def chromiumoxide, do: @chromiumoxide
  @doc "Kreuzcrawl-owned native browser backend derived from Obscura."
  @spec native() :: t()
  def native, do: @native
end
