# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5e4d7896ac784966833ca07a9e0f5bf0dbaf219e0d4fb95a18b4c8688bef1708
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.BrowserBackend do
  @moduledoc "Browser backend used for JavaScript rendering."

  @typedoc "Browser backend used for JavaScript rendering."
  @type t :: :chromiumoxide | :native

  @chromiumoxide :chromiumoxide
  @native :native

  @doc "Existing Chromium/CDP backend powered by chromiumoxide."
  @spec chromiumoxide() :: t()
  def chromiumoxide, do: @chromiumoxide
  @doc "Kreuzcrawl-owned native browser backend derived from Obscura."
  @spec native() :: t()
  def native, do: @native
end
