# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1b25e195cb011d2f4c88ea3444cf50a8531d6c3b49123619f77ccac69ca37d71
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.BrowserMode do
  @moduledoc "When to use the headless browser fallback."

  @typedoc "When to use the headless browser fallback."
  @type t :: :auto | :always | :never

  @auto :auto
  @always :always
  @never :never

  @doc "Automatically detect when JS rendering is needed and fall back to browser."
  @spec auto() :: t()
  def auto, do: @auto
  @doc "Always use the browser for every request."
  @spec always() :: t()
  def always, do: @always
  @doc "Never use the browser fallback."
  @spec never() :: t()
  def never, do: @never
end
