# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:70ed23670434c5aaaea9cfa944556edc6616a5b4463684883ca6199c6264fafb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.CitationReference do
  @moduledoc """
  A single numbered reference in a citation list — produced by the citation
  extractor when content uses inline `[N]`-style markers.
  """

  @typedoc "A single numbered reference in a citation list — produced by the citation extractor when content uses inline `[N]`-style markers."
  @type t :: %__MODULE__{
          index: non_neg_integer(),
          url: String.t() | nil,
          text: String.t() | nil
        }

  defstruct index: 0,
            url: nil,
            text: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
