# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1faf62b85560753066f02cbab32b7edb21536f306b00f415f926087a9f2be6ad
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.ContentConfig do
  @moduledoc "Content extraction and conversion configuration."

  defstruct output_format: "markdown",
            preprocessing_preset: "standard",
            remove_navigation: true,
            remove_forms: true,
            strip_tags: [],
            preserve_tags: [],
            exclude_selectors: [],
            skip_images: false,
            max_depth: nil,
            wrap: false,
            wrap_width: 80,
            include_document_structure: true
end
