# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1a1b2fd3ca16640cf73559a1f0627ec25d8fa1c8784f66388c4fa5a7f6afe047
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.ContentConfig do
  @moduledoc """
  Content extraction and conversion configuration.

  Controls how HTML is converted to the output format. Uses
  html-to-markdown-rs as the conversion engine for all formats
  (markdown, plain text, djot).
  """

  @typedoc "Content extraction and conversion configuration."
  @type t :: %__MODULE__{
          output_format: String.t() | nil,
          preprocessing_preset: String.t() | nil,
          remove_navigation: boolean(),
          remove_forms: boolean(),
          strip_tags: [String.t()],
          preserve_tags: [String.t()],
          exclude_selectors: [String.t()],
          skip_images: boolean(),
          max_depth: non_neg_integer() | nil,
          wrap: boolean(),
          wrap_width: non_neg_integer(),
          include_document_structure: boolean()
        }

  defstruct output_format: "markdown",
            preprocessing_preset: "standard",
            remove_navigation: true,
            remove_forms: true,
            strip_tags: [],
            preserve_tags: [],
            exclude_selectors: [],
            skip_images: false,
            max_depth: nil,
            wrap: false,
            wrap_width: 80,
            include_document_structure: true
end
