# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4a1130eaa7f8e3312e90b66f3eb0a52e657e6378ee013ed7eeaada8817434913
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.CookieInfo do
  @moduledoc "Information about an HTTP cookie received from a response."

  @typedoc "Information about an HTTP cookie received from a response."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          value: String.t() | nil,
          domain: String.t() | nil,
          path: String.t() | nil
        }

  defstruct name: nil,
            value: nil,
            domain: nil,
            path: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
