# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:24e0eba585e4c02949dc9afef384ce27f55a4b456d45f42ccc0863dec10f6862
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.CookieInfo do
  @moduledoc "Information about an HTTP cookie received from a response."

  @typedoc "Information about an HTTP cookie received from a response."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          value: String.t() | nil,
          domain: String.t() | nil,
          path: String.t() | nil
        }

  defstruct name: nil,
            value: nil,
            domain: nil,
            path: nil
end
