# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d35900494970a01192f1b482e29fd7782e94e6ddb4a2c18bad51f45b8ce2faad
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.CrawlStreamRequest do
  @moduledoc """
  Request to begin a single-URL streaming crawl.

  Wraps a single seed URL for delivery through the streaming-adapter binding
  surface. Required as a struct because alef's streaming adapter requires a
  named request type — primitives are not supported.
  """

  @typedoc "Request to begin a single-URL streaming crawl."
  @type t :: %__MODULE__{
          url: String.t() | nil
        }

  defstruct url: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Jason.Encoder.encode(opts)
    end
  end
end
