# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c71c6cebc3048c2cd2c1e6daba158174f156e790d59b506d304c335b9728d6df
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzcrawl.CrawlStreamRequest do
  @moduledoc """
  Request to begin a single-URL streaming crawl.

  Wraps a single seed URL for delivery through the streaming-adapter binding
  surface. Required as a struct because alef's streaming adapter requires a
  named request type — primitives are not supported.
  """

  @typedoc "Request to begin a single-URL streaming crawl."
  @type t :: %__MODULE__{
          url: String.t() | nil
        }

  defstruct url: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
