# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f2acf0fe68bedde7da1909fa6feedaffb995d5aec49220ec23bf64125a392d19
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.DownloadedDocument do
  @moduledoc """
  A downloaded non-HTML document (PDF, DOCX, image, code file, etc.).

  When the crawler encounters non-HTML content and `download_documents` is
  enabled, it downloads the raw bytes and populates this struct instead of
  skipping the resource.
  """

  @typedoc "A downloaded non-HTML document (PDF, DOCX, image, code file, etc.)."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          mime_type: String.t() | nil,
          size: non_neg_integer(),
          filename: String.t() | nil,
          content_hash: String.t() | nil,
          headers: map()
        }

  defstruct url: nil,
            mime_type: nil,
            size: 0,
            filename: nil,
            content_hash: nil,
            headers: %{}

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
