# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzcrawl.DownloadedAsset do
  @moduledoc "A downloaded asset from a page."

  defstruct url: "",
            content_hash: "",
            mime_type: "",
            size: 0,
            asset_category: :image,
            html_tag: ""
end
