# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:301fc8d9306b02f0364dd1a0a04cc2bbfa3a4036734176b1881bde69f676a6bd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.ExtractionMeta do
  @moduledoc "Metadata about an LLM extraction pass."

  @typedoc "Metadata about an LLM extraction pass."
  @type t :: %__MODULE__{
          cost: float() | nil,
          prompt_tokens: non_neg_integer() | nil,
          completion_tokens: non_neg_integer() | nil,
          model: String.t() | nil,
          chunks_processed: non_neg_integer()
        }

  defstruct cost: nil,
            prompt_tokens: nil,
            completion_tokens: nil,
            model: nil,
            chunks_processed: 0
end
