# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:af79d98584e691ba001edd7c81f77b8b78b0f3a75092e96486a62bc57ae351de
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.ExtractionMeta do
  @moduledoc "Metadata about an LLM extraction pass."

  @typedoc "Metadata about an LLM extraction pass."
  @type t :: %__MODULE__{
          cost: float() | nil,
          prompt_tokens: non_neg_integer() | nil,
          completion_tokens: non_neg_integer() | nil,
          model: String.t() | nil,
          chunks_processed: non_neg_integer()
        }

  defstruct cost: nil,
            prompt_tokens: nil,
            completion_tokens: nil,
            model: nil,
            chunks_processed: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Jason.Encoder.encode(opts)
    end
  end
end
