# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4842acb3276c59c85e53f26fd4ba0a2a8333ebb5bee619f91fdbca2998b057b6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.ExtractionMeta do
  @moduledoc "Metadata about an LLM extraction pass."

  @typedoc "Metadata about an LLM extraction pass."
  @type t :: %__MODULE__{
    cost: float() | nil,    prompt_tokens: non_neg_integer() | nil,    completion_tokens: non_neg_integer() | nil,    model: String.t() | nil,    chunks_processed: non_neg_integer()        }

  defstruct cost: nil,
            prompt_tokens: nil,
            completion_tokens: nil,
            model: nil,
            chunks_processed: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
