# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:196d90a73fdb96222246064c5dce70f1723a6aca423cdf51502e56a3afefde29
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.FeedInfo do
  @moduledoc "Information about a feed link found on a page."

  @typedoc "Information about a feed link found on a page."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          title: String.t() | nil,
          feed_type: String.t() | nil
        }

  defstruct url: nil,
            title: nil,
            feed_type: :rss

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
