# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:676d34200787436019f4a076231c9cf054b507dbd4c39d77b8ca67d9d0f5e3ec
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.FeedType do
  @moduledoc "The type of a feed (RSS, Atom, or JSON Feed)."

  @typedoc "The type of a feed (RSS, Atom, or JSON Feed)."
  @type t :: :rss | :atom | :json_feed

  @rss :rss
  @atom :atom
  @json_feed :json_feed

  @doc "RSS feed."
  @spec rss() :: t()
  def rss, do: @rss
  @doc "Atom feed."
  @spec atom() :: t()
  def atom, do: @atom
  @doc "JSON Feed."
  @spec json_feed() :: t()
  def json_feed, do: @json_feed
end
