# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4a1130eaa7f8e3312e90b66f3eb0a52e657e6378ee013ed7eeaada8817434913
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.FeedType do
  @moduledoc "The type of a feed (RSS, Atom, or JSON Feed)."

  @typedoc "The type of a feed (RSS, Atom, or JSON Feed)."
  @type t :: :rss | :atom | :json_feed

  @rss :rss
  @atom :atom
  @json_feed :json_feed

  @doc "RSS feed."
  @spec rss() :: t()
  def rss, do: @rss
  @doc "Atom feed."
  @spec atom() :: t()
  def atom, do: @atom
  @doc "JSON Feed."
  @spec json_feed() :: t()
  def json_feed, do: @json_feed
end
