# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ee77b1b86c68905dfe399ebd9cb2b7a665f52308be7178eaf5099e6585d71c97
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.HeadingInfo do
  @moduledoc "A heading element extracted from the page."

  @typedoc "A heading element extracted from the page."
  @type t :: %__MODULE__{
          level: non_neg_integer(),
          text: String.t() | nil
        }

  defstruct level: 0,
            text: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
