# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e0b048907e4acd1bff8132ca9fab8a2ec941d36e30e70ac1f6ce3cd337219c92
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.HeadingInfo do
  @moduledoc "A heading element extracted from the page."

  @typedoc "A heading element extracted from the page."
  @type t :: %__MODULE__{
          level: non_neg_integer(),
          text: String.t() | nil
        }

  defstruct level: 0,
            text: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
