# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:844df915154f680a35d6cba0bf29ade937e5ffa63c54639d604b2c0c18bd6a79
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.HreflangEntry do
  @moduledoc "An hreflang alternate link entry."

  @typedoc "An hreflang alternate link entry."
  @type t :: %__MODULE__{
          lang: String.t() | nil,
          url: String.t() | nil
        }

  defstruct lang: nil,
            url: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
