# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:451147a80426c3b2fb90e8ee69a52a7512127c75b4a71f6091ef9e4be4c9f3f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.HreflangEntry do
  @moduledoc "An hreflang alternate link entry."

  @typedoc "An hreflang alternate link entry."
  @type t :: %__MODULE__{
          lang: String.t() | nil,
          url: String.t() | nil
        }

  defstruct lang: nil,
            url: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
