# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzcrawl.ImageInfo do
  @moduledoc "Information about an image found on a page."

  defstruct url: "",
            alt: "",
            width: 0,
            height: 0,
            source: :img
end
