# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d0875c4eff80f4b4aa7f1d2cc39dfb24e7839258c9b4893ebdd1529c47cba6cc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.ImageSource do
  @moduledoc "The source of an image reference."

  @typedoc "The source of an image reference."
  @type t :: :img | :picture_source | :"og:image" | :"twitter:image"

  @img :img
  @picture_source :picture_source
  @og_image :"og:image"
  @twitter_image :"twitter:image"

  @doc "An `<img>` tag."
  @spec img() :: t()
  def img, do: @img
  @doc "A `<source>` tag inside `<picture>`."
  @spec picture_source() :: t()
  def picture_source, do: @picture_source
  @doc "An `og:image` meta tag."
  @spec og_image() :: t()
  def og_image, do: @og_image
  @doc "A `twitter:image` meta tag."
  @spec twitter_image() :: t()
  def twitter_image, do: @twitter_image
end
