# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:42cba53345bfa03607a118143529cae069edebcd6e06046a0d61ed5a35b20ea3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.JsonLdEntry do
  @moduledoc "A JSON-LD structured data entry found on a page."

  @typedoc "A JSON-LD structured data entry found on a page."
  @type t :: %__MODULE__{
          schema_type: String.t() | nil,
          name: String.t() | nil,
          raw: String.t() | nil
        }

  defstruct schema_type: nil,
            name: nil,
            raw: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
