# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fced693bde80386ea9407ef3ff4876dcfb37ececce19becec06a496f86099891
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzcrawl.JsonLdEntry do
  @moduledoc "A JSON-LD structured data entry found on a page."

  @typedoc "A JSON-LD structured data entry found on a page."
  @type t :: %__MODULE__{
          schema_type: String.t() | nil,
          name: String.t() | nil,
          raw: String.t() | nil
        }

  defstruct schema_type: nil,
            name: nil,
            raw: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
