# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3c1c2cb7c2f610995b6d15dbf1e1a6e561317ad4f7e441e40ef3a486db0f9e1e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.LinkInfo do
  @moduledoc "Information about a link found on a page."

  @typedoc "Information about a link found on a page."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          text: String.t() | nil,
          link_type: String.t() | nil,
          rel: String.t() | nil,
          nofollow: boolean()
        }

  defstruct url: nil,
            text: nil,
            link_type: :internal,
            rel: nil,
            nofollow: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
