# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c71c6cebc3048c2cd2c1e6daba158174f156e790d59b506d304c335b9728d6df
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzcrawl.LinkType do
  @moduledoc "The classification of a link."

  @typedoc "The classification of a link."
  @type t :: :internal | :external | :anchor | :document

  @internal :internal
  @external :external
  @anchor :anchor
  @document :document

  @doc "A link to the same domain."
  @spec internal() :: t()
  def internal, do: @internal
  @doc "A link to a different domain."
  @spec external() :: t()
  def external, do: @external
  @doc "A fragment-only link (e.g., `#section`)."
  @spec anchor() :: t()
  def anchor, do: @anchor
  @doc "A link to a downloadable document (PDF, DOC, etc.)."
  @spec document() :: t()
  def document, do: @document
end
