# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3f360095a79bccf54e028029edea125916949267698be40862f7712e24c5d718
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.LinkInfo do
  @moduledoc "Information about a link found on a page."

  defstruct url: nil,
            text: nil,
            link_type: :internal,
            rel: nil,
            nofollow: false
end
