# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4b023e3e05968bd55d87098ef83aae65339070f57b227647cda2f67c49edaa0a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.LinkType do
  @moduledoc "The classification of a link."

  @typedoc "The classification of a link."
  @type t :: :internal | :external | :anchor | :document

  @internal :internal
  @external :external
  @anchor :anchor
  @document :document

  @doc "A link to the same domain."
  @spec internal() :: t()
  def internal, do: @internal
  @doc "A link to a different domain."
  @spec external() :: t()
  def external, do: @external
  @doc "A fragment-only link (e.g., `#section`)."
  @spec anchor() :: t()
  def anchor, do: @anchor
  @doc "A link to a downloadable document (PDF, DOC, etc.)."
  @spec document() :: t()
  def document, do: @document
end
