# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9cb269b0ed2a5c3f6288d3cbbc0f267d59bcad18efb8c8a8ed5643d0f9e2dada
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.PageAction do
  @moduledoc """
  A single page interaction action.

  Actions are serialized with a `type` tag using camelCase naming,
  except `ExecuteJs` which is explicitly renamed to `"executeJs"`.
  """

  @typedoc "A single page interaction action."
  @type t :: term()

  @typedoc "Click on an element matching the given CSS selector."
  @type click :: %{type: :click, selector: String.t()}
  @typedoc "Type text into an element matching the given CSS selector."
  @type type_text :: %{type: :type_text, selector: String.t(), text: String.t()}
  @typedoc "Press a keyboard key (e.g. \"Enter\", \"Tab\", \"Escape\")."
  @type press :: %{type: :press, key: String.t()}
  @typedoc "Scroll the page or a specific element."
  @type scroll :: %{type: :scroll, direction: map(), selector: String.t(), amount: integer()}
  @typedoc "Wait for a duration or for an element to appear."
  @type wait :: %{type: :wait, milliseconds: integer(), selector: String.t()}
  @typedoc "Take a screenshot of the current page."
  @type screenshot :: %{type: :screenshot, full_page: boolean()}
  @typedoc "Execute arbitrary JavaScript in the page context."
  @type execute_js :: %{type: :execute_js, script: String.t()}
  @typedoc "Scrape the current page HTML."
  @type scrape :: :scrape
end
