# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5e4d7896ac784966833ca07a9e0f5bf0dbaf219e0d4fb95a18b4c8688bef1708
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.ProxyConfig do
  @moduledoc "Proxy configuration for HTTP requests."

  @typedoc "Proxy configuration for HTTP requests."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          username: String.t() | nil,
          password: String.t() | nil
        }

  defstruct url: nil,
            username: nil,
            password: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
