# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4842acb3276c59c85e53f26fd4ba0a2a8333ebb5bee619f91fdbca2998b057b6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.ResponseMeta do
  @moduledoc "Response metadata extracted from HTTP headers."

  @typedoc "Response metadata extracted from HTTP headers."
  @type t :: %__MODULE__{
    etag: String.t() | nil,    last_modified: String.t() | nil,    cache_control: String.t() | nil,    server: String.t() | nil,    x_powered_by: String.t() | nil,    content_language: String.t() | nil,    content_encoding: String.t() | nil        }

  defstruct etag: nil,
            last_modified: nil,
            cache_control: nil,
            server: nil,
            x_powered_by: nil,
            content_language: nil,
            content_encoding: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
