# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:451147a80426c3b2fb90e8ee69a52a7512127c75b4a71f6091ef9e4be4c9f3f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.ResponseMeta do
  @moduledoc "Response metadata extracted from HTTP headers."

  @typedoc "Response metadata extracted from HTTP headers."
  @type t :: %__MODULE__{
          etag: String.t() | nil,
          last_modified: String.t() | nil,
          cache_control: String.t() | nil,
          server: String.t() | nil,
          x_powered_by: String.t() | nil,
          content_language: String.t() | nil,
          content_encoding: String.t() | nil
        }

  defstruct etag: nil,
            last_modified: nil,
            cache_control: nil,
            server: nil,
            x_powered_by: nil,
            content_language: nil,
            content_encoding: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
