# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.ResponseMeta do
  @moduledoc "Response metadata extracted from HTTP headers."

  defstruct etag: "",
            last_modified: "",
            cache_control: "",
            server: "",
            x_powered_by: "",
            content_language: "",
            content_encoding: ""
end
