# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f63bf6c4de3a1a09c706829a652b6ceb8eb454186714f968a68c163220233d2d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.ScrollDirection do
  @moduledoc "Direction for a scroll action."

  @typedoc "Direction for a scroll action."
  @type t :: :up | :down

  @up :up
  @down :down

  @doc "Scroll upward."
  @spec up() :: t()
  def up, do: @up
  @doc "Scroll downward."
  @spec down() :: t()
  def down, do: @down
end
