# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8fc3cef2ad0ada08bee1c82c39a437179e273f52f7ca6f2e98164d17d9ec34a4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.ScrollDirection do
  @moduledoc "Direction for a scroll action."

  @typedoc "Direction for a scroll action."
  @type t :: :up | :down

  @up :up
  @down :down

  @doc "Scroll upward."
  @spec up() :: t()
  def up, do: @up
  @doc "Scroll downward."
  @spec down() :: t()
  def down, do: @down
end
