# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9895b60f6d5fb095c6d1779bde7879c8e27380ad73a146ca4a5888f7696c339d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.SitemapUrl do
  @moduledoc "A URL entry from a sitemap."

  @typedoc "A URL entry from a sitemap."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          lastmod: String.t() | nil,
          changefreq: String.t() | nil,
          priority: String.t() | nil
        }

  defstruct url: nil,
            lastmod: nil,
            changefreq: nil,
            priority: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
