# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f63bf6c4de3a1a09c706829a652b6ceb8eb454186714f968a68c163220233d2d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.SsrfPolicy do
  @moduledoc "SSRF policy configuration."

  @typedoc "SSRF policy configuration."
  @type t :: %__MODULE__{
          deny_private: boolean(),
          max_redirects: non_neg_integer()
        }

  defstruct deny_private: true,
            max_redirects: 5

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
