// DO NOT EDIT - auto-generated by alef
// alef:hash:952c737eea2172575fdb72ef8eef11fca0a2c69ce6ec700e348f70e5c4a6fd2d
package io.xberg.crawlberg;

/**
 * A connection error occurred.
 */
public class ConnectionException extends CrawlErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new ConnectionException with the given message. */
    public ConnectionException(final String message) {
        super(message);
    }

    /** Creates a new ConnectionException with the given message and cause. */
    public ConnectionException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
