// DO NOT EDIT - auto-generated by alef
// alef:hash:11ba98ea104a2a0b34dc436503c6e2cd4ca6f9e1337846ab2f7e4b9fccb505c9
package io.xberg.crawlberg;

/**
 * Data was lost or truncated during transfer.
 */
public class DataLossException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DataLossException with the given message. */
  public DataLossException(final String message) {
    super(message);
  }

  /** Creates a new DataLossException with the given message and cause. */
  public DataLossException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
