// DO NOT EDIT - auto-generated by alef
// alef:hash:755569af2b42861f32165142a5cdf9e9f29615d380c94212ac00ea218a5db003
package io.xberg.crawlberg;

/**
 * Data was lost or truncated during transfer.
 */
public class DataLossException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DataLossException with the given message. */
  public DataLossException(final String message) {
    super(message);
  }

  /** Creates a new DataLossException with the given message and cause. */
  public DataLossException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
