// DO NOT EDIT - auto-generated by alef
// alef:hash:11ba98ea104a2a0b34dc436503c6e2cd4ca6f9e1337846ab2f7e4b9fccb505c9
package io.xberg.crawlberg;

/**
 * URL denied by SSRF policy: private IP, metadata IP, etc.
 */
public class DeniedByPolicyException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DeniedByPolicyException with the given message. */
  public DeniedByPolicyException(final String message) {
    super(message);
  }

  /** Creates a new DeniedByPolicyException with the given message and cause. */
  public DeniedByPolicyException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
