// DO NOT EDIT - auto-generated by alef
// alef:hash:277d85397998235b21fcea3a167fbdf11c7196bb8ab9a24070c0403ce7910336
package io.xberg.crawlberg;

/**
 * URL scheme not in allowlist (e.g., `ftp://` when only `http`/`https` allowed).
 */
public class DisallowedSchemeException extends SsrfErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new DisallowedSchemeException with the given message. */
    public DisallowedSchemeException(final String message) {
        super(message);
    }

    /** Creates a new DisallowedSchemeException with the given message and cause. */
    public DisallowedSchemeException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
