// DO NOT EDIT - auto-generated by alef
// alef:hash:b60db53f8e86834a869c3860eb7122e465ce62affbd0852b1dd5f5fa00c4b5f2
package io.xberg.crawlberg;

/**
 * URL scheme not in allowlist (e.g., `ftp://` when only `http`/`https` allowed).
 */
public class DisallowedSchemeException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DisallowedSchemeException with the given message. */
  public DisallowedSchemeException(final String message) {
    super(message);
  }

  /** Creates a new DisallowedSchemeException with the given message and cause. */
  public DisallowedSchemeException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
