// DO NOT EDIT - auto-generated by alef
// alef:hash:23d662f17ccee663375ea978facec5b4b691adf30860c73224d58efb602c12d2
package io.xberg.crawlberg;

/**
 * The resource is permanently gone (HTTP 410).
 */
public class GoneException extends CrawlErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new GoneException with the given message. */
    public GoneException(final String message) {
        super(message);
    }

    /** Creates a new GoneException with the given message and cause. */
    public GoneException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
