// DO NOT EDIT - auto-generated by alef
// alef:hash:23d662f17ccee663375ea978facec5b4b691adf30860c73224d58efb602c12d2
package io.xberg.crawlberg;

/**
 * Invalid URL format.
 */
public class InvalidUrlException extends SsrfErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new InvalidUrlException with the given message. */
    public InvalidUrlException(final String message) {
        super(message);
    }

    /** Creates a new InvalidUrlException with the given message and cause. */
    public InvalidUrlException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
