// DO NOT EDIT - auto-generated by alef
// alef:hash:06831f8166c6d860691af36ee02b72ae3246568eb2e5c67ed5d11da71d02afeb
package io.xberg.crawlberg;

/**
 * Host not on allowlist when an allowlist is configured.
 */
public class NotOnAllowlistException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new NotOnAllowlistException with the given message. */
  public NotOnAllowlistException(final String message) {
    super(message);
  }

  /** Creates a new NotOnAllowlistException with the given message and cause. */
  public NotOnAllowlistException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
