// DO NOT EDIT - auto-generated by alef
// alef:hash:a981b4c635037625f0e2a1806b53bedd24cd0627892d6d41614fcfec2528d021
package io.xberg.crawlberg;

/**
 * An SSL/TLS error occurred.
 */
public class SslException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SslException with the given message. */
  public SslException(final String message) {
    super(message);
  }

  /** Creates a new SslException with the given message and cause. */
  public SslException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
