// DO NOT EDIT - auto-generated by alef
// alef:hash:755569af2b42861f32165142a5cdf9e9f29615d380c94212ac00ea218a5db003
package io.xberg.crawlberg;

/**
 * A URL was rejected by SSRF policy (private IP, metadata, disallowed scheme, etc).
 */
public class SsrfPolicyViolationException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SsrfPolicyViolationException with the given message. */
  public SsrfPolicyViolationException(final String message) {
    super(message);
  }

  /** Creates a new SsrfPolicyViolationException with the given message and cause. */
  public SsrfPolicyViolationException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
