// DO NOT EDIT - auto-generated by alef
// alef:hash:06831f8166c6d860691af36ee02b72ae3246568eb2e5c67ed5d11da71d02afeb
package io.xberg.crawlberg;

/**
 * SSRF validation error.
 */
public class SsrfErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new SsrfErrorException with the given message. */
  public SsrfErrorException(final String message) {
    super(message);
  }

  /** Creates a new SsrfErrorException with the given message and cause. */
  public SsrfErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
