// DO NOT EDIT - auto-generated by alef
// alef:hash:277d85397998235b21fcea3a167fbdf11c7196bb8ab9a24070c0403ce7910336
package io.xberg.crawlberg;

/**
 * The request was unauthorized (HTTP 401).
 */
public class UnauthorizedException extends CrawlErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new UnauthorizedException with the given message. */
    public UnauthorizedException(final String message) {
        super(message);
    }

    /** Creates a new UnauthorizedException with the given message and cause. */
    public UnauthorizedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
