// DO NOT EDIT - auto-generated by alef
// alef:hash:952c737eea2172575fdb72ef8eef11fca0a2c69ce6ec700e348f70e5c4a6fd2d
package io.xberg.crawlberg;

/**
 * The requested capability is not supported by the active backend or build.
 */
public class UnsupportedException extends CrawlErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new UnsupportedException with the given message. */
    public UnsupportedException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedException with the given message and cause. */
    public UnsupportedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
