# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b59e800fdddf59213911a2309f9e365fa6993399f1c12fbe68bd27b269cff2d9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Kreuzcrawl
  VERSION = "0.3.0-rc.1"
end
