# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4d44f6ca0373cb2dea5fd2ed538c296c8a54cedd71f30637fdb1485de2a8d9cb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Kreuzcrawl
  VERSION = '0.3.0.pre.rc.10'
end
