// Generated by alef. Do not edit by hand.
// alef:hash:4a1130eaa7f8e3312e90b66f3eb0a52e657e6378ee013ed7eeaada8817434913
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
)

package dev.kreuzberg.kreuzcrawl.android

/**
 * Request to begin a multi-URL streaming crawl.
 *
 * Wraps a set of seed URLs for delivery through the streaming-adapter binding surface. Required as
 * a struct because alef's streaming adapter requires a named request type — primitives are not
 * supported.
 */
data class BatchCrawlStreamRequest(
    /**
     * The seed URLs to crawl. Each URL is followed independently up to the engine's configured
     * depth.
     */
    val urls: List<String> = emptyList()
)
