// Generated by alef. Do not edit by hand.
// alef:hash:0539e1fc0b063acf517daa21234cfb94c938e727d015c3b6d1cf094b4bb05451
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package dev.kreuzberg.kreuzcrawl.android

/**
 * Request to begin a multi-URL streaming crawl.
 *
 * Wraps a set of seed URLs for delivery through the streaming-adapter binding surface. Required as
 * a struct because alef's streaming adapter requires a named request type — primitives are not
 * supported.
 */
data class BatchCrawlStreamRequest(
    /**
     * The seed URLs to crawl. Each URL is followed independently up to the engine's configured
     * depth.
     */
    val urls: List<String> = emptyList()
)
