// Generated by alef. Do not edit by hand.
// alef:hash:c71da313df7b9a37bdd4f997f05150b92dfa5e723d3e2a4db0adafea6f951837
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package dev.kreuzberg.kreuzcrawl.android

/** Result from a single URL in a batch crawl operation. */
data class BatchCrawlResult(
    /** The seed URL that was crawled. */
    val url: String = "",
    /** The crawl result, if successful. */
    val result: CrawlResult? = null,
    /** The error message, if the crawl failed. */
    val error: String? = null,
)
