// Generated by alef. Do not edit by hand.
// alef:hash:5fe7349bb6652c47fba5231171bbafdd1bf743e1c6c68fe6b52bcecda7a5f8c1
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
)

package dev.kreuzberg.kreuzcrawl.android

import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.databind.PropertyNamingStrategies
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.withContext

/**
 * Opaque handle to a configured crawl engine.
 *
 * Constructed via `create_engine` with an optional `CrawlConfig`. Default implementations for all
 * pluggable components are used internally.
 */
class CrawlEngineHandle internal constructor(internal val handle: Long) : AutoCloseable {
    override fun close() {
        KreuzcrawlConverterBridge.nativeFreeCrawlEngineHandle(handle)
    }

    private val mapper =
        ObjectMapper()
            .registerModule(Jdk8Module())
            .findAndRegisterModules()
            .setPropertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE)

    @Suppress("TooGenericExceptionCaught")
    fun crawlStream(req: CrawlStreamRequest): Flow<CrawlEvent> = callbackFlow {
        val streamHandle: Long =
            withContext(Dispatchers.IO) {
                KreuzcrawlConverterBridge.nativeCrawlEngineHandleCrawlStreamStart(
                    handle,
                    mapper.writeValueAsString(req),
                )
            }
        try {
            while (true) {
                val chunkJson: String? =
                    withContext(Dispatchers.IO) {
                        KreuzcrawlConverterBridge.nativeCrawlEngineHandleCrawlStreamNext(
                            streamHandle
                        )
                    }
                if (chunkJson == null) break
                val chunk = mapper.readValue(chunkJson, CrawlEvent::class.java)
                send(chunk)
            }
            close()
        } catch (e: Throwable) {
            close(e)
        }
        awaitClose {
            KreuzcrawlConverterBridge.nativeCrawlEngineHandleCrawlStreamFree(streamHandle)
        }
    }

    @Suppress("TooGenericExceptionCaught")
    fun batchCrawlStream(req: BatchCrawlStreamRequest): Flow<CrawlEvent> = callbackFlow {
        val streamHandle: Long =
            withContext(Dispatchers.IO) {
                KreuzcrawlConverterBridge.nativeCrawlEngineHandleBatchCrawlStreamStart(
                    handle,
                    mapper.writeValueAsString(req),
                )
            }
        try {
            while (true) {
                val chunkJson: String? =
                    withContext(Dispatchers.IO) {
                        KreuzcrawlConverterBridge.nativeCrawlEngineHandleBatchCrawlStreamNext(
                            streamHandle
                        )
                    }
                if (chunkJson == null) break
                val chunk = mapper.readValue(chunkJson, CrawlEvent::class.java)
                send(chunk)
            }
            close()
        } catch (e: Throwable) {
            close(e)
        }
        awaitClose {
            KreuzcrawlConverterBridge.nativeCrawlEngineHandleBatchCrawlStreamFree(streamHandle)
        }
    }
}
