// Generated by alef. Do not edit by hand.
// alef:hash:0918d261d00df25528ad43e170ebb4136bcf9ba7e27dbb81f6ad604080475b6b
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package dev.kreuzberg.kreuzcrawl.android

/**
 * Request to begin a single-URL streaming crawl.
 *
 * Wraps a single seed URL for delivery through the streaming-adapter binding surface. Required as a
 * struct because alef's streaming adapter requires a named request type — primitives are not
 * supported.
 */
data class CrawlStreamRequest(
    /** The seed URL to crawl. */
    val url: String = ""
)
