// Generated by alef. Do not edit by hand.
// alef:hash:c7ccb8950f448d5ad65e78649c618fb261c896faa19f3af6273aa19a09c8d4b9
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package dev.kreuzberg.kreuzcrawl.android

/** Information about a favicon or icon link. */
data class FaviconInfo(
    /** The icon URL. */
    val url: String = "",
    /** The `rel` attribute (e.g., "icon", "apple-touch-icon"). */
    val rel: String = "",
    /** The `sizes` attribute, if present. */
    val sizes: String? = null,
    /** The MIME type, if present. */
    val mimeType: String? = null,
)
