// Generated by alef. Do not edit by hand.
// alef:hash:882a6f513499cb08d9cbeb641424fe238f26f3653e161241824c4ea057a44c4f

package dev.kreuzberg.kreuzcrawl.android

class KreuzcrawlBridgeException(message: String?, cause: Throwable?) :
    RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
