// Generated by alef. Do not edit by hand.
// alef:hash:bcc3d5bd544a6e7593876ab5de51eb8c1f53d0d8d2c8c3d31c436d54ead6b3ec
@file:Suppress(
    "ktlint:standard:max-line-length",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:annotation",
    "MaxLineLength",
    "TooManyFunctions",
    "LongParameterList",
)

package dev.kreuzberg.kreuzcrawl.android

@Suppress("TooManyFunctions")
object KreuzcrawlBridge {
    init {
        System.loadLibrary("kcrawl_jni")
    }

    @Throws(KreuzcrawlBridgeException::class)
    external fun nativeGenerateCitations(markdown: String): String

    @Throws(KreuzcrawlBridgeException::class) external fun nativeCreateEngine(config: String): Long

    @Throws(KreuzcrawlBridgeException::class)
    external fun nativeScrape(engine: Long, url: String): String

    @Throws(KreuzcrawlBridgeException::class)
    external fun nativeCrawl(engine: Long, url: String): String

    @Throws(KreuzcrawlBridgeException::class)
    external fun nativeMapUrls(engine: Long, url: String): String

    @Throws(KreuzcrawlBridgeException::class)
    external fun nativeInteract(engine: Long, url: String, actions: String): String

    @Throws(KreuzcrawlBridgeException::class)
    external fun nativeBatchScrape(engine: Long, urls: String): String

    @Throws(KreuzcrawlBridgeException::class)
    external fun nativeBatchCrawl(engine: Long, urls: String): String

    // JNI external funs for client instance methods.
    @Throws(KreuzcrawlBridgeException::class)
    external fun nativeCrawlEngineHandleCrawlStream(handle: Long, requestJson: String): String

    @Throws(KreuzcrawlBridgeException::class)
    external fun nativeCrawlEngineHandleBatchCrawlStream(handle: Long, requestJson: String): String

    external fun nativeFreeCrawlEngineHandle(handle: Long)

    // JNI streaming external funs — implementations are Rust JNI shims.

    // Streaming JNI externs for CrawlEngineHandle.crawlStream
    @Throws(KreuzcrawlBridgeException::class)
    external fun nativeCrawlEngineHandleCrawlStreamStart(
        clientHandle: Long,
        requestJson: String,
    ): Long

    @Throws(KreuzcrawlBridgeException::class)
    external fun nativeCrawlEngineHandleCrawlStreamNext(streamHandle: Long): String?

    external fun nativeCrawlEngineHandleCrawlStreamFree(streamHandle: Long)

    // Streaming JNI externs for CrawlEngineHandle.batchCrawlStream
    @Throws(KreuzcrawlBridgeException::class)
    external fun nativeCrawlEngineHandleBatchCrawlStreamStart(
        clientHandle: Long,
        requestJson: String,
    ): Long

    @Throws(KreuzcrawlBridgeException::class)
    external fun nativeCrawlEngineHandleBatchCrawlStreamNext(streamHandle: Long): String?

    external fun nativeCrawlEngineHandleBatchCrawlStreamFree(streamHandle: Long)

    // Destructor external funs for handle-only opaque types.
}
