// Generated by alef. Do not edit by hand.
// alef:hash:4a1130eaa7f8e3312e90b66f3eb0a52e657e6378ee013ed7eeaada8817434913
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
)

package dev.kreuzberg.kreuzcrawl.android

/** The classification of a link. */
enum class LinkType {
    /** A link to the same domain. */
    @com.fasterxml.jackson.annotation.JsonProperty("internal") INTERNAL,
    /** A link to a different domain. */
    @com.fasterxml.jackson.annotation.JsonProperty("external") EXTERNAL,
    /** A fragment-only link (e.g., `#section`). */
    @com.fasterxml.jackson.annotation.JsonProperty("anchor") ANCHOR,
    /** A link to a downloadable document (PDF, DOC, etc.). */
    @com.fasterxml.jackson.annotation.JsonProperty("document") DOCUMENT;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            INTERNAL -> "internal"
            EXTERNAL -> "external"
            ANCHOR -> "anchor"
            DOCUMENT -> "document"
        }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): LinkType =
            when (value) {
                "internal" -> INTERNAL
                "external" -> EXTERNAL
                "anchor" -> ANCHOR
                "document" -> DOCUMENT
                else -> throw IllegalArgumentException("Unknown LinkType value: $value")
            }
    }
}
