// Generated by alef. Do not edit by hand.
// alef:hash:0539e1fc0b063acf517daa21234cfb94c938e727d015c3b6d1cf094b4bb05451
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package dev.kreuzberg.kreuzcrawl.android

/** Response metadata extracted from HTTP headers. */
data class ResponseMeta(
    /** The ETag header value. */
    val etag: String? = null,
    /** The Last-Modified header value. */
    val lastModified: String? = null,
    /** The Cache-Control header value. */
    val cacheControl: String? = null,
    /** The Server header value. */
    val server: String? = null,
    /** The X-Powered-By header value. */
    val xPoweredBy: String? = null,
    /** The Content-Language header value. */
    val contentLanguage: String? = null,
    /** The Content-Encoding header value. */
    val contentEncoding: String? = null,
)
