<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b37c8869ab04ccaa05554e451f6e2e0ab994a61ab48967b58aa2b7e8c87905f9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef


declare(strict_types=1);

namespace Kreuzcrawl\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzcrawl\Kreuzcrawl;
use Kreuzcrawl\CrawlConfig;

/** E2e tests for category: cookies. */
final class CookiesTest extends TestCase
{
    /** Isolates cookies per domain during crawl */
    public function test_cookies_per_domain(): void
    {
        $engine_config = CrawlConfig::from_json(json_encode(["cookiesEnabled" => true, "maxDepth" => 1, "respectRobotsTxt" => false]));
        $engine = Kreuzcrawl::createEngine($engine_config);
        $url = getenv('MOCK_SERVER_URL') . '/fixtures/cookies_per_domain';
        $result = Kreuzcrawl::crawl($engine, $url);

        $this->assertEquals(1, count($result->getCookies()));
        $this->assertStringContainsString("domain_cookie", $result->getCookies());

    }


    /** Maintains cookies across multiple crawl requests */
    public function test_cookies_persistence(): void
    {
        $engine_config = CrawlConfig::from_json(json_encode(["cookiesEnabled" => true, "maxDepth" => 1, "respectRobotsTxt" => false]));
        $engine = Kreuzcrawl::createEngine($engine_config);
        $url = getenv('MOCK_SERVER_URL') . '/fixtures/cookies_persistence';
        $result = Kreuzcrawl::crawl($engine, $url);

        $this->assertStringContainsString("session", $result->getCookies());

    }


    /** Respects Set-Cookie header from server responses */
    public function test_cookies_set_cookie_response(): void
    {
        $engine_config = CrawlConfig::from_json(json_encode(["cookiesEnabled" => true, "maxDepth" => 1, "respectRobotsTxt" => false]));
        $engine = Kreuzcrawl::createEngine($engine_config);
        $url = getenv('MOCK_SERVER_URL') . '/fixtures/cookies_set_cookie_response';
        $result = Kreuzcrawl::crawl($engine, $url);

        $this->assertStringContainsString("tracking", $result->getCookies());

    }

}
