<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1b87f699746b548234fb34280354764c6f7b31e694c5d2c99969c866e1e56f26
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzcrawl\Kreuzcrawl;
use Kreuzcrawl\CrawlConfig;

/** E2e tests for category: proxy. */
final class ProxyTest extends TestCase
{
    /** Proxy with username and password credentials authenticates successfully */
    public function test_proxy_authenticated(): void
    {
        $engine_config = CrawlConfig::default();
        $engine_config->proxy = ["password" => "proxypass", "url" => "http://127.0.0.1:8889", "username" => "proxyuser"];
        $engine_config->respect_robots_txt = false;
        $engine = Kreuzcrawl::createEngine($engine_config);
        $url = getenv('MOCK_SERVER_URL') . '/fixtures/proxy_authenticated';
        $result = Kreuzcrawl::scrape_async($engine, $url);
        $this->assertEquals(200, $result->status_code);
        // skipped: field 'pages.length' not available on result type
    }

    /** Configure proxy URL and successfully crawl through it */
    public function test_proxy_basic_success(): void
    {
        $engine_config = CrawlConfig::default();
        $engine_config->proxy = ["url" => "http://127.0.0.1:8888"];
        $engine_config->respect_robots_txt = false;
        $engine = Kreuzcrawl::createEngine($engine_config);
        $url = getenv('MOCK_SERVER_URL') . '/fixtures/proxy_basic_success';
        $result = Kreuzcrawl::scrape_async($engine, $url);
        $this->assertEquals(200, $result->status_code);
        // skipped: field 'pages.length' not available on result type
    }
}
