<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c9b0d2a3dfb56b9e78a20f2176a3a0d25f8268f22862f6596fca4b7dc0041e17
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef


declare(strict_types=1);

namespace Kreuzcrawl\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzcrawl\Kreuzcrawl;use Kreuzcrawl\CrawlConfig;
/** E2e tests for category: proxy. */
final class ProxyTest extends TestCase
{

    /** Proxy with username and password credentials authenticates successfully */
    public function test_proxy_authenticated(): void
    {
        $engine_config = CrawlConfig::from_json(json_encode(["proxy" => ["password" => "proxypass", "url" => "http://127.0.0.1:8889", "username" => "proxyuser"], "respectRobotsTxt" => false]));
        $engine = Kreuzcrawl::createEngine($engine_config);
        $url = getenv('MOCK_SERVER_URL') . '/fixtures/proxy_authenticated';
        $result = Kreuzcrawl::crawl($engine, $url);

            $this->assertEquals(0, count($result->getPages()));

    }


    /** Configure proxy URL and successfully crawl through it */
    public function test_proxy_basic_success(): void
    {
        $engine_config = CrawlConfig::from_json(json_encode(["proxy" => ["url" => "http://127.0.0.1:8888"], "respectRobotsTxt" => false]));
        $engine = Kreuzcrawl::createEngine($engine_config);
        $url = getenv('MOCK_SERVER_URL') . '/fixtures/proxy_basic_success';
        $result = Kreuzcrawl::crawl($engine, $url);

            $this->assertEquals(0, count($result->getPages()));

    }

}
