// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:10fd8884dc42e20590862b58827e77a095a19786603d0504744b5cace12add36
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Article metadata extracted from {@code article:*} Open Graph tags.
 */
public record ArticleMetadata(
		/** The article publication time. */
		@JsonProperty("published_time") Optional<String> publishedTime,
		/** The article modification time. */
		@JsonProperty("modified_time") Optional<String> modifiedTime,
		/** The article author. */
		Optional<String> author,
		/** The article section. */
		Optional<String> section, /** The article tags. */
		List<String> tags) {
	public static ArticleMetadataBuilder builder() {
		return new ArticleMetadataBuilder();
	}
}
