// DO NOT EDIT - auto-generated by alef
// alef:hash:b98764eed9e96431aff145f24a6d4e7b9070a8f8550c23508a96b387827f5f1f
package dev.kreuzberg.kreuzcrawl;

/**
 * A bad gateway error occurred (HTTP 502).
 */
public class BadGatewayException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new BadGatewayException with the given message. */
  public BadGatewayException(final String message) {
    super(message);
  }

  /** Creates a new BadGatewayException with the given message and cause. */
  public BadGatewayException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
