// DO NOT EDIT - auto-generated by alef
// alef:hash:c56b59b6ea36ea384e647b230eed0057f2d0e7ef003ea475f1f9a7ced369ae61
package dev.kreuzberg.kreuzcrawl;

/**
 * A bad gateway error occurred (HTTP 502).
 */
public class BadGatewayException extends CrawlErrorException {
  /** Creates a new BadGatewayException with the given message. */
  public BadGatewayException(final String message) {
    super(message);
  }

  /** Creates a new BadGatewayException with the given message and cause. */
  public BadGatewayException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
