// DO NOT EDIT - auto-generated by alef
// alef:hash:27bc3a02497bf9c716d40fadff4236819609c40b258843d3d9b3df6e866780fa
package dev.kreuzberg.kreuzcrawl;

/**
 * A bad gateway error occurred (HTTP 502).
 */
public class BadGatewayException extends CrawlErrorException {
  /** Creates a new BadGatewayException with the given message. */
  public BadGatewayException(final String message) {
    super(message);
  }

  /** Creates a new BadGatewayException with the given message and cause. */
  public BadGatewayException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
