// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:23ddbe494ce9557b68eef4a33a33c1d32a0c48a9b9101d74f030d12a850f95ea
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jetbrains.annotations.Nullable;

/**
 * Result from a single URL in a batch scrape operation.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BatchScrapeResultBuilder.class)
public record BatchScrapeResult(
		/** The URL that was scraped. */
		String url,
		/** The scrape result, if successful. */
		@Nullable ScrapeResult result, /** The error message, if the scrape failed. */
		@Nullable String error) {
	public static BatchScrapeResultBuilder builder() {
		return new BatchScrapeResultBuilder();
	}
}
