// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:10fd8884dc42e20590862b58827e77a095a19786603d0504744b5cace12add36
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import java.util.Optional;

/**
 * Result from a single URL in a batch scrape operation.
 */
public record BatchScrapeResult(
		/** The URL that was scraped. */
		String url,
		/** The scrape result, if successful. */
		Optional<ScrapeResult> result, /** The error message, if the scrape failed. */
		Optional<String> error) {
	public static BatchScrapeResultBuilder builder() {
		return new BatchScrapeResultBuilder();
	}
}
