// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5cc4289f94d951392b6b941e0d55839a8f3961fd64e416fcd2b685bcb34a4ec4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jetbrains.annotations.Nullable;

/**
 * Result from a single URL in a batch crawl operation.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BatchCrawlResultBuilder.class)
public record BatchCrawlResult(String url, @Nullable CrawlResult result, @Nullable String error) {
	public static BatchCrawlResultBuilder builder() {
		return new BatchCrawlResultBuilder();
	}
}
