// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ac6493a3a6af78cb4d9c21a92dd6ec1e51eb0c5769e870cc3249686a88963c62
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Result from a single URL in a batch scrape operation.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class BatchScrapeResultBuilder {

    @JsonProperty("url")
    private String url = "";
    @JsonProperty("result")
    private Optional<ScrapeResult> result = Optional.empty();
    @JsonProperty("error")
    private Optional<String> error = Optional.empty();

    /** Sets the url field. */
    @JsonProperty("url")
    public BatchScrapeResultBuilder withUrl(final String value) {
        this.url = value;
        return this;
    }

    /** Sets the result field. */
    @JsonProperty("result")
    public BatchScrapeResultBuilder withResult(final Optional<ScrapeResult> value) {
        this.result = value;
        return this;
    }

    /** Sets the error field. */
    @JsonProperty("error")
    public BatchScrapeResultBuilder withError(final Optional<String> value) {
        this.error = value;
        return this;
    }

    /** Builds the BatchScrapeResult instance. */
    public BatchScrapeResult build() {
        return new BatchScrapeResult(
            url,
            result.orElse(null),
            error.orElse(null)
        );
    }
}
