// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.kreuzcrawl;

import java.util.Optional;

public record BatchScrapeResult(String url, Optional<ScrapeResult> result, Optional<String> error) {
	public static BatchScrapeResultBuilder builder() {
		return new BatchScrapeResultBuilder();
	}
}
