// DO NOT EDIT - auto-generated by alef
// alef:hash:42cba53345bfa03607a118143529cae069edebcd6e06046a0d61ed5a35b20ea3
package dev.kreuzberg.kreuzcrawl;

/**
 * The browser failed to launch, connect, or navigate.
 */
public class BrowserErrorException extends CrawlErrorException {
  /** Creates a new BrowserErrorException with the given message. */
  public BrowserErrorException(final String message) {
    super(message);
  }

  /** Creates a new BrowserErrorException with the given message and cause. */
  public BrowserErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
