// DO NOT EDIT - auto-generated by alef
// alef:hash:c71da313df7b9a37bdd4f997f05150b92dfa5e723d3e2a4db0adafea6f951837
package dev.kreuzberg.kreuzcrawl;

/**
 * The browser page load or rendering timed out.
 */
public class BrowserTimeoutException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new BrowserTimeoutException with the given message. */
  public BrowserTimeoutException(final String message) {
    super(message);
  }

  /** Creates a new BrowserTimeoutException with the given message and cause. */
  public BrowserTimeoutException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
