// DO NOT EDIT - auto-generated by alef
// alef:hash:0070221070bfc845d4cd03259048f84aee7675d5ea463a83e36621bd4b9656e4
package dev.kreuzberg.kreuzcrawl;

/**
 * The browser failed to launch, connect, or navigate.
 */
public class BrowserErrorException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new BrowserErrorException with the given message. */
  public BrowserErrorException(final String message) {
    super(message);
  }

  /** Creates a new BrowserErrorException with the given message and cause. */
  public BrowserErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
