// DO NOT EDIT - auto-generated by alef
// alef:hash:bdb701df0967a71ad55f33851f6cb2fc1adbe06fecfd322979c96c076e6e33e4
package dev.kreuzberg.kreuzcrawl;

/**
 * The browser page load or rendering timed out.
 */
public class BrowserTimeoutException extends CrawlErrorException {
    /** Creates a new BrowserTimeoutException with the given message. */
    public BrowserTimeoutException(final String message) {
        super(message);
    }

    /** Creates a new BrowserTimeoutException with the given message and cause. */
    public BrowserTimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
