// DO NOT EDIT - auto-generated by alef
// alef:hash:48966973ad2093e6029e9adac7cf0ae59c8568a56a38d3526b1aed6581f566fb
package dev.kreuzberg.kreuzcrawl;

/**
 * The browser failed to launch, connect, or navigate.
 */
public class BrowserErrorException extends CrawlErrorException {
    /** Creates a new BrowserErrorException with the given message. */
    public BrowserErrorException(final String message) {
        super(message);
    }

    /** Creates a new BrowserErrorException with the given message and cause. */
    public BrowserErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
