// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:63baffb10d907c9aee00f8fced026da0b72d45de467ea2c8a528fc550eff36a8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;

/**
 * Serialises {@code byte[]} as a JSON array of integers.
 *
 * <p>Jackson's default serialiser encodes {@code byte[]} as a base64 string, but
 * Rust's {@code serde} for {@code Vec<u8>} expects {@code [72, 101, 108, ...]}.
 * Annotate any {@code byte[]} field sent to the FFI layer with
 * {@code @JsonSerialize(using = ByteArrayToIntArraySerializer.class)}.
 */
@SuppressWarnings("PMD")
public class ByteArrayToIntArraySerializer extends StdSerializer<byte[]> {
  /** Default constructor required by Jackson. */
  public ByteArrayToIntArraySerializer() {
    super(byte[].class);
  }

  @Override
  public void serialize(
      final byte[] value, final JsonGenerator gen, final SerializerProvider provider)
      throws java.io.IOException {
    gen.writeStartArray();
    for (byte b : value) {
      gen.writeNumber(b & 0xFF);
    }
    gen.writeEndArray();
  }
}
