// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6718293b4ee21f8f28c87c0729d4ca9d2c51024b52f3414c8dc1be5c4218fd9b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

@JsonPOJOBuilder(withPrefix = "with")
public class CitationReferenceBuilder {

	private long index = 0;
	private String url = "";
	private String text = "";

	/** Sets the index field. */
	public CitationReferenceBuilder withIndex(final long value) {
		this.index = value;
		return this;
	}

	/** Sets the url field. */
	public CitationReferenceBuilder withUrl(final String value) {
		this.url = value;
		return this;
	}

	/** Sets the text field. */
	public CitationReferenceBuilder withText(final String value) {
		this.text = value;
		return this;
	}

	/** Builds the CitationReference instance. */
	public CitationReference build() {
		return new CitationReference(index, url, text);
	}
}
