// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3c9b451ae8f64e9df4826397aadd056244e92ebbe1cbcdb27c914327eb13a3e5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonPOJOBuilder(withPrefix = "with")
public class CitationReferenceBuilder {

    @JsonProperty("index")
    private long index = 0;
    @JsonProperty("url")
    private String url = "";
    @JsonProperty("text")
    private String text = "";

    /** Sets the index field. */
    @JsonProperty("index")
    public CitationReferenceBuilder withIndex(final long value) {
        this.index = value;
        return this;
    }

    /** Sets the url field. */
    @JsonProperty("url")
    public CitationReferenceBuilder withUrl(final String value) {
        this.url = value;
        return this;
    }

    /** Sets the text field. */
    @JsonProperty("text")
    public CitationReferenceBuilder withText(final String value) {
        this.text = value;
        return this;
    }

    /** Builds the CitationReference instance. */
    public CitationReference build() {
        return new CitationReference(
            index,
            url,
            text
        );
    }
}
