// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1bfc289f7248d270244fd2a64aef3762a150dc6b8965739510784cf13fbdf1e8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Result of citation conversion.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record CitationResult(String content, List<CitationReference> references) {
}
