// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b73a33597114ff0394846e1119efb35c113eb8082ca4c51a09403e3659794bb4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import java.util.List;

/**
 * Result of citation conversion.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CitationResult.Builder.class)
@SuppressWarnings("PMD")
public record CitationResult(
    @JsonProperty("content") String content,
    @JsonProperty("references") List<CitationReference> references) {
  public static Builder builder() {
    return new Builder();
  }

  // CPD-OFF
  @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
  @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
  public static final class Builder {

    private String content = "";
    private List<CitationReference> references = List.of();

    /** Sets the content field. */
    @JsonProperty("content")
    public Builder withContent(final String value) {
      this.content = value;
      return this;
    }

    /** Sets the references field. */
    @JsonProperty("references")
    public Builder withReferences(final List<CitationReference> value) {
      this.references = value;
      return this;
    }

    /** Builds the CitationResult instance. */
    public CitationResult build() {
      return new CitationResult(content, references);
    }
  }
  // CPD-ON
}
