// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:02ddda8e14e7f18cc1268b058c7d05cfd157c54147a5cf5a608f2d84c7927ac6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CitationReferenceBuilder.class)
public record CitationReference(long index, String url, String text) {
	public static CitationReferenceBuilder builder() {
		return new CitationReferenceBuilder();
	}
}
