// DO NOT EDIT - auto-generated by alef
// alef:hash:8fc3cef2ad0ada08bee1c82c39a437179e273f52f7ca6f2e98164d17d9ec34a4
package dev.kreuzberg.kreuzcrawl;

/**
 * A connection error occurred.
 */
public class ConnectionException extends CrawlErrorException {
  /** Creates a new ConnectionException with the given message. */
  public ConnectionException(final String message) {
    super(message);
  }

  /** Creates a new ConnectionException with the given message and cause. */
  public ConnectionException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
