// DO NOT EDIT - auto-generated by alef
// alef:hash:0fdfaed140238d53bc6b110bcf837bd32eea306a3658f5b7a081c6c1f37ce701
package dev.kreuzberg.kreuzcrawl;

/**
 * A connection error occurred.
 */
public class ConnectionException extends CrawlErrorException {
  /** Creates a new ConnectionException with the given message. */
  public ConnectionException(final String message) {
    super(message);
  }

  /** Creates a new ConnectionException with the given message and cause. */
  public ConnectionException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
