// DO NOT EDIT - auto-generated by alef
// alef:hash:046006c9c535ab6a0ecaa1b7ff90e95aae2b11fc446ea68adae07d5f9bdd3af2
package dev.kreuzberg.kreuzcrawl;

/**
 * A connection error occurred.
 */
public class ConnectionException extends CrawlErrorException {
    /** Creates a new ConnectionException with the given message. */
    public ConnectionException(final String message) {
        super(message);
    }

    /** Creates a new ConnectionException with the given message and cause. */
    public ConnectionException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
