// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.kreuzcrawl;

import java.util.List;
import java.util.Optional;

/**
 * Content extraction and conversion configuration.
 *
 * Controls how HTML is converted to the output format. Uses html-to-markdown-rs
 * as the conversion engine for all formats (markdown, plain text, djot).
 */
public class ContentConfigBuilder {

	private String outputFormat = "";
	private String preprocessingPreset = "";
	private boolean removeNavigation = false;
	private boolean removeForms = false;
	private List<String> stripTags = List.of();
	private List<String> preserveTags = List.of();
	private List<String> excludeSelectors = List.of();
	private boolean skipImages = false;
	private Optional<Long> maxDepth = Optional.empty();
	private boolean wrap = false;
	private long wrapWidth = 0;
	private boolean includeDocumentStructure = false;

	public ContentConfigBuilder withOutputFormat(String value) {
		this.outputFormat = value;
		return this;
	}

	public ContentConfigBuilder withPreprocessingPreset(String value) {
		this.preprocessingPreset = value;
		return this;
	}

	public ContentConfigBuilder withRemoveNavigation(boolean value) {
		this.removeNavigation = value;
		return this;
	}

	public ContentConfigBuilder withRemoveForms(boolean value) {
		this.removeForms = value;
		return this;
	}

	public ContentConfigBuilder withStripTags(List<String> value) {
		this.stripTags = value;
		return this;
	}

	public ContentConfigBuilder withPreserveTags(List<String> value) {
		this.preserveTags = value;
		return this;
	}

	public ContentConfigBuilder withExcludeSelectors(List<String> value) {
		this.excludeSelectors = value;
		return this;
	}

	public ContentConfigBuilder withSkipImages(boolean value) {
		this.skipImages = value;
		return this;
	}

	public ContentConfigBuilder withMaxDepth(Optional<Long> value) {
		this.maxDepth = value;
		return this;
	}

	public ContentConfigBuilder withWrap(boolean value) {
		this.wrap = value;
		return this;
	}

	public ContentConfigBuilder withWrapWidth(long value) {
		this.wrapWidth = value;
		return this;
	}

	public ContentConfigBuilder withIncludeDocumentStructure(boolean value) {
		this.includeDocumentStructure = value;
		return this;
	}

	public ContentConfig build() {
		return new ContentConfig(outputFormat, preprocessingPreset, removeNavigation, removeForms, stripTags,
				preserveTags, excludeSelectors, skipImages, maxDepth, wrap, wrapWidth, includeDocumentStructure);
	}
}
