// DO NOT EDIT - auto-generated by alef
// alef:hash:bdb701df0967a71ad55f33851f6cb2fc1adbe06fecfd322979c96c076e6e33e4
package dev.kreuzberg.kreuzcrawl;

/**
 * Errors that can occur during crawling, scraping, or mapping operations.
 */
public class CrawlErrorException extends Exception {
    /** Creates a new CrawlErrorException with the given message. */
    public CrawlErrorException(final String message) {
        super(message);
    }

    /** Creates a new CrawlErrorException with the given message and cause. */
    public CrawlErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
