// DO NOT EDIT - auto-generated by alef
// alef:hash:4b2ec8f37baf254f082c382d154b0b907ce8831507d1ae454a7f35f23811e026
package dev.kreuzberg.kreuzcrawl;

/** Errors that can occur during crawling, scraping, or mapping operations. */
public class CrawlErrorException extends Exception {
	/** Creates a new CrawlErrorException with the given message. */
	public CrawlErrorException(final String message) {
		super(message);
	}

	/** Creates a new CrawlErrorException with the given message and cause. */
	public CrawlErrorException(final String message, final Throwable cause) {
		super(message, cause);
	}
}
