// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.kreuzcrawl;

/** Errors that can occur during crawling, scraping, or mapping operations. */
public class CrawlErrorException extends Exception {
    public CrawlErrorException(String message) {
        super(message);
    }

    public CrawlErrorException(String message, Throwable cause) {
        super(message, cause);
    }
}
