// DO NOT EDIT - auto-generated by alef
// alef:hash:844df915154f680a35d6cba0bf29ade937e5ffa63c54639d604b2c0c18bd6a79
package dev.kreuzberg.kreuzcrawl;

/**
 * Data was lost or truncated during transfer.
 */
public class DataLossException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DataLossException with the given message. */
  public DataLossException(final String message) {
    super(message);
  }

  /** Creates a new DataLossException with the given message and cause. */
  public DataLossException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
