// DO NOT EDIT - auto-generated by alef
// alef:hash:c9b0d2a3dfb56b9e78a20f2176a3a0d25f8268f22862f6596fca4b7dc0041e17
package dev.kreuzberg.kreuzcrawl;

/**
 * Data was lost or truncated during transfer.
 */
public class DataLossException extends CrawlErrorException {
    /** Creates a new DataLossException with the given message. */
    public DataLossException(final String message) {
        super(message);
    }

    /** Creates a new DataLossException with the given message and cause. */
    public DataLossException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
