// DO NOT EDIT - auto-generated by alef
// alef:hash:3c1c2cb7c2f610995b6d15dbf1e1a6e561317ad4f7e441e40ef3a486db0f9e1e
package dev.kreuzberg.kreuzcrawl;

/**
 * URL denied by SSRF policy: private IP, metadata IP, etc.
 */
public class DeniedByPolicyException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DeniedByPolicyException with the given message. */
  public DeniedByPolicyException(final String message) {
    super(message);
  }

  /** Creates a new DeniedByPolicyException with the given message and cause. */
  public DeniedByPolicyException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
