// DO NOT EDIT - auto-generated by alef
// alef:hash:6de2d7a3fff7e34a7488334afa8e014e203513905446c2f051c0110b98c25d84
package dev.kreuzberg.kreuzcrawl;

/**
 * URL denied by SSRF policy: private IP, metadata IP, etc.
 */
public class DeniedByPolicyException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DeniedByPolicyException with the given message. */
  public DeniedByPolicyException(final String message) {
    super(message);
  }

  /** Creates a new DeniedByPolicyException with the given message and cause. */
  public DeniedByPolicyException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
