// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.kreuzcrawl;

/** A DNS resolution error occurred. */
public class DnsException extends CrawlErrorException {
  public DnsException(String message) {
    super(message);
  }

  public DnsException(String message, Throwable cause) {
    super(message, cause);
  }
}
