// DO NOT EDIT - auto-generated by alef
// alef:hash:7b9c93728a9ad6929902470aae4101dc3ceb9f7790425e064878ef114f164df6
package dev.kreuzberg.kreuzcrawl;

/**
 * A DNS resolution error occurred.
 */
public class DnsException extends CrawlErrorException {
    /** Creates a new DnsException with the given message. */
    public DnsException(final String message) {
        super(message);
    }

    /** Creates a new DnsException with the given message and cause. */
    public DnsException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
