// DO NOT EDIT - auto-generated by alef
// alef:hash:b1eaf8351c96d22db4968d7fe538e959ae14c161de2fcc6bf4533a0f6fd6d8b1
package dev.kreuzberg.kreuzcrawl;

/**
 * DNS resolution failed for hostname.
 */
public class DnsResolutionFailedException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DnsResolutionFailedException with the given message. */
  public DnsResolutionFailedException(final String message) {
    super(message);
  }

  /** Creates a new DnsResolutionFailedException with the given message and cause. */
  public DnsResolutionFailedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
