// DO NOT EDIT - auto-generated by alef
// alef:hash:176d92f5987c1de31d45b093cb97d374e225b81409de72b97c987327a8d11e76
package dev.kreuzberg.kreuzcrawl;

/**
 * DNS resolution failed for hostname.
 */
public class DnsResolutionFailedException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DnsResolutionFailedException with the given message. */
  public DnsResolutionFailedException(final String message) {
    super(message);
  }

  /** Creates a new DnsResolutionFailedException with the given message and cause. */
  public DnsResolutionFailedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
