// DO NOT EDIT - auto-generated by alef
// alef:hash:ce7d0852836f953466f527d3ad7e49112985c16055bfb2a88369a14c615d7d5d
package dev.kreuzberg.kreuzcrawl;

/**
 * DNS resolution failed for hostname.
 */
public class DnsResolutionFailedException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DnsResolutionFailedException with the given message. */
  public DnsResolutionFailedException(final String message) {
    super(message);
  }

  /** Creates a new DnsResolutionFailedException with the given message and cause. */
  public DnsResolutionFailedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
