// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:74a6fb19b54a9a9a9ac67b40bab1d5f19d8dc32329a2d46923fd1ca1bb2321b2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Metadata about an LLM extraction pass.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ExtractionMeta(
    /**
     * Estimated cost of the LLM call in USD.
     */
    @Nullable Double cost,
    /**
     * Number of prompt (input) tokens consumed.
     */
    @Nullable @JsonProperty("prompt_tokens") Long promptTokens,
    /**
     * Number of completion (output) tokens generated.
     */
    @Nullable @JsonProperty("completion_tokens") Long completionTokens,
    /**
     * The model identifier used for extraction.
     */
    @Nullable String model,
    /**
     * Number of content chunks sent to the LLM.
     */
    @JsonProperty("chunks_processed") long chunksProcessed
) {
}
