// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:10fd8884dc42e20590862b58827e77a095a19786603d0504744b5cace12add36
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import java.util.Optional;

/**
 * Information about a favicon or icon link.
 */
public class FaviconInfoBuilder {

	private String url = "";
	private String rel = "";
	private Optional<String> sizes = Optional.empty();
	private Optional<String> mimeType = Optional.empty();

	/** Sets the url field. */
	public FaviconInfoBuilder withUrl(final String value) {
		this.url = value;
		return this;
	}

	/** Sets the rel field. */
	public FaviconInfoBuilder withRel(final String value) {
		this.rel = value;
		return this;
	}

	/** Sets the sizes field. */
	public FaviconInfoBuilder withSizes(final Optional<String> value) {
		this.sizes = value;
		return this;
	}

	/** Sets the mimeType field. */
	public FaviconInfoBuilder withMimeType(final Optional<String> value) {
		this.mimeType = value;
		return this;
	}

	/** Builds the FaviconInfo instance. */
	public FaviconInfo build() {
		return new FaviconInfo(url, rel, sizes, mimeType);
	}
}
