// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0ca68837f600b021a368d04031b3f179c23e61b420b44a4e62afb4090be69525
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The type of a feed (RSS, Atom, or JSON Feed).
 */
public enum FeedType {
    /**
     * RSS feed.
     */
    Rss("rss"),
    /**
     * Atom feed.
     */
    Atom("atom"),
    /**
     * JSON Feed.
     */
    JsonFeed("json_feed");

    /** The string value. */
    private final String value;

    FeedType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static FeedType fromValue(final String value) {
        for (FeedType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
