// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c7ccb8950f448d5ad65e78649c618fb261c896faa19f3af6273aa19a09c8d4b9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The type of a feed (RSS, Atom, or JSON Feed).
 */
@SuppressWarnings("PMD")
public enum FeedType {
  /**
   * RSS feed.
   */
  Rss("rss"),
  /**
   * Atom feed.
   */
  Atom("atom"),
  /**
   * JSON Feed.
   */
  JsonFeed("json_feed");

  /** The string value. */
  private final String value;

  FeedType(final String value) {
    this.value = value;
  }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static FeedType fromValue(final String value) {
    for (FeedType e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown FeedType value: " + value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
