// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d0eca8259f1f191ea4be9b4c5bb5fcdc7dc19437ba1367971e3b413b4f6b6281
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Information about a feed link found on a page.
 */
public record FeedInfo(
		/** The feed URL. */
		String url,
		/** The feed title, if present. */
		Optional<String> title, /** The type of feed. */
		@JsonProperty("feed_type") FeedType feedType) {
	public static FeedInfoBuilder builder() {
		return new FeedInfoBuilder();
	}
}
