// DO NOT EDIT - auto-generated by alef
// alef:hash:9895b60f6d5fb095c6d1779bde7879c8e27380ad73a146ca4a5888f7696c339d
package dev.kreuzberg.kreuzcrawl;

/**
 * The request was forbidden (HTTP 403).
 */
public class ForbiddenException extends CrawlErrorException {
  /** Creates a new ForbiddenException with the given message. */
  public ForbiddenException(final String message) {
    super(message);
  }

  /** Creates a new ForbiddenException with the given message and cause. */
  public ForbiddenException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
