// DO NOT EDIT - auto-generated by alef
// alef:hash:5fe7349bb6652c47fba5231171bbafdd1bf743e1c6c68fe6b52bcecda7a5f8c1
package dev.kreuzberg.kreuzcrawl;

/**
 * The request was forbidden (HTTP 403).
 */
public class ForbiddenException extends CrawlErrorException {
  /** Creates a new ForbiddenException with the given message. */
  public ForbiddenException(final String message) {
    super(message);
  }

  /** Creates a new ForbiddenException with the given message and cause. */
  public ForbiddenException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
