// DO NOT EDIT - auto-generated by alef
// alef:hash:c71c6cebc3048c2cd2c1e6daba158174f156e790d59b506d304c335b9728d6df
package dev.kreuzberg.kreuzcrawl;

/**
 * The request was forbidden (HTTP 403).
 */
public class ForbiddenException extends CrawlErrorException {
    /** Creates a new ForbiddenException with the given message. */
    public ForbiddenException(final String message) {
        super(message);
    }

    /** Creates a new ForbiddenException with the given message and cause. */
    public ForbiddenException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
