// DO NOT EDIT - auto-generated by alef
// alef:hash:c71c6cebc3048c2cd2c1e6daba158174f156e790d59b506d304c335b9728d6df
package dev.kreuzberg.kreuzcrawl;

/**
 * The resource is permanently gone (HTTP 410).
 */
public class GoneException extends CrawlErrorException {
    /** Creates a new GoneException with the given message. */
    public GoneException(final String message) {
        super(message);
    }

    /** Creates a new GoneException with the given message and cause. */
    public GoneException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
