// DO NOT EDIT - auto-generated by alef
// alef:hash:bf67966050b906a100b333792343c0107588bb2f57d007e4f430441fa364f639
package dev.kreuzberg.kreuzcrawl;

/**
 * The resource is permanently gone (HTTP 410).
 */
public class GoneException extends CrawlErrorException {
	/** Creates a new GoneException with the given message. */
	public GoneException(final String message) {
		super(message);
	}

	/** Creates a new GoneException with the given message and cause. */
	public GoneException(final String message, final Throwable cause) {
		super(message, cause);
	}
}
