// DO NOT EDIT - auto-generated by alef
// alef:hash:8b342312994c200c31887452a5ad22f8673b2e1634e9a5593bf410b8f31e82e0
package dev.kreuzberg.kreuzcrawl;

/**
 * The resource is permanently gone (HTTP 410).
 */
public class GoneException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new GoneException with the given message. */
  public GoneException(final String message) {
    super(message);
  }

  /** Creates a new GoneException with the given message and cause. */
  public GoneException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
