// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e54d8704dca901eeddf053eafac9195d0827bf50ee9d477fd8ec022968eeb13e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

/**
 * A heading element extracted from the page.
 */
public record HeadingInfo(byte level, String text) {
	public static HeadingInfoBuilder builder() {
		return new HeadingInfoBuilder();
	}
}
