// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a1a1685027ba4a27308f011607a5bc08ef1d9d47f6caaa93530de6531a67464b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * A heading element extracted from the page.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = HeadingInfo.Builder.class)
public record HeadingInfo(@JsonProperty("level") byte level, @JsonProperty("text") String text) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private byte level = 0;
private String text = "";

        /** Sets the level field. */
        @JsonProperty("level")
        public Builder withLevel(final byte value) {
            this.level = value;
            return this;
        }

        /** Sets the text field. */
        @JsonProperty("text")
        public Builder withText(final String value) {
            this.text = value;
            return this;
        }

        /** Builds the HeadingInfo instance. */
        public HeadingInfo build() {
            return new HeadingInfo(
                level,
                text
            );
        }
    }
    // CPD-ON
}
