// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e717682acd1f5afb6885c4cd873be1de5eab7f9936979a56dc75ea6d9413088a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * A heading element extracted from the page.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = HeadingInfoBuilder.class)
public record HeadingInfo(byte level, String text) {
    public static HeadingInfoBuilder builder() {
        return new HeadingInfoBuilder();
    }

    /**
     * Parse a {@code HeadingInfo} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws RuntimeException if the JSON cannot be deserialised.
     */
    public static HeadingInfo fromJson(String json) {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, HeadingInfo.class);
        } catch (Exception e) {
            throw new RuntimeException("Failed to parse HeadingInfo from JSON", e);
        }
    }
}
