// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c71c6cebc3048c2cd2c1e6daba158174f156e790d59b506d304c335b9728d6df
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * An hreflang alternate link entry.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = HreflangEntry.Builder.class)
public record HreflangEntry(@JsonProperty("lang") String lang, @JsonProperty("url") String url) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private String lang = "";
private String url = "";

        /** Sets the lang field. */
        @JsonProperty("lang")
        public Builder withLang(final String value) {
            this.lang = value;
            return this;
        }

        /** Sets the url field. */
        @JsonProperty("url")
        public Builder withUrl(final String value) {
            this.url = value;
            return this;
        }

        /** Builds the HreflangEntry instance. */
        public HreflangEntry build() {
            return new HreflangEntry(
                lang,
                url
            );
        }
    }
    // CPD-ON
}
