// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b6e5572ef25948cd19f7269e7646ae76aa1364ca90f21c181425a292adae4e1b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * An hreflang alternate link entry.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = HreflangEntryBuilder.class)
public record HreflangEntry(String lang, String url) {
	public static HreflangEntryBuilder builder() {
		return new HreflangEntryBuilder();
	}
}
