// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5bd2ee2e8c88a47b18ee27849bc196a1257ba8fe1d47f0fcf0d46feb5506b27b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * An hreflang alternate link entry.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record HreflangEntry(String lang, String url) {
}
