// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2325cbcd2a621a460255c59880e840e94a4f89e38da908cf0595a55a3ff4ccf6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jetbrains.annotations.Nullable;

/**
 * Information about an image found on a page.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ImageInfoBuilder.class)
public record ImageInfo(
		/** The image URL. */
		String url,
		/** The alt text, if present. */
		@Nullable String alt,
		/** The width attribute, if present and parseable. */
		@Nullable Integer width,
		/** The height attribute, if present and parseable. */
		@Nullable Integer height, /** The source of the image reference. */
		ImageSource source) {
	public static ImageInfoBuilder builder() {
		return new ImageInfoBuilder();
	}
}
