// DO NOT EDIT - auto-generated by alef
// alef:hash:ffd5d6426918a5966cdb0138af39453693f90932065e82c0c61b06b395c5651a
package dev.kreuzberg.kreuzcrawl;

/**
 * The provided configuration is invalid.
 */
public class InvalidConfigException extends CrawlErrorException {
    /** Creates a new InvalidConfigException with the given message. */
    public InvalidConfigException(final String message) {
        super(message);
    }

    /** Creates a new InvalidConfigException with the given message and cause. */
    public InvalidConfigException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
