// DO NOT EDIT - auto-generated by alef
// alef:hash:5e4d7896ac784966833ca07a9e0f5bf0dbaf219e0d4fb95a18b4c8688bef1708
package dev.kreuzberg.kreuzcrawl;

/**
 * The provided configuration is invalid.
 */
public class InvalidConfigException extends CrawlErrorException {
  /** Creates a new InvalidConfigException with the given message. */
  public InvalidConfigException(final String message) {
    super(message);
  }

  /** Creates a new InvalidConfigException with the given message and cause. */
  public InvalidConfigException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
