// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0539e1fc0b063acf517daa21234cfb94c938e727d015c3b6d1cf094b4bb05451
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.kreuzcrawl;

/** Exception thrown when input validation fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class InvalidInputException extends KreuzcrawlRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidInputException. */
  public InvalidInputException(final String message) {
    super(1, message);
  }

  /** Creates a new InvalidInputException with a cause. */
  public InvalidInputException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
