// DO NOT EDIT - auto-generated by alef
// alef:hash:6de2d7a3fff7e34a7488334afa8e014e203513905446c2f051c0110b98c25d84
package dev.kreuzberg.kreuzcrawl;

/**
 * Invalid URL format.
 */
public class InvalidUrlException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidUrlException with the given message. */
  public InvalidUrlException(final String message) {
    super(message);
  }

  /** Creates a new InvalidUrlException with the given message and cause. */
  public InvalidUrlException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
