// DO NOT EDIT - auto-generated by alef
// alef:hash:f2c1a82d7c896efc81bbc3daa5c0505f7420ca03a71dd58c1004c9f98988e6da
package dev.kreuzberg.kreuzcrawl;

/**
 * The provided configuration is invalid.
 */
public class InvalidConfigException extends CrawlErrorException {
  /** Creates a new InvalidConfigException with the given message. */
  public InvalidConfigException(final String message) {
    super(message);
  }

  /** Creates a new InvalidConfigException with the given message and cause. */
  public InvalidConfigException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
