// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6de2d7a3fff7e34a7488334afa8e014e203513905446c2f051c0110b98c25d84
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.kreuzcrawl;

/** Exception thrown by KreuzcrawlRs. */
public class KreuzcrawlRsException extends Exception {
  private static final long serialVersionUID = 1L;
  /** The error code. */
  private final int code;

  /** Creates a new KreuzcrawlRsException. */
  public KreuzcrawlRsException(final int code, final String message) {
    super(message);
    this.code = code;
  }

  /** Creates a new KreuzcrawlRsException with a cause. */
  public KreuzcrawlRsException(final String message, final Throwable cause) {
    super(message, cause);
    this.code = -1;
  }

  /** Returns the error code. */
  public int getCode() {
    return code;
  }
}
