// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b1eaf8351c96d22db4968d7fe538e959ae14c161de2fcc6bf4533a0f6fd6d8b1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.kreuzcrawl;

/** Exception thrown by KreuzcrawlRs. */
public class KreuzcrawlRsException extends Exception {
  private static final long serialVersionUID = 1L;
  /** The error code. */
  private final int code;

  /** Creates a new KreuzcrawlRsException. */
  public KreuzcrawlRsException(final int code, final String message) {
    super(message);
    this.code = code;
  }

  /** Creates a new KreuzcrawlRsException with a cause. */
  public KreuzcrawlRsException(final String message, final Throwable cause) {
    super(message, cause);
    this.code = -1;
  }

  /** Returns the error code. */
  public int getCode() {
    return code;
  }
}
