// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0fdfaed140238d53bc6b110bcf837bd32eea306a3658f5b7a081c6c1f37ce701
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.kreuzcrawl;

/** Exception thrown by KreuzcrawlRs. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class KreuzcrawlRsException extends Exception {
    /** The error code. */
    private final int code;

    /** Creates a new KreuzcrawlRsException. */
    public KreuzcrawlRsException(final int code, final String message) {
        super(message);
        this.code = code;
    }

    /** Creates a new KreuzcrawlRsException with a cause. */
    public KreuzcrawlRsException(final String message, final Throwable cause) {
        super(message, cause);
        this.code = -1;
    }

    /** Returns the error code. */
    public int getCode() {
        return code;
    }
}
