// DO NOT EDIT - auto-generated by alef
// alef:hash:0ca68837f600b021a368d04031b3f179c23e61b420b44a4e62afb4090be69525
package dev.kreuzberg.kreuzcrawl;

/**
 * The requested page was not found (HTTP 404).
 */
public class NotFoundException extends CrawlErrorException {
    /** Creates a new NotFoundException with the given message. */
    public NotFoundException(final String message) {
        super(message);
    }

    /** Creates a new NotFoundException with the given message and cause. */
    public NotFoundException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
