// DO NOT EDIT - auto-generated by alef
// alef:hash:0918d261d00df25528ad43e170ebb4136bcf9ba7e27dbb81f6ad604080475b6b
package dev.kreuzberg.kreuzcrawl;

/**
 * The requested page was not found (HTTP 404).
 */
public class NotFoundException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new NotFoundException with the given message. */
  public NotFoundException(final String message) {
    super(message);
  }

  /** Creates a new NotFoundException with the given message and cause. */
  public NotFoundException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
