// DO NOT EDIT - auto-generated by alef
// alef:hash:f2acf0fe68bedde7da1909fa6feedaffb995d5aec49220ec23bf64125a392d19
package dev.kreuzberg.kreuzcrawl;

/**
 * The requested page was not found (HTTP 404).
 */
public class NotFoundException extends CrawlErrorException {
  /** Creates a new NotFoundException with the given message. */
  public NotFoundException(final String message) {
    super(message);
  }

  /** Creates a new NotFoundException with the given message and cause. */
  public NotFoundException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
