// DO NOT EDIT - auto-generated by alef
// alef:hash:aa7504a8f66d06e6d06ebc173a17ed5956f42308b0c1c28a391e350e9ff7c302
package dev.kreuzberg.kreuzcrawl;

/**
 * An unclassified error occurred.
 */
public class OtherException extends CrawlErrorException {
  /** Creates a new OtherException with the given message. */
  public OtherException(final String message) {
    super(message);
  }

  /** Creates a new OtherException with the given message and cause. */
  public OtherException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
