// DO NOT EDIT - auto-generated by alef
// alef:hash:835d6da2fd74ea3e92d27bb3bd18ac61f50e74ada570fba813efb521101172a2
package dev.kreuzberg.kreuzcrawl;

/**
 * An unclassified error occurred.
 */
public class OtherException extends CrawlErrorException {
    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
