// DO NOT EDIT - auto-generated by alef
// alef:hash:339ef1873e5d94ff9c5e3e64ebf72329a75f6cd042117527a2ea1ebb192fb19b
package dev.kreuzberg.kreuzcrawl;

/**
 * The request was rate-limited (HTTP 429).
 */
public class RateLimitedException extends CrawlErrorException {
	/** Creates a new RateLimitedException with the given message. */
	public RateLimitedException(final String message) {
		super(message);
	}

	/** Creates a new RateLimitedException with the given message and cause. */
	public RateLimitedException(final String message, final Throwable cause) {
		super(message, cause);
	}
}
