// DO NOT EDIT - auto-generated by alef
// alef:hash:0fdfaed140238d53bc6b110bcf837bd32eea306a3658f5b7a081c6c1f37ce701
package dev.kreuzberg.kreuzcrawl;

/**
 * The request was rate-limited (HTTP 429).
 */
public class RateLimitedException extends CrawlErrorException {
    /** Creates a new RateLimitedException with the given message. */
    public RateLimitedException(final String message) {
        super(message);
    }

    /** Creates a new RateLimitedException with the given message and cause. */
    public RateLimitedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
