// DO NOT EDIT - auto-generated by alef
// alef:hash:bcc3d5bd544a6e7593876ab5de51eb8c1f53d0d8d2c8c3d31c436d54ead6b3ec
package dev.kreuzberg.kreuzcrawl;

/**
 * The request was rate-limited (HTTP 429).
 */
public class RateLimitedException extends CrawlErrorException {
  /** Creates a new RateLimitedException with the given message. */
  public RateLimitedException(final String message) {
    super(message);
  }

  /** Creates a new RateLimitedException with the given message and cause. */
  public RateLimitedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
