// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d6f304ba5891ff2e2d10e9a77d71ae7fabc846e2b9e5dc55877738577e419b4a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Response metadata extracted from HTTP headers.
 */
public record ResponseMeta(
		/** The ETag header value. */
		Optional<String> etag,
		/** The Last-Modified header value. */
		@JsonProperty("last_modified") Optional<String> lastModified,
		/** The Cache-Control header value. */
		@JsonProperty("cache_control") Optional<String> cacheControl,
		/** The Server header value. */
		Optional<String> server,
		/** The X-Powered-By header value. */
		@JsonProperty("x_powered_by") Optional<String> xPoweredBy,
		/** The Content-Language header value. */
		@JsonProperty("content_language") Optional<String> contentLanguage, /** The Content-Encoding header value. */
		@JsonProperty("content_encoding") Optional<String> contentEncoding) {
	public static ResponseMetaBuilder builder() {
		return new ResponseMetaBuilder();
	}
}
