// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b1eaf8351c96d22db4968d7fe538e959ae14c161de2fcc6bf4533a0f6fd6d8b1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.kreuzcrawl;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * The result of a single-page scrape operation.
 */
@SuppressWarnings({"PMD.LongVariable"})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ScrapeResult.Builder.class)
public record ScrapeResult(
    @JsonProperty("status_code") short statusCode,
    @JsonProperty("final_url") String finalUrl,
    @JsonProperty("content_type") String contentType,
    @JsonProperty("html") String html,
    @JsonProperty("body_size") long bodySize,
    @JsonProperty("metadata") PageMetadata metadata,
    @JsonProperty("links") List<LinkInfo> links,
    @JsonProperty("images") List<ImageInfo> images,
    @JsonProperty("feeds") List<FeedInfo> feeds,
    @JsonProperty("json_ld") List<JsonLdEntry> jsonLd,
    @JsonProperty("is_allowed") boolean isAllowed,
    @Nullable @JsonProperty("crawl_delay") Long crawlDelay,
    @JsonProperty("noindex_detected") boolean noindexDetected,
    @JsonProperty("nofollow_detected") boolean nofollowDetected,
    @Nullable @JsonProperty("x_robots_tag") String xRobotsTag,
    @JsonProperty("is_pdf") boolean isPdf,
    @JsonProperty("was_skipped") boolean wasSkipped,
    @Nullable @JsonProperty("detected_charset") String detectedCharset,
    @JsonProperty("auth_header_sent") boolean authHeaderSent,
    @Nullable @JsonProperty("response_meta") ResponseMeta responseMeta,
    @JsonProperty("assets") List<DownloadedAsset> assets,
    @JsonProperty("js_render_hint") boolean jsRenderHint,
    @JsonProperty("browser_used") boolean browserUsed,
    @Nullable @JsonProperty("markdown") MarkdownResult markdown,
    @Nullable @JsonProperty("extracted_data") Object extractedData,
    @Nullable @JsonProperty("extraction_meta") ExtractionMeta extractionMeta,
    @Nullable @JsonProperty("downloaded_document") DownloadedDocument downloadedDocument,
    @Nullable @JsonProperty("browser") BrowserExtras browser
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for ScrapeResult deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        /** statusCode. */
        @JsonProperty("status_code")
        private final short statusCode;
        /** finalUrl. */
        @JsonProperty("final_url")
        private final String finalUrl;
        /** contentType. */
        @JsonProperty("content_type")
        private final String contentType;
        /** html. */
        private final String html;
        /** bodySize. */
        @JsonProperty("body_size")
        private final long bodySize;
        /** metadata. */
        private final PageMetadata metadata;
        /** links. */
        private final List<LinkInfo> links = List.of();
        /** images. */
        private final List<ImageInfo> images = List.of();
        /** feeds. */
        private final List<FeedInfo> feeds = List.of();
        /** jsonLd. */
        @JsonProperty("json_ld")
        private final List<JsonLdEntry> jsonLd = List.of();
        /** isAllowed. */
        @JsonProperty("is_allowed")
        private final boolean isAllowed;
        /** crawlDelay. */
        @JsonProperty("crawl_delay")
        private final Long crawlDelay;
        /** noindexDetected. */
        @JsonProperty("noindex_detected")
        private final boolean noindexDetected;
        /** nofollowDetected. */
        @JsonProperty("nofollow_detected")
        private final boolean nofollowDetected;
        /** xRobotsTag. */
        @JsonProperty("x_robots_tag")
        private final String xRobotsTag;
        /** isPdf. */
        @JsonProperty("is_pdf")
        private final boolean isPdf;
        /** wasSkipped. */
        @JsonProperty("was_skipped")
        private final boolean wasSkipped;
        /** detectedCharset. */
        @JsonProperty("detected_charset")
        private final String detectedCharset;
        /** authHeaderSent. */
        @JsonProperty("auth_header_sent")
        private final boolean authHeaderSent;
        /** responseMeta. */
        @JsonProperty("response_meta")
        private final ResponseMeta responseMeta;
        /** assets. */
        private final List<DownloadedAsset> assets = List.of();
        /** jsRenderHint. */
        @JsonProperty("js_render_hint")
        private final boolean jsRenderHint;
        /** browserUsed. */
        @JsonProperty("browser_used")
        private final boolean browserUsed;
        /** markdown. */
        private final MarkdownResult markdown;
        /** extractedData. */
        @JsonProperty("extracted_data")
        private final Object extractedData;
        /** extractionMeta. */
        @JsonProperty("extraction_meta")
        private final ExtractionMeta extractionMeta;
        /** downloadedDocument. */
        @JsonProperty("downloaded_document")
        private final DownloadedDocument downloadedDocument;
        /** browser. */
        private final BrowserExtras browser;

        /** Sets the statusCode field. */
        @JsonProperty("status_code")
        public Builder withStatusCode(final short value) {
            this.statusCode = value;
            return this;
        }

        /** Sets the finalUrl field. */
        @JsonProperty("final_url")
        public Builder withFinalUrl(final String value) {
            this.finalUrl = value;
            return this;
        }

        /** Sets the contentType field. */
        @JsonProperty("content_type")
        public Builder withContentType(final String value) {
            this.contentType = value;
            return this;
        }

        /** Sets the html field. */
        @JsonProperty("html")
        public Builder withHtml(final String value) {
            this.html = value;
            return this;
        }

        /** Sets the bodySize field. */
        @JsonProperty("body_size")
        public Builder withBodySize(final long value) {
            this.bodySize = value;
            return this;
        }

        /** Sets the metadata field. */
        @JsonProperty("metadata")
        public Builder withMetadata(final PageMetadata value) {
            this.metadata = value;
            return this;
        }

        /** Sets the links field. */
        @JsonProperty("links")
        public Builder withLinks(final List<LinkInfo> value) {
            this.links = value;
            return this;
        }

        /** Sets the images field. */
        @JsonProperty("images")
        public Builder withImages(final List<ImageInfo> value) {
            this.images = value;
            return this;
        }

        /** Sets the feeds field. */
        @JsonProperty("feeds")
        public Builder withFeeds(final List<FeedInfo> value) {
            this.feeds = value;
            return this;
        }

        /** Sets the jsonLd field. */
        @JsonProperty("json_ld")
        public Builder withJsonLd(final List<JsonLdEntry> value) {
            this.jsonLd = value;
            return this;
        }

        /** Sets the isAllowed field. */
        @JsonProperty("is_allowed")
        public Builder withIsAllowed(final boolean value) {
            this.isAllowed = value;
            return this;
        }

        /** Sets the crawlDelay field. */
        @JsonProperty("crawl_delay")
        public Builder withCrawlDelay(final @Nullable long value) {
            this.crawlDelay = value;
            return this;
        }

        /** Sets the noindexDetected field. */
        @JsonProperty("noindex_detected")
        public Builder withNoindexDetected(final boolean value) {
            this.noindexDetected = value;
            return this;
        }

        /** Sets the nofollowDetected field. */
        @JsonProperty("nofollow_detected")
        public Builder withNofollowDetected(final boolean value) {
            this.nofollowDetected = value;
            return this;
        }

        /** Sets the xRobotsTag field. */
        @JsonProperty("x_robots_tag")
        public Builder withXRobotsTag(final @Nullable String value) {
            this.xRobotsTag = value;
            return this;
        }

        /** Sets the isPdf field. */
        @JsonProperty("is_pdf")
        public Builder withIsPdf(final boolean value) {
            this.isPdf = value;
            return this;
        }

        /** Sets the wasSkipped field. */
        @JsonProperty("was_skipped")
        public Builder withWasSkipped(final boolean value) {
            this.wasSkipped = value;
            return this;
        }

        /** Sets the detectedCharset field. */
        @JsonProperty("detected_charset")
        public Builder withDetectedCharset(final @Nullable String value) {
            this.detectedCharset = value;
            return this;
        }

        /** Sets the authHeaderSent field. */
        @JsonProperty("auth_header_sent")
        public Builder withAuthHeaderSent(final boolean value) {
            this.authHeaderSent = value;
            return this;
        }

        /** Sets the responseMeta field. */
        @JsonProperty("response_meta")
        public Builder withResponseMeta(final @Nullable ResponseMeta value) {
            this.responseMeta = value;
            return this;
        }

        /** Sets the assets field. */
        @JsonProperty("assets")
        public Builder withAssets(final List<DownloadedAsset> value) {
            this.assets = value;
            return this;
        }

        /** Sets the jsRenderHint field. */
        @JsonProperty("js_render_hint")
        public Builder withJsRenderHint(final boolean value) {
            this.jsRenderHint = value;
            return this;
        }

        /** Sets the browserUsed field. */
        @JsonProperty("browser_used")
        public Builder withBrowserUsed(final boolean value) {
            this.browserUsed = value;
            return this;
        }

        /** Sets the markdown field. */
        @JsonProperty("markdown")
        public Builder withMarkdown(final @Nullable MarkdownResult value) {
            this.markdown = value;
            return this;
        }

        /** Sets the extractedData field. */
        @JsonProperty("extracted_data")
        public Builder withExtractedData(final @Nullable Object value) {
            this.extractedData = value;
            return this;
        }

        /** Sets the extractionMeta field. */
        @JsonProperty("extraction_meta")
        public Builder withExtractionMeta(final @Nullable ExtractionMeta value) {
            this.extractionMeta = value;
            return this;
        }

        /** Sets the downloadedDocument field. */
        @JsonProperty("downloaded_document")
        public Builder withDownloadedDocument(final @Nullable DownloadedDocument value) {
            this.downloadedDocument = value;
            return this;
        }

        /** Sets the browser field. */
        @JsonProperty("browser")
        public Builder withBrowser(final @Nullable BrowserExtras value) {
            this.browser = value;
            return this;
        }

        /** Constructs a ScrapeResult instance from the builder's current state. */
        public ScrapeResult build() {
            return new ScrapeResult(
                statusCode,
                finalUrl,
                contentType,
                html,
                bodySize,
                metadata,
                links,
                images,
                feeds,
                jsonLd,
                isAllowed,
                crawlDelay,
                noindexDetected,
                nofollowDetected,
                xRobotsTag,
                isPdf,
                wasSkipped,
                detectedCharset,
                authHeaderSent,
                responseMeta,
                assets,
                jsRenderHint,
                browserUsed,
                markdown,
                extractedData,
                extractionMeta,
                downloadedDocument,
                browser
            );
        }
    }
    // CPD-ON
}
