// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:835d6da2fd74ea3e92d27bb3bd18ac61f50e74ada570fba813efb521101172a2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Direction for a scroll action.
 */
public enum ScrollDirection {
    /**
     * Scroll upward.
     */
    Up("up"),
    /**
     * Scroll downward.
     */
    Down("down");

    /** The string value. */
    private final String value;

    ScrollDirection(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ScrollDirection fromValue(final String value) {
        for (ScrollDirection e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
