// DO NOT EDIT - auto-generated by alef
// alef:hash:f2c1a82d7c896efc81bbc3daa5c0505f7420ca03a71dd58c1004c9f98988e6da
package dev.kreuzberg.kreuzcrawl;

/**
 * A server error occurred (HTTP 5xx).
 */
public class ServerErrorException extends CrawlErrorException {
  /** Creates a new ServerErrorException with the given message. */
  public ServerErrorException(final String message) {
    super(message);
  }

  /** Creates a new ServerErrorException with the given message and cause. */
  public ServerErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
