// DO NOT EDIT - auto-generated by alef
// alef:hash:f2acf0fe68bedde7da1909fa6feedaffb995d5aec49220ec23bf64125a392d19
package dev.kreuzberg.kreuzcrawl;

/**
 * A server error occurred (HTTP 5xx).
 */
public class ServerErrorException extends CrawlErrorException {
  /** Creates a new ServerErrorException with the given message. */
  public ServerErrorException(final String message) {
    super(message);
  }

  /** Creates a new ServerErrorException with the given message and cause. */
  public ServerErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
