// DO NOT EDIT - auto-generated by alef
// alef:hash:0070221070bfc845d4cd03259048f84aee7675d5ea463a83e36621bd4b9656e4
package dev.kreuzberg.kreuzcrawl;

/**
 * A server error occurred (HTTP 5xx).
 */
public class ServerErrorException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ServerErrorException with the given message. */
  public ServerErrorException(final String message) {
    super(message);
  }

  /** Creates a new ServerErrorException with the given message and cause. */
  public ServerErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
