// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f1fc43546a583f73990a1542aaaf0f3fd4cbe890d6475be378b9df8eb182c768
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import java.util.Optional;

/**
 * A URL entry from a sitemap.
 */
public record SitemapUrl(
		/** The URL. */
		String url,
		/** The last modification date, if present. */
		Optional<String> lastmod,
		/** The change frequency, if present. */
		Optional<String> changefreq, /** The priority, if present. */
		Optional<String> priority) {
	public static SitemapUrlBuilder builder() {
		return new SitemapUrlBuilder();
	}
}
