// DO NOT EDIT - auto-generated by alef
// alef:hash:4a1130eaa7f8e3312e90b66f3eb0a52e657e6378ee013ed7eeaada8817434913
package dev.kreuzberg.kreuzcrawl;

/**
 * An SSL/TLS error occurred.
 */
public class SslException extends CrawlErrorException {
  /** Creates a new SslException with the given message. */
  public SslException(final String message) {
    super(message);
  }

  /** Creates a new SslException with the given message and cause. */
  public SslException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
