// DO NOT EDIT - auto-generated by alef
// alef:hash:42cba53345bfa03607a118143529cae069edebcd6e06046a0d61ed5a35b20ea3
package dev.kreuzberg.kreuzcrawl;

/**
 * An SSL/TLS error occurred.
 */
public class SslException extends CrawlErrorException {
  /** Creates a new SslException with the given message. */
  public SslException(final String message) {
    super(message);
  }

  /** Creates a new SslException with the given message and cause. */
  public SslException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
