// DO NOT EDIT - auto-generated by alef
// alef:hash:62f1feacfbb1003c06558c46ed6cf6504763e8ac7843ddccd1925beece81240a
package dev.kreuzberg.kreuzcrawl;

/**
 * An SSL/TLS error occurred.
 */
public class SslException extends CrawlErrorException {
    /** Creates a new SslException with the given message. */
    public SslException(final String message) {
        super(message);
    }

    /** Creates a new SslException with the given message and cause. */
    public SslException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
