// DO NOT EDIT - auto-generated by alef
// alef:hash:64f1dccc2b627e045228bee042af14577c9c807584398094928d2095eb008f90
package dev.kreuzberg.kreuzcrawl;

/**
 * A URL was rejected by SSRF policy (private IP, metadata, disallowed scheme, etc).
 */
public class SsrfPolicyViolationException extends CrawlErrorException {
  /** Creates a new SsrfPolicyViolationException with the given message. */
  public SsrfPolicyViolationException(final String message) {
    super(message);
  }

  /** Creates a new SsrfPolicyViolationException with the given message and cause. */
  public SsrfPolicyViolationException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
