// DO NOT EDIT - auto-generated by alef
// alef:hash:4a1130eaa7f8e3312e90b66f3eb0a52e657e6378ee013ed7eeaada8817434913
package dev.kreuzberg.kreuzcrawl;

/**
 * The request timed out.
 */
public class TimeoutException extends CrawlErrorException {
  /** Creates a new TimeoutException with the given message. */
  public TimeoutException(final String message) {
    super(message);
  }

  /** Creates a new TimeoutException with the given message and cause. */
  public TimeoutException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
