// DO NOT EDIT - auto-generated by alef
// alef:hash:12ca26810aaedabcfac436caf5c5acc9524800d76d8c3b04b0e436fb02d0a7cb
package dev.kreuzberg.kreuzcrawl;

/**
 * The request timed out.
 */
public class TimeoutException extends CrawlErrorException {
    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
