// DO NOT EDIT - auto-generated by alef
// alef:hash:f2acf0fe68bedde7da1909fa6feedaffb995d5aec49220ec23bf64125a392d19
package dev.kreuzberg.kreuzcrawl;

/**
 * The request timed out.
 */
public class TimeoutException extends CrawlErrorException {
  /** Creates a new TimeoutException with the given message. */
  public TimeoutException(final String message) {
    super(message);
  }

  /** Creates a new TimeoutException with the given message and cause. */
  public TimeoutException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
