// DO NOT EDIT - auto-generated by alef
// alef:hash:689137b0ed6ef11560caf21444ae822de5314052bfb7cb5d27829dfb1e7c80ed
package dev.kreuzberg.kreuzcrawl;

/**
 * Too many HTTP redirects encountered during validation.
 */
public class TooManyRedirectsException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new TooManyRedirectsException with the given message. */
  public TooManyRedirectsException(final String message) {
    super(message);
  }

  /** Creates a new TooManyRedirectsException with the given message and cause. */
  public TooManyRedirectsException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
