// DO NOT EDIT - auto-generated by alef
// alef:hash:15d02c69c38615e96464c441d5b862382f273470e44d070f76004da0d2cf8812
package dev.kreuzberg.kreuzcrawl;

/**
 * The request was unauthorized (HTTP 401).
 */
public class UnauthorizedException extends CrawlErrorException {
    /** Creates a new UnauthorizedException with the given message. */
    public UnauthorizedException(final String message) {
        super(message);
    }

    /** Creates a new UnauthorizedException with the given message and cause. */
    public UnauthorizedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
