// DO NOT EDIT - auto-generated by alef
// alef:hash:9cb269b0ed2a5c3f6288d3cbbc0f267d59bcad18efb8c8a8ed5643d0f9e2dada
package dev.kreuzberg.kreuzcrawl;

/**
 * The request was unauthorized (HTTP 401).
 */
public class UnauthorizedException extends CrawlErrorException {
    /** Creates a new UnauthorizedException with the given message. */
    public UnauthorizedException(final String message) {
        super(message);
    }

    /** Creates a new UnauthorizedException with the given message and cause. */
    public UnauthorizedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
