// DO NOT EDIT - auto-generated by alef
// alef:hash:87eeabe6555261f7b3e97e8ed066b9a9260e9a6fc3948900feefea30a5820892
package dev.kreuzberg.kreuzcrawl;

/**
 * The request was unauthorized (HTTP 401).
 */
public class UnauthorizedException extends CrawlErrorException {
  /** Creates a new UnauthorizedException with the given message. */
  public UnauthorizedException(final String message) {
    super(message);
  }

  /** Creates a new UnauthorizedException with the given message and cause. */
  public UnauthorizedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
