// DO NOT EDIT - auto-generated by alef
// alef:hash:b0da2f779427adb8164a650ae13f4bff7e5d612f1be06c12b5229fb65238455b
package dev.kreuzberg.kreuzcrawl;

/**
 * The requested capability is not supported by the active backend or build.
 */
public class UnsupportedException extends CrawlErrorException {
    /** Creates a new UnsupportedException with the given message. */
    public UnsupportedException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedException with the given message and cause. */
    public UnsupportedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
