// DO NOT EDIT - auto-generated by alef
// alef:hash:154754c093bcd85cfb15021f5ca17a01df2e86e2795ac06e3798493af38395c8
package dev.kreuzberg.kreuzcrawl;

/**
 * The requested capability is not supported by the active backend or build.
 */
public class UnsupportedException extends CrawlErrorException {
    /** Creates a new UnsupportedException with the given message. */
    public UnsupportedException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedException with the given message and cause. */
    public UnsupportedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
