// DO NOT EDIT - auto-generated by alef
// alef:hash:c7ccb8950f448d5ad65e78649c618fb261c896faa19f3af6273aa19a09c8d4b9
package dev.kreuzberg.kreuzcrawl;

/**
 * The requested capability is not supported by the active backend or build.
 */
public class UnsupportedException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new UnsupportedException with the given message. */
  public UnsupportedException(final String message) {
    super(message);
  }

  /** Creates a new UnsupportedException with the given message and cause. */
  public UnsupportedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
