// DO NOT EDIT - auto-generated by alef
// alef:hash:7d3cbe1e164d61eb4ae34c8061622a51b2a735b15b42f234419582009d82043e
package dev.kreuzberg.kreuzcrawl;

/**
 * The request was blocked by a WAF or bot protection (HTTP 403 with WAF indicators).
 *
 * `vendor` is the lowercase identifier of the detected WAF (e.g. "cloudflare",
 * "datadome"). When the engine cannot identify the vendor, it uses "unknown".
 * `message` is the freeform description for logs and human readers.
 *
 * The stable error tag remains `forbidden: waf/blocked: MESSAGE` so existing
 * log-grep patterns and cross-language bindings continue to work; vendor is
 * surfaced separately for structured consumers.
 */
public class WafBlockedException extends CrawlErrorException {
    /** Creates a new WafBlockedException with the given message. */
    public WafBlockedException(final String message) {
        super(message);
    }

    /** Creates a new WafBlockedException with the given message and cause. */
    public WafBlockedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
