// DO NOT EDIT - auto-generated by alef
// alef:hash:d66b53311e3444afea49b618b7c3690d6724771ffd2c3d86adcbccf047dd5caf
package dev.kreuzberg.kreuzcrawl;

/**
 * The request was blocked by a WAF or bot protection (HTTP 403 with WAF indicators).
 */
public class WafBlockedException extends CrawlErrorException {
    /** Creates a new WafBlockedException with the given message. */
    public WafBlockedException(final String message) {
        super(message);
    }

    /** Creates a new WafBlockedException with the given message and cause. */
    public WafBlockedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
