// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:acd9a7ba70073f0e8072ce3d10eb8b5e7ded2157e12c6562bb27ab1ff8de738c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
    globalSetup: "./globalSetup.ts",
  },
});
