// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8896b7e192e408f916c81acf04c97fc5ee10b269fe22c287e9eefab02fada615
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
		setupFiles: ["./setup.ts"],
	},
});
