// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bb258bc753e9e54115c24cf975e944a80dd08d5bf22b6da1db4f4ff2c9c1fe45
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import dev.kreuzberg.kreuzcrawl.Kreuzcrawl
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import dev.kreuzberg.kreuzcrawl.CrawlConfig

/** E2e tests for category: cookies. */
class CookiesTest {

    companion object {
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testCookiesPerDomain() {
        // Isolates cookies per domain during crawl
        val engineConfig = MAPPER.readValue("{\"cookies_enabled\":true,\"max_depth\":1,\"respect_robots_txt\":false}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/cookies_per_domain"
        val result = Kreuzcrawl.scrape(engine, url)
        // skipped: field 'cookies.length' not available on result type
        // skipped: field 'cookies' not available on result type
    }

    @Test
    fun testCookiesPersistence() {
        // Maintains cookies across multiple crawl requests
        val engineConfig = MAPPER.readValue("{\"cookies_enabled\":true,\"max_depth\":1,\"respect_robots_txt\":false}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/cookies_persistence"
        val result = Kreuzcrawl.scrape(engine, url)
        // skipped: field 'cookies' not available on result type
    }

    @Test
    fun testCookiesSetCookieResponse() {
        // Respects Set-Cookie header from server responses
        val engineConfig = MAPPER.readValue("{\"cookies_enabled\":true,\"max_depth\":1,\"respect_robots_txt\":false}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/cookies_set_cookie_response"
        val result = Kreuzcrawl.scrape(engine, url)
        // skipped: field 'cookies' not available on result type
    }

}
