// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:31c891ef4dcbe3563f50bde484ef446431505a842e64fb280cd4ff5cc1a3bec1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import dev.kreuzberg.kreuzcrawl.Kreuzcrawl

/** E2e tests for category: encoding. */
class EncodingTest {
    @Test
    fun testEncodingDoubleEncoded() {
        // Handles double-encoded URL characters (%25C3%25B6)
        val engine = Kreuzcrawl.createEngine(null)
        val url = System.getenv("MOCK_SERVER_URL") + "/fixtures/encoding_double_encoded"
        val result = Kreuzcrawl.scrape(engine, url)
        assertFalse(result.html().isEmpty(), "expected non-empty value")
        assertTrue(result.links().size >= 1, "expected >= {kotlin_val}")
    }

    @Test
    fun testEncodingMixedCharsetPage() {
        // Handles charset mismatch between HTTP header and HTML meta tag
        val engine = Kreuzcrawl.createEngine(null)
        val url = System.getenv("MOCK_SERVER_URL") + "/fixtures/encoding_mixed_charset_page"
        val result = Kreuzcrawl.scrape(engine, url)
        assertFalse(result.html().isEmpty(), "expected non-empty value")
    }

    @Test
    fun testEncodingPercentEncodedPath() {
        // Handles percent-encoded spaces and characters in URL paths
        val engine = Kreuzcrawl.createEngine(null)
        val url = System.getenv("MOCK_SERVER_URL") + "/fixtures/encoding_percent_encoded_path"
        val result = Kreuzcrawl.scrape(engine, url)
        assertFalse(result.html().isEmpty(), "expected non-empty value")
        assertTrue(result.links().size >= 2, "expected >= {kotlin_val}")
    }

    @Test
    fun testEncodingUnicodeUrl() {
        // Handles Unicode characters in URLs (Hebrew, Japanese, Cyrillic)
        val engine = Kreuzcrawl.createEngine(null)
        val url = System.getenv("MOCK_SERVER_URL") + "/fixtures/encoding_unicode_url"
        val result = Kreuzcrawl.scrape(engine, url)
        assertFalse(result.html().isEmpty(), "expected non-empty value")
    }

}
