// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6172269032b4b7dcee5792dee9fd0f3bcc01e3f07cfd423805ef8792f9ad59bf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import dev.kreuzberg.kreuzcrawl.Kreuzcrawl
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import dev.kreuzberg.kreuzcrawl.CrawlConfig

/** E2e tests for category: redirect. */
class RedirectTest {

    companion object {
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testRedirect301Permanent() {
        // Follows 301 permanent redirect and returns final page content
        val engineConfig = MAPPER.readValue("{\"respect_robots_txt\":false}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = System.getenv("MOCK_SERVER_URL") + "/fixtures/redirect_301_permanent"
        val result = Kreuzcrawl.scrape(engine, url)
        // skipped: field 'final_url' not available on result type
        // skipped: field 'redirect_count' not available on result type
    }

    @Test
    fun testRedirect302Found() {
        // Follows 302 Found redirect correctly
        val engineConfig = MAPPER.readValue("{\"respect_robots_txt\":false}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = System.getenv("MOCK_SERVER_URL") + "/fixtures/redirect_302_found"
        val result = Kreuzcrawl.scrape(engine, url)
        // skipped: field 'final_url' not available on result type
        // skipped: field 'redirect_count' not available on result type
    }

    @Test
    fun testRedirect303SeeOther() {
        // Follows 303 See Other redirect (method changes to GET)
        val engineConfig = MAPPER.readValue("{\"respect_robots_txt\":false}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = System.getenv("MOCK_SERVER_URL") + "/fixtures/redirect_303_see_other"
        val result = Kreuzcrawl.scrape(engine, url)
        // skipped: field 'final_url' not available on result type
        // skipped: field 'redirect_count' not available on result type
    }

    @Test
    fun testRedirect307Temporary() {
        // Follows 307 Temporary Redirect (preserves method)
        val engineConfig = MAPPER.readValue("{\"respect_robots_txt\":false}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = System.getenv("MOCK_SERVER_URL") + "/fixtures/redirect_307_temporary"
        val result = Kreuzcrawl.scrape(engine, url)
        // skipped: field 'final_url' not available on result type
        // skipped: field 'redirect_count' not available on result type
    }

    @Test
    fun testRedirect308Permanent() {
        // Follows 308 Permanent Redirect (preserves method)
        val engineConfig = MAPPER.readValue("{\"respect_robots_txt\":false}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = System.getenv("MOCK_SERVER_URL") + "/fixtures/redirect_308_permanent"
        val result = Kreuzcrawl.scrape(engine, url)
        // skipped: field 'final_url' not available on result type
        // skipped: field 'redirect_count' not available on result type
    }

    @Test
    fun testRedirectChain() {
        // Follows a chain of redirects (301 -> 302 -> 200)
        val engineConfig = MAPPER.readValue("{\"respect_robots_txt\":false}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = System.getenv("MOCK_SERVER_URL") + "/fixtures/redirect_chain"
        val result = Kreuzcrawl.scrape(engine, url)
        // skipped: field 'final_url' not available on result type
        // skipped: field 'redirect_count' not available on result type
    }

    @Test
    fun testRedirectCrossDomain() {
        // Reports cross-domain redirect target without following to external domain
        val engineConfig = MAPPER.readValue("{\"respect_robots_txt\":false}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = System.getenv("MOCK_SERVER_URL") + "/fixtures/redirect_cross_domain"
        val result = Kreuzcrawl.scrape(engine, url)
        // skipped: field 'final_url' not available on result type
        // skipped: field 'redirect_count' not available on result type
    }

    @Test
    fun testRedirectLoop() {
        // Detects redirect loop (A -> B -> A) and returns error
        val engineConfig = MAPPER.readValue("{\"respect_robots_txt\":false}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = System.getenv("MOCK_SERVER_URL") + "/fixtures/redirect_loop"
        val result = Kreuzcrawl.scrape(engine, url)
        // skipped: field 'is_error' not available on result type
    }

    @Test
    fun testRedirectMaxExceeded() {
        // Aborts when redirect count exceeds max_redirects limit
        val engineConfig = MAPPER.readValue("{\"max_redirects\":2,\"respect_robots_txt\":false}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = System.getenv("MOCK_SERVER_URL") + "/fixtures/redirect_max_exceeded"
        val result = Kreuzcrawl.scrape(engine, url)
        // skipped: field 'is_error' not available on result type
    }

    @Test
    fun testRedirectMetaRefresh() {
        // Follows HTML meta-refresh redirect to target page
        val engineConfig = MAPPER.readValue("{\"respect_robots_txt\":false}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = System.getenv("MOCK_SERVER_URL") + "/fixtures/redirect_meta_refresh"
        val result = Kreuzcrawl.scrape(engine, url)
        // skipped: field 'final_url' not available on result type
        // skipped: field 'redirect_count' not available on result type
    }

    @Test
    fun testRedirectRefreshHeader() {
        // Handles HTTP Refresh header redirect
        val engineConfig = MAPPER.readValue("{\"respect_robots_txt\":false}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = System.getenv("MOCK_SERVER_URL") + "/fixtures/redirect_refresh_header"
        val result = Kreuzcrawl.scrape(engine, url)
        // skipped: field 'final_url' not available on result type
        // skipped: field 'redirect_count' not available on result type
    }

    @Test
    fun testRedirectTo404() {
        // Redirect target returns 404 Not Found
        val engineConfig = MAPPER.readValue("{\"respect_robots_txt\":false}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = System.getenv("MOCK_SERVER_URL") + "/fixtures/redirect_to_404"
        val result = Kreuzcrawl.scrape(engine, url)
        // skipped: field 'final_url' not available on result type
        // skipped: field 'redirect_count' not available on result type
        // skipped: field 'is_error' not available on result type
    }

}
