// Generated by alef. Do not edit by hand.
// alef:hash:277d85397998235b21fcea3a167fbdf11c7196bb8ab9a24070c0403ce7910336

package io.xberg.crawlberg.android

class CrawlbergBridgeException(message: String?, cause: Throwable?) : RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
