// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:755569af2b42861f32165142a5cdf9e9f29615d380c94212ac00ea218a5db003
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The browser page load or rendering timed out.
/// </summary>
public class BrowserTimeoutException : CrawlErrorException
{
    public BrowserTimeoutException(string message) : base(message) { }

    public BrowserTimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
