// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b60db53f8e86834a869c3860eb7122e465ce62affbd0852b1dd5f5fa00c4b5f2
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Crawlberg;
/// <summary>
/// Browser backend used for JavaScript rendering.
/// </summary>
[JsonConverter(typeof(BrowserBackendJsonConverter))]
public enum BrowserBackend
{
    /// <summary>
    /// Existing Chromium/CDP backend powered by chromiumoxide.
    /// </summary>
    [JsonPropertyName("chromiumoxide")]
    Chromiumoxide,
    /// <summary>
    /// Crawlberg-owned native browser backend derived from Obscura.
    /// </summary>
    [JsonPropertyName("native")]
    Native,
}


/// <summary>
/// Custom JSON converter for <see cref="BrowserBackend"/> that respects explicit variant names.
/// </summary>
internal sealed class BrowserBackendJsonConverter : JsonConverter<BrowserBackend>
{
    public override BrowserBackend Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "chromiumoxide" => BrowserBackend.Chromiumoxide,
            "native" => BrowserBackend.Native,
            _ => throw new JsonException($"Unknown BrowserBackend value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, BrowserBackend value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            BrowserBackend.Chromiumoxide => "chromiumoxide",
            BrowserBackend.Native => "native",
            _ => throw new JsonException($"Unknown BrowserBackend value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
