// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:11ba98ea104a2a0b34dc436503c6e2cd4ca6f9e1337846ab2f7e4b9fccb505c9
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The browser page load or rendering timed out.
/// </summary>
public class BrowserTimeoutException : CrawlErrorException
{
    public BrowserTimeoutException(string message) : base(message) { }

    public BrowserTimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
