// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:952c737eea2172575fdb72ef8eef11fca0a2c69ce6ec700e348f70e5c4a6fd2d
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// A connection error occurred.
/// </summary>
public class ConnectionException : CrawlErrorException
{
    public ConnectionException(string message) : base(message) { }

    public ConnectionException(string message, Exception innerException) : base(message, innerException) { }
}
