// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:23d662f17ccee663375ea978facec5b4b691adf30860c73224d58efb602c12d2
#nullable enable

using System;

namespace Crawlberg;

public class CrawlbergException : Exception
{
    public int Code { get; }

    public CrawlbergException(int code, string message) : base(message)
    {
        Code = code;
    }

    public CrawlbergException(string message) : base(message)
    {
        Code = 0;
    }

    public CrawlbergException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
