// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:06831f8166c6d860691af36ee02b72ae3246568eb2e5c67ed5d11da71d02afeb
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// URL denied by SSRF policy: private IP, metadata IP, etc.
/// </summary>
public class DeniedByPolicyException : SsrfErrorException
{
    public DeniedByPolicyException(string message) : base(message) { }

    public DeniedByPolicyException(string message, Exception innerException) : base(message, innerException) { }
}
