// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a981b4c635037625f0e2a1806b53bedd24cd0627892d6d41614fcfec2528d021
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// A DNS resolution error occurred.
/// </summary>
public class DnsException : CrawlErrorException
{
    public DnsException(string message) : base(message) { }

    public DnsException(string message, Exception innerException) : base(message, innerException) { }
}
