// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b60db53f8e86834a869c3860eb7122e465ce62affbd0852b1dd5f5fa00c4b5f2
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The provided configuration is invalid.
/// </summary>
public class InvalidConfigException : CrawlErrorException
{
    public InvalidConfigException(string message) : base(message) { }

    public InvalidConfigException(string message, Exception innerException) : base(message, innerException) { }
}
