// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:23d662f17ccee663375ea978facec5b4b691adf30860c73224d58efb602c12d2
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The provided configuration is invalid.
/// </summary>
public class InvalidConfigException : CrawlErrorException
{
    public InvalidConfigException(string message) : base(message) { }

    public InvalidConfigException(string message, Exception innerException) : base(message, innerException) { }
}
