// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:952c737eea2172575fdb72ef8eef11fca0a2c69ce6ec700e348f70e5c4a6fd2d
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The requested page was not found (HTTP 404).
/// </summary>
public class NotFoundException : CrawlErrorException
{
    public NotFoundException(string message) : base(message) { }

    public NotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
