// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0eab3539dd01cb6d0df8fba44f697d2d6be190216721ace0203cec2be3c98844
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// Host not on allowlist when an allowlist is configured.
/// </summary>
public class NotOnAllowlistException : SsrfErrorException
{
    public NotOnAllowlistException(string message) : base(message) { }

    public NotOnAllowlistException(string message, Exception innerException) : base(message, innerException) { }
}
