// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c71da313df7b9a37bdd4f997f05150b92dfa5e723d3e2a4db0adafea6f951837
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// An unclassified error occurred.
/// </summary>
public class OtherException : CrawlErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
