// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:23d662f17ccee663375ea978facec5b4b691adf30860c73224d58efb602c12d2
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The request was rate-limited (HTTP 429).
/// </summary>
public class RateLimitedException : CrawlErrorException
{
    public RateLimitedException(string message) : base(message) { }

    public RateLimitedException(string message, Exception innerException) : base(message, innerException) { }
}
