// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0eab3539dd01cb6d0df8fba44f697d2d6be190216721ace0203cec2be3c98844
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// A server error occurred (HTTP 5xx).
/// </summary>
public class ServerErrorException : CrawlErrorException
{
    public ServerErrorException(string message) : base(message) { }

    public ServerErrorException(string message, Exception innerException) : base(message, innerException) { }
}
