// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:846f6cbccdf32f8dd0df2ec186f6c893e427b87c5266b53af98d2142b58e4763
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// A server error occurred (HTTP 5xx).
/// </summary>
public class ServerErrorException : CrawlErrorException
{
    public ServerErrorException(string message) : base(message) { }

    public ServerErrorException(string message, Exception innerException) : base(message, innerException) { }
}
