// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:277d85397998235b21fcea3a167fbdf11c7196bb8ab9a24070c0403ce7910336
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The request was unauthorized (HTTP 401).
/// </summary>
public class UnauthorizedException : CrawlErrorException
{
    public UnauthorizedException(string message) : base(message) { }

    public UnauthorizedException(string message, Exception innerException) : base(message, innerException) { }
}
