// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:27185243ffb8b9dd7aa000047ac6570987e13460b13692990410af82a75d4159
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
	},
});
