// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:69c2f8e60a626cc1620af4ec7e4588ca48d8ce1f5f648f7d2826802afeea0950
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    globalSetup: "./globalSetup.ts",
  },
});
