# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:277d85397998235b21fcea3a167fbdf11c7196bb8ab9a24070c0403ce7910336
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.AuthConfig do
  @moduledoc "Authentication configuration."

  @typedoc "Authentication configuration."
  @type t :: term()

  @typedoc "HTTP Basic authentication."
  @type basic :: %{type: :basic, username: String.t(), password: String.t()}
  @typedoc "Bearer token authentication."
  @type bearer :: %{type: :bearer, token: String.t()}
  @typedoc "Custom authentication header."
  @type header :: %{type: :header, name: String.t(), value: String.t()}

  def basic(username, password), do: {:basic, %{username: username, password: password}}
  def bearer(token), do: {:bearer, %{token: token}}
  def header(name, value), do: {:header, %{name: name, value: value}}
end
