# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a981b4c635037625f0e2a1806b53bedd24cd0627892d6d41614fcfec2528d021
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.BatchCrawlStreamRequest do
  @moduledoc """
  Request to begin a multi-URL streaming crawl.

  Wraps a set of seed URLs for delivery through the streaming-adapter binding
  surface. Required as a struct because alef's streaming adapter requires a
  named request type — primitives are not supported.
  """

  @typedoc "Request to begin a multi-URL streaming crawl."
  @type t :: %__MODULE__{
          urls: [String.t()]
        }

  defstruct urls: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
