# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b60db53f8e86834a869c3860eb7122e465ce62affbd0852b1dd5f5fa00c4b5f2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.BrowserExtras do
  @moduledoc """
  Browser-specific extras populated when the native browser backend was used.

  Available on `ScrapeResult.browser` when `BrowserBackend::Native` handled the request.
  """

  @typedoc "Browser-specific extras populated when the native browser backend was used."
  @type t :: %__MODULE__{
          eval_result: String.t() | nil,
          network_events: [map()],
          cookies: [map()]
        }

  defstruct eval_result: nil,
            network_events: [],
            cookies: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
