# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b60db53f8e86834a869c3860eb7122e465ce62affbd0852b1dd5f5fa00c4b5f2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.BrowserBackend do
  @moduledoc "Browser backend used for JavaScript rendering."

  @typedoc "Browser backend used for JavaScript rendering."
  @type t :: :chromiumoxide | :native

  @chromiumoxide :chromiumoxide
  @native :native

  @doc "Existing Chromium/CDP backend powered by chromiumoxide."
  @spec chromiumoxide() :: t()
  def chromiumoxide, do: @chromiumoxide
  @doc "Crawlberg-owned native browser backend derived from Obscura."
  @spec native() :: t()
  def native, do: @native
end
