# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:11ba98ea104a2a0b34dc436503c6e2cd4ca6f9e1337846ab2f7e4b9fccb505c9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.CookieInfo do
  @moduledoc "Information about an HTTP cookie received from a response."

  @typedoc "Information about an HTTP cookie received from a response."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          value: String.t() | nil,
          domain: String.t() | nil,
          path: String.t() | nil
        }

  defstruct name: nil,
            value: nil,
            domain: nil,
            path: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
