# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:952c737eea2172575fdb72ef8eef11fca0a2c69ce6ec700e348f70e5c4a6fd2d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.CrawlEvent do
  @moduledoc """
  An event emitted during a streaming crawl operation.

  Not available on `wasm32` targets — streaming requires native concurrency
  primitives (tokio channels, `JoinSet`) that are not supported on wasm32.

  Delivered to bindings through each target's native streaming idiom.
  """

  @typedoc "An event emitted during a streaming crawl operation."
  @type t :: term()

  @typedoc "A single page has been crawled."
  @type page :: %{type: :page, result: Crawlberg.CrawlPageResult.t()}
  @typedoc "An error occurred while crawling a URL."
  @type error :: %{type: :error, url: String.t(), error: String.t()}
  @typedoc "The crawl has completed."
  @type complete :: %{type: :complete, pages_crawled: non_neg_integer()}

  def page(result), do: {:page, %{result: result}}
  def error(url, error), do: {:error, %{url: url, error: error}}
  def complete(pages_crawled), do: {:complete, %{pages_crawled: pages_crawled}}
end
