# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:11ba98ea104a2a0b34dc436503c6e2cd4ca6f9e1337846ab2f7e4b9fccb505c9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.FaviconInfo do
  @moduledoc "Information about a favicon or icon link."

  @typedoc "Information about a favicon or icon link."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          rel: String.t() | nil,
          sizes: String.t() | nil,
          mime_type: String.t() | nil
        }

  defstruct url: nil,
            rel: nil,
            sizes: nil,
            mime_type: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
