# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:277d85397998235b21fcea3a167fbdf11c7196bb8ab9a24070c0403ce7910336
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.FeedType do
  @moduledoc "The type of a feed (RSS, Atom, or JSON Feed)."

  @typedoc "The type of a feed (RSS, Atom, or JSON Feed)."
  @type t :: :rss | :atom | :json_feed

  @rss :rss
  @atom :atom
  @json_feed :json_feed

  @doc "RSS feed."
  @spec rss() :: t()
  def rss, do: @rss
  @doc "Atom feed."
  @spec atom() :: t()
  def atom, do: @atom
  @doc "JSON Feed."
  @spec json_feed() :: t()
  def json_feed, do: @json_feed
end
