# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:11ba98ea104a2a0b34dc436503c6e2cd4ca6f9e1337846ab2f7e4b9fccb505c9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.HreflangEntry do
  @moduledoc "An hreflang alternate link entry."

  @typedoc "An hreflang alternate link entry."
  @type t :: %__MODULE__{
          lang: String.t() | nil,
          url: String.t() | nil
        }

  defstruct lang: nil,
            url: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
