# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:06831f8166c6d860691af36ee02b72ae3246568eb2e5c67ed5d11da71d02afeb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.JsonLdEntry do
  @moduledoc "A JSON-LD structured data entry found on a page."

  @typedoc "A JSON-LD structured data entry found on a page."
  @type t :: %__MODULE__{
          schema_type: String.t() | nil,
          name: String.t() | nil,
          raw: String.t() | nil
        }

  defstruct schema_type: nil,
            name: nil,
            raw: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
