# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a981b4c635037625f0e2a1806b53bedd24cd0627892d6d41614fcfec2528d021
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.ScrollDirection do
  @moduledoc "Direction for a scroll action."

  @typedoc "Direction for a scroll action."
  @type t :: :up | :down

  @up :up
  @down :down

  @doc "Scroll upward."
  @spec up() :: t()
  def up, do: @up
  @doc "Scroll downward."
  @spec down() :: t()
  def down, do: @down
end
