# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:755569af2b42861f32165142a5cdf9e9f29615d380c94212ac00ea218a5db003
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.SsrfPolicy do
  @moduledoc "SSRF policy configuration."

  @typedoc "SSRF policy configuration."
  @type t :: %__MODULE__{
          deny_private: boolean(),
          max_redirects: non_neg_integer()
        }

  defstruct deny_private: true,
            max_redirects: 5

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
