// Code generated by kreuzcrawl-e2e-generator. DO NOT EDIT.

use wiremock::matchers::{method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

/// Start a new mock HTTP server.
pub async fn setup_mock_server() -> MockServer {
    MockServer::start().await
}

/// Load a response body file from fixtures/responses/.
pub fn load_response_body(relative_path: &str) -> String {
    let base = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("e2e/rust parent")
        .parent()
        .expect("e2e parent")
        .join("fixtures")
        .join("responses");
    let full_path = base.join(relative_path);
    std::fs::read_to_string(&full_path)
        .unwrap_or_else(|e| panic!("failed to load response body {}: {e}", full_path.display()))
}

/// Register a mock route on the given server.
pub async fn register_mock(
    server: &MockServer,
    http_method: &str,
    route: &str,
    status: u16,
    headers: &[(&str, &str)],
    body: &str,
) {
    // Use set_body_bytes to avoid wiremock's default text/plain content-type
    // that set_body_string adds (which can't be overridden by append_header).
    let mut response = ResponseTemplate::new(status).set_body_bytes(body.as_bytes());
    for &(key, value) in headers {
        response = response.append_header(key, value);
    }
    Mock::given(method(http_method))
        .and(path(route))
        .respond_with(response)
        .mount(server)
        .await;
}
