// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bcefa5a57e85c4822653a199f7fb362ca98cb5ae57083ddc69c6f2cf3edb13e2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzcrawl

/// E2e tests for category: proxy.
final class ProxyTests: XCTestCase {
    func testProxyAuthenticated() async throws {
        // Proxy with username and password credentials authenticates successfully
        let engineConfig = try crawlConfigFromJson("{\"proxy\":{\"password\":\"proxypass\",\"url\":\"http://127.0.0.1:8889\",\"username\":\"proxyuser\"},\"respect_robots_txt\":false}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/proxy_authenticated"
        let result = try await Kreuzcrawl.crawl(engine: engineObj, url: url)
        let _vec_pages_equals_29fea8bb = result.pages()
        XCTAssertEqual(_vec_pages_equals_29fea8bb[0].statusCode(), UInt(200))
        XCTAssertEqual(result.pages().count, UInt(1))
    }

    func testProxyBasicSuccess() async throws {
        // Configure proxy URL and successfully crawl through it
        let engineConfig = try crawlConfigFromJson("{\"proxy\":{\"url\":\"http://127.0.0.1:8888\"},\"respect_robots_txt\":false}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/proxy_basic_success"
        let result = try await Kreuzcrawl.crawl(engine: engineObj, url: url)
        let _vec_pages_equals_29fea8bb = result.pages()
        XCTAssertEqual(_vec_pages_equals_29fea8bb[0].statusCode(), UInt(200))
        XCTAssertEqual(result.pages().count, UInt(1))
    }

}
