// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:716144e36deb18548afef54d8e6f81f65bf0c7da0310077cb46c0f3946e46014
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import Foundation
import Kreuzcrawl
import RustBridge

/// E2e tests for category: warc.
final class WarcTests: XCTestCase {
    func testWarcBasicOutput() async throws {
        // Scrape single page with WARC output enabled writes to file
        let engineConfig = try crawlConfigFromJson("{\"respect_robots_txt\":false,\"warc_output\":\"/tmp/kreuzcrawl_test.warc\"}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/warc_basic_output"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        // skipped: field 'pages.length' not available on result type
    }

    func testWarcMultiPageCrawl() async throws {
        // Crawl multiple pages with depth=1 and WARC output enabled
        let engineConfig = try crawlConfigFromJson("{\"max_depth\":1,\"respect_robots_txt\":false,\"warc_output\":\"/tmp/kreuzcrawl_crawl.warc\"}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/warc_multi_page_crawl"
        let result = try await scrape(engineObj, url)
        // skipped: field 'pages.length' not available on result type
        // skipped: field 'stayed_on_domain' not available on result type
    }

}
