// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a00ec7eb1d5318b4b0d22e5c961bf559d5efff4ed87813979c5458495866c823
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

import { describe, expect, it } from "vitest";
import { scrape, interact, createEngine } from "@kreuzberg/kreuzcrawl";
function _alefE2eText(value: unknown): string {
  return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
  if (item == null || typeof item !== "object") {
    return [_alefE2eText(item)];
  }
  const record = item as Record<string, unknown>;
  const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
  return [
    _alefE2eText(item),
    _alefE2eText(record.kind),
    _alefE2eText(record.name),
    _alefE2eText(record.source),
    _alefE2eText(record.alias),
    _alefE2eText(record.text),
    _alefE2eText(record.signature),
    itemsText,
  ];
}

describe("interaction", () => {
  it("interact_action_sequence: Execute a sequence of multiple actions (click, type, click) and verify all succeed with correct indices", async () => {
    const engineConfig = { browser: { mode: "always" } };
    const engine = createEngine(engineConfig);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/interact_action_sequence`;
    await interact(engine, url, [
      { selector: "#open", type: "click" },
      { selector: "#field", text: "test_data", type: "type" },
      { selector: "#submit", type: "click" },
    ]); // skipped: field 'interaction.action_results[0].action_index' not available on result type
    // skipped: field 'interaction.action_results[0].action_type' not available on result type
    // skipped: field 'interaction.action_results[0].success' not available on result type
    // skipped: field 'interaction.action_results[1].action_index' not available on result type
    // skipped: field 'interaction.action_results[1].action_type' not available on result type
    // skipped: field 'interaction.action_results[1].success' not available on result type
    // skipped: field 'interaction.action_results[2].action_index' not available on result type
    // skipped: field 'interaction.action_results[2].action_type' not available on result type
    // skipped: field 'interaction.action_results[2].success' not available on result type
  });
  it("interact_click_element: Click a button element and verify success", async () => {
    const engineConfig = { browser: { mode: "always" } };
    const engine = createEngine(engineConfig);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/interact_click_element`;
    await interact(engine, url, [{ selector: "#submit", type: "click" }]); // skipped: field 'interaction.action_results[0].success' not available on result type
    // skipped: field 'interaction.action_results[0].action_type' not available on result type
    // skipped: field 'interaction.action_results[0].action_index' not available on result type
  });
  it("interact_execute_js: Execute JavaScript that returns document.title and verify success with data", async () => {
    const engineConfig = { browser: { mode: "always" } };
    const engine = createEngine(engineConfig);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/interact_execute_js`;
    await interact(engine, url, [{ script: "return document.title", type: "executeJs" }]); // skipped: field 'interaction.action_results[0].success' not available on result type
    // skipped: field 'interaction.action_results[0].action_type' not available on result type
    // skipped: field 'interaction.action_results[0].data' not available on result type
  });
  it("interact_invalid_selector: Click on a non-existent selector and verify error in action_results", async () => {
    const engineConfig = { browser: { mode: "always" } };
    const engine = createEngine(engineConfig);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/interact_invalid_selector`;
    await interact(engine, url, [{ selector: "#nonexistent", type: "click" }]); // skipped: field 'interaction.action_results[0].success' not available on result type
    // skipped: field 'interaction.action_results[0].action_type' not available on result type
    // skipped: field 'interaction.action_results[0].error' not available on result type
  });
  it("interact_max_actions_exceeded: Submit 101 actions (exceeds MAX_ACTIONS=100) and verify validation error", async () => {
    await expect(async () => {
      const engineConfig = { browser: { mode: "always" } };
      const engine = createEngine(engineConfig);
      const url = `${process.env.MOCK_SERVER_URL}/fixtures/interact_max_actions_exceeded`;
      await interact(engine, url, [
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
        { selector: "#btn", type: "click" },
      ]);
    }).rejects.toThrow();
  });
  it("interact_scroll_down: Scroll down on the page and verify success", async () => {
    const engineConfig = { browser: { mode: "always" } };
    const engine = createEngine(engineConfig);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/interact_scroll_down`;
    await interact(engine, url, [{ amount: 500, direction: "down", type: "scroll" }]); // skipped: field 'interaction.action_results[0].success' not available on result type
    // skipped: field 'interaction.action_results[0].action_type' not available on result type
    // skipped: field 'interaction.action_results[0].action_index' not available on result type
  });
  it("interact_type_input: Type text into an input field and verify success", async () => {
    const engineConfig = { browser: { mode: "always" } };
    const engine = createEngine(engineConfig);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/interact_type_input`;
    await interact(engine, url, [{ selector: "#username", text: "john_doe", type: "type" }]); // skipped: field 'interaction.action_results[0].success' not available on result type
    // skipped: field 'interaction.action_results[0].action_type' not available on result type
    // skipped: field 'interaction.action_results[0].action_index' not available on result type
  });
  it("interact_wait_selector: Wait for a CSS selector that exists on the page", async () => {
    const engineConfig = { browser: { mode: "always" } };
    const engine = createEngine(engineConfig);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/interact_wait_selector`;
    await interact(engine, url, [{ selector: "#content", type: "wait" }]); // skipped: field 'interaction.action_results[0].success' not available on result type
    // skipped: field 'interaction.action_results[0].action_type' not available on result type
    // skipped: field 'interaction.action_results[0].action_index' not available on result type
  });
});
