// DO NOT EDIT - auto-generated by alef
// alef:hash:c71da313df7b9a37bdd4f997f05150b92dfa5e723d3e2a4db0adafea6f951837
package dev.kreuzberg.crawlberg;

/**
 * URL scheme not in allowlist (e.g., `ftp://` when only `http`/`https` allowed).
 */
public class DisallowedSchemeException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DisallowedSchemeException with the given message. */
  public DisallowedSchemeException(final String message) {
    super(message);
  }

  /** Creates a new DisallowedSchemeException with the given message and cause. */
  public DisallowedSchemeException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
