// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:846f6cbccdf32f8dd0df2ec186f6c893e427b87c5266b53af98d2142b58e4763
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.crawlberg;

/** Exception thrown when input validation fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class InvalidInputException extends CrawlbergRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidInputException. */
  public InvalidInputException(final String message) {
    super(1, message);
  }

  /** Creates a new InvalidInputException with a cause. */
  public InvalidInputException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
