// DO NOT EDIT - auto-generated by alef
// alef:hash:846f6cbccdf32f8dd0df2ec186f6c893e427b87c5266b53af98d2142b58e4763
package dev.kreuzberg.crawlberg;

/**
 * An unclassified error occurred.
 */
public class OtherException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new OtherException with the given message. */
  public OtherException(final String message) {
    super(message);
  }

  /** Creates a new OtherException with the given message and cause. */
  public OtherException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
