// DO NOT EDIT - auto-generated by alef
// alef:hash:c71da313df7b9a37bdd4f997f05150b92dfa5e723d3e2a4db0adafea6f951837
package dev.kreuzberg.crawlberg;

/**
 * The request timed out.
 */
public class TimeoutException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new TimeoutException with the given message. */
  public TimeoutException(final String message) {
    super(message);
  }

  /** Creates a new TimeoutException with the given message and cause. */
  public TimeoutException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
