<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fbf2830a355e5de1b4e1423a91d8f5e6eb534e881c9ca8b8408011e2e2dd61c3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Kreuzcrawl;

/**
 * Opaque handle to a configured crawl engine.
 *
 * Constructed via `create_engine` with an optional `CrawlConfig`.
 * Default implementations for all pluggable components are used internally.
 */
final class CrawlEngineHandle
{
    public function crawlStream(CrawlStreamRequest $req): \Generator
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }

    public function batchCrawlStream(BatchCrawlStreamRequest $req): \Generator
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }

}
