<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7d3cbe1e164d61eb4ae34c8061622a51b2a735b15b42f234419582009d82043e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Kreuzcrawl;

/**
 * Opaque handle to a configured crawl engine.
 *
 * Constructed via `create_engine` with an optional `CrawlConfig`.
 * Default implementations for all pluggable components are used internally.
 */
final class CrawlEngineHandle
{
    public function crawlStream(CrawlStreamRequest $req): \Generator
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }

    public function batchCrawlStream(BatchCrawlStreamRequest $req): \Generator
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }

}
