<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:06831f8166c6d860691af36ee02b72ae3246568eb2e5c67ed5d11da71d02afeb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Crawlberg;

/**
 * Opaque handle to a configured crawl engine.
 *
 * Constructed via `create_engine` with an optional `CrawlConfig`.
 * Default implementations for all pluggable components are used internally.
 */
final class CrawlEngineHandle
{
    public function crawlStream(CrawlStreamRequest $req): \Generator
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }

    public function batchCrawlStream(BatchCrawlStreamRequest $req): \Generator
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }

}
