// Generated by alef — intentionally empty.
// alef:hash:23d662f17ccee663375ea978facec5b4b691adf30860c73224d58efb602c12d2
// Streaming-adapter owner handles are declared canonically (once) in the
// Rust extern blocks, so swift-bridge synthesizes their class triple and
// `$_free` destructor directly; no hand-rolled class hierarchy is needed.

import Foundation
import RustBridgeC
