// Generated by alef — opaque handle class triples for types marked
// alef:hash:844df915154f680a35d6cba0bf29ade937e5ffa63c54639d604b2c0c18bd6a79
// #[swift_bridge(already_declared)] in the Rust extern blocks.
// These classes are referenced by swift-bridge-generated code but are not
// auto-generated when the type is marked already_declared.

import Foundation

public class CrawlEngineHandle: CrawlEngineHandleRefMut {
  public var isOwned: Bool = true

  public override init(ptr: UnsafeMutableRawPointer) {
    super.init(ptr: ptr)
  }

  deinit {
    if isOwned {
      __swift_bridge__$CrawlEngineHandle$_free(ptr)
    }
  }
}

public class CrawlEngineHandleRefMut: CrawlEngineHandleRef {
  public override init(ptr: UnsafeMutableRawPointer) {
    super.init(ptr: ptr)
  }
}

public class CrawlEngineHandleRef {
  public var ptr: UnsafeMutableRawPointer
  public init(ptr: UnsafeMutableRawPointer) { self.ptr = ptr }
}
