// Generated by alef — opaque handle class triples for types marked
// alef:hash:b1eaf8351c96d22db4968d7fe538e959ae14c161de2fcc6bf4533a0f6fd6d8b1
// #[swift_bridge(already_declared)] in the Rust extern blocks.
// These classes are referenced by swift-bridge-generated code but are not
// auto-generated when the type is marked already_declared.

import Foundation
import RustBridgeC

public class CrawlEngineHandle: CrawlEngineHandleRefMut {
    public var isOwned: Bool = true

    public override init(ptr: UnsafeMutableRawPointer) {
        super.init(ptr: ptr)
    }

    deinit {
        if isOwned {
            __swift_bridge__$CrawlEngineHandle$_free(ptr)
        }
    }
}

public class CrawlEngineHandleRefMut: CrawlEngineHandleRef {
    public override init(ptr: UnsafeMutableRawPointer) {
        super.init(ptr: ptr)
    }
}

public class CrawlEngineHandleRef {
    public var ptr: UnsafeMutableRawPointer
    public init(ptr: UnsafeMutableRawPointer) { self.ptr = ptr }
}
