# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:96c3f5289e0196cb8741ca6faaec7184cd31e2ef748f04d035624037c5edd91c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

"""E2e tests for category: interaction."""

import os
import pytest  # noqa: F401
from kreuzcrawl import interact, create_engine, CrawlConfig, BrowserConfig


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = (
        " ".join(str(value) for value in raw_items)
        if isinstance(raw_items, list)
        else ""
    )
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


@pytest.mark.asyncio
async def test_interact_action_sequence() -> None:
    """Execute a sequence of multiple actions (click, type, click) and verify all succeed with correct indices."""
    engine_config = CrawlConfig(browser=BrowserConfig(mode="always"))
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/interact_action_sequence"
    actions = [
        PageAction(selector="#open", type="click"),
        PageAction(selector="#field", text="test_data", type="type"),
        PageAction(selector="#submit", type="click"),
    ]

    _ = await interact(engine, url, actions)
    # skipped: field 'interaction.action_results[0].action_index' not available on result type
    # skipped: field 'interaction.action_results[0].action_type' not available on result type
    # skipped: field 'interaction.action_results[0].success' not available on result type
    # skipped: field 'interaction.action_results[1].action_index' not available on result type
    # skipped: field 'interaction.action_results[1].action_type' not available on result type
    # skipped: field 'interaction.action_results[1].success' not available on result type
    # skipped: field 'interaction.action_results[2].action_index' not available on result type
    # skipped: field 'interaction.action_results[2].action_type' not available on result type
    # skipped: field 'interaction.action_results[2].success' not available on result type


@pytest.mark.asyncio
async def test_interact_click_element() -> None:
    """Click a button element and verify success."""
    engine_config = CrawlConfig(browser=BrowserConfig(mode="always"))
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/interact_click_element"
    actions = [PageAction(selector="#submit", type="click")]

    _ = await interact(engine, url, actions)
    # skipped: field 'interaction.action_results[0].success' not available on result type
    # skipped: field 'interaction.action_results[0].action_type' not available on result type
    # skipped: field 'interaction.action_results[0].action_index' not available on result type


@pytest.mark.asyncio
async def test_interact_execute_js() -> None:
    """Execute JavaScript that returns document.title and verify success with data."""
    engine_config = CrawlConfig(browser=BrowserConfig(mode="always"))
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/interact_execute_js"
    actions = [PageAction(script="return document.title", type="executeJs")]

    _ = await interact(engine, url, actions)
    # skipped: field 'interaction.action_results[0].success' not available on result type
    # skipped: field 'interaction.action_results[0].action_type' not available on result type
    # skipped: field 'interaction.action_results[0].data' not available on result type


@pytest.mark.asyncio
async def test_interact_invalid_selector() -> None:
    """Click on a non-existent selector and verify error in action_results."""
    engine_config = CrawlConfig(browser=BrowserConfig(mode="always"))
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/interact_invalid_selector"
    actions = [PageAction(selector="#nonexistent", type="click")]

    _ = await interact(engine, url, actions)
    # skipped: field 'interaction.action_results[0].success' not available on result type
    # skipped: field 'interaction.action_results[0].action_type' not available on result type
    # skipped: field 'interaction.action_results[0].error' not available on result type


@pytest.mark.asyncio
async def test_interact_max_actions_exceeded() -> None:
    """Submit 101 actions (exceeds MAX_ACTIONS=100) and verify validation error."""
    with pytest.raises(Exception) as exc_info:  # noqa: B017
        engine_config = CrawlConfig(browser=BrowserConfig(mode="always"))
        engine = create_engine(engine_config)
        url = os.environ["MOCK_SERVER_URL"] + "/fixtures/interact_max_actions_exceeded"
        actions = [
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
            PageAction(selector="#btn", type="click"),
        ]
        await interact(engine, url, actions)
    assert (
        "actions" in str(exc_info.value) or "actions" in type(exc_info.value).__name__
    )  # noqa: S101


@pytest.mark.asyncio
async def test_interact_scroll_down() -> None:
    """Scroll down on the page and verify success."""
    engine_config = CrawlConfig(browser=BrowserConfig(mode="always"))
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/interact_scroll_down"
    actions = [PageAction(amount=500, direction="down", type="scroll")]

    _ = await interact(engine, url, actions)
    # skipped: field 'interaction.action_results[0].success' not available on result type
    # skipped: field 'interaction.action_results[0].action_type' not available on result type
    # skipped: field 'interaction.action_results[0].action_index' not available on result type


@pytest.mark.asyncio
async def test_interact_type_input() -> None:
    """Type text into an input field and verify success."""
    engine_config = CrawlConfig(browser=BrowserConfig(mode="always"))
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/interact_type_input"
    actions = [PageAction(selector="#username", text="john_doe", type="type")]

    _ = await interact(engine, url, actions)
    # skipped: field 'interaction.action_results[0].success' not available on result type
    # skipped: field 'interaction.action_results[0].action_type' not available on result type
    # skipped: field 'interaction.action_results[0].action_index' not available on result type


@pytest.mark.asyncio
async def test_interact_wait_selector() -> None:
    """Wait for a CSS selector that exists on the page."""
    engine_config = CrawlConfig(browser=BrowserConfig(mode="always"))
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/interact_wait_selector"
    actions = [PageAction(selector="#content", type="wait")]

    _ = await interact(engine, url, actions)
    # skipped: field 'interaction.action_results[0].success' not available on result type
    # skipped: field 'interaction.action_results[0].action_type' not available on result type
    # skipped: field 'interaction.action_results[0].action_index' not available on result type
