// Generated by alef. Do not edit by hand.
// alef:hash:a981b4c635037625f0e2a1806b53bedd24cd0627892d6d41614fcfec2528d021

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "crawlberg-e2e"
