# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:11ba98ea104a2a0b34dc436503c6e2cd4ca6f9e1337846ab2f7e4b9fccb505c9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require_relative "crawlberg/version"
require_relative "crawlberg/native"

# Top-level namespace for the Crawlberg Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "crawlberg/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module Crawlberg
  # Re-export all types and functions from native extension
end
