# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0ca68837f600b021a368d04031b3f179c23e61b420b44a4e62afb4090be69525
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require_relative "kreuzcrawl/version"
require_relative "kreuzcrawl/native"

module Kreuzcrawl
  # Re-export all types and functions from native extension
end
