# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8fc3cef2ad0ada08bee1c82c39a437179e273f52f7ca6f2e98164d17d9ec34a4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require_relative "kreuzcrawl/version"
require_relative "kreuzcrawl/native"

# Top-level namespace for the Kreuzcrawl Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "kreuzcrawl/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module Kreuzcrawl
  # Re-export all types and functions from native extension
end
