# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c7ccb8950f448d5ad65e78649c618fb261c896faa19f3af6273aa19a09c8d4b9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require_relative "kreuzcrawl/version"
require_relative "kreuzcrawl/native"

# Top-level namespace for the Kreuzcrawl Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "kreuzcrawl/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module Kreuzcrawl
  # Re-export all types and functions from native extension
end
