// Generated by alef. Do not edit by hand.

import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id("com.android.library") version "8.7.3"
    kotlin("android") version "2.3.21"
    id("maven-publish")
    id("org.jlleitschuh.gradle.ktlint") version "13.1.0"
    id("com.github.ben-manes.versions") version "0.52.0"
}

android {
    namespace = "dev.kreuzberg.kreuzcrawl.android"
    compileSdk = 35

    defaultConfig {
        minSdk = 21
        consumerProguardFiles("consumer-rules.pro")
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    sourceSets {
        getByName("main") {
            jniLibs.srcDirs("src/main/jniLibs")
        }
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

// alef v0.16.8 still emits Panama-FFM Java glue (CrawlEngineHandle.java,
// KreuzcrawlRs.java, NativeLib.java) into the kotlin-android package
// alongside the DTOs. Panama is unavailable on Android (max JDK 17, no
// java.lang.foreign), so these files cannot compile. The runtime path is
// JNI via KreuzcrawlBridge.kt; these are dead weight. Exclude until alef
// stops emitting them.
tasks.withType<JavaCompile>().configureEach {
    exclude("dev/kreuzberg/kreuzcrawl/CrawlEngineHandle.java")
    exclude("dev/kreuzberg/kreuzcrawl/KreuzcrawlRs.java")
    exclude("dev/kreuzberg/kreuzcrawl/NativeLib.java")
}

ktlint {
    version.set("1.8.0")
    android.set(true)
    ignoreFailures.set(false)
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib")
    // Generated Kotlin facade uses suspend functions and Flow wrappers, both of
    // which require kotlinx-coroutines-android (transitively pulls -core).
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.11.0")
    // alef-generated Java DTOs use Jackson + JSpecify annotations — match
    // canonical Java package (packages/java/pom.xml).
    implementation("com.fasterxml.jackson.core:jackson-databind:2.21.3")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.21.3")
    implementation("org.jspecify:jspecify:1.0.0")
    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.3.0")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.7.0")
}

publishing {
    publications {
        register<MavenPublication>("release") {
            afterEvaluate {
                from(components["release"])
            }
            groupId = "dev.kreuzberg.kreuzcrawl.android"
            artifactId = "kreuzcrawl-android"
            version = "0.0.0"
        }
    }
}
