# Generated by alef. Do not edit by hand.
# alef:hash:b1eaf8351c96d22db4968d7fe538e959ae14c161de2fcc6bf4533a0f6fd6d8b1
# Keep generated public API for consumers using R8/ProGuard.
-keep class dev.kreuzberg.kreuzcrawl.android.** { *; }
