// Generated by alef. Do not edit by hand.
// alef:hash:0eab3539dd01cb6d0df8fba44f697d2d6be190216721ace0203cec2be3c98844

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "crawlberg-android"
