// Generated by alef. Do not edit by hand.
// alef:hash:0fdfaed140238d53bc6b110bcf837bd32eea306a3658f5b7a081c6c1f37ce701

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "kreuzcrawl-android"
