// Generated by alef. Do not edit by hand.
// alef:hash:882a6f513499cb08d9cbeb641424fe238f26f3653e161241824c4ea057a44c4f

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "kreuzcrawl-android"
