// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0fdfaed140238d53bc6b110bcf837bd32eea306a3658f5b7a081c6c1f37ce701
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
		setupFiles: ["./setup.ts"],
	},
});
