// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8e558b1b4645ea28c955ba5fcdc08590b671514607d103018f389ed2cec1d8b3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
		setupFiles: ["./setup.ts"],
	},
});
