// Generated by alef. Do not edit by hand.
// alef:hash:b73a33597114ff0394846e1119efb35c113eb8082ca4c51a09403e3659794bb4

// Traits module (empty in Dart as Dart does not have trait systems like Rust).
// This file is kept for API surface consistency across language bindings.
