// Generated by alef. Do not edit by hand.
// alef:hash:74de99d78969665be7fe561ee6d23a4e7e7ea97f70348c560fde67fa2e8a6017

// Traits module (empty in Dart as Dart does not have trait systems like Rust).
// This file is kept for API surface consistency across language bindings.
