// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:75c3fcb86e669810d7bb91c5d83dcc2abd2ac77509326e1db8d835e6d858cf09
fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::generate(crate_dir)
        .expect("Unable to generate C bindings")
        .write_to_file("include/kreuzcrawl.h");

    let go_include_dir = std::path::Path::new("../../packages/go/include");
    std::fs::create_dir_all(go_include_dir).expect("Unable to create Go include directory");
    std::fs::copy("include/kreuzcrawl.h", go_include_dir.join("kreuzcrawl.h"))
        .expect("Unable to copy header to Go include directory");
}
