# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:23d662f17ccee663375ea978facec5b4b691adf30860c73224d58efb602c12d2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Smoke test: import the published package."""

import importlib


def test_imports_published_package():
    module = importlib.import_module("crawlberg")
    assert module is not None
