# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:201177ab1fb2fdec3556e24178fc176a8245e0c8a6a32a882f4cc3ded3e5ac8b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Smoke test: import the published package."""

import importlib


def test_imports_published_package():
    module = importlib.import_module("kreuzcrawl")
    assert module is not None
