# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:277d85397998235b21fcea3a167fbdf11c7196bb8ab9a24070c0403ce7910336
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Smoke test: import the published package."""

import importlib


def test_imports_published_package():
    module = importlib.import_module("crawlberg")
    assert module is not None
