# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c1461d1c275b9c83f8874694e07e7726b65c6fbcea356741dabb2e9c9ab09991
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module Kreuzcrawl
  ## The version string for this package.
  VERSION = "0.3.0.pre.rc.62"
end
