# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:aa7504a8f66d06e6d06ebc173a17ed5956f42308b0c1c28a391e350e9ff7c302
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module Kreuzcrawl
  ## The version string for this package.
  VERSION = "0.3.0.pre.rc.69"
end
