# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c9b0d2a3dfb56b9e78a20f2176a3a0d25f8268f22862f6596fca4b7dc0041e17
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
# frozen_string_literal: true

module Kreuzcrawl
  VERSION = "0.3.0.pre.rc.37"
end
