/*
 * This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f3f42d5383d7ee705546392ac1d3926fc4cad2cf911bac2bc5fceae95b4b07d7
 * To regenerate: alef generate
 * To verify freshness: alef verify --exit-code
 * Issues & docs: https://github.com/kreuzberg-dev/alef
 */
/* E2e tests for category: map */

#include <assert.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "kreuzcrawl.h"
#include "test_runner.h"

void test_map_discover_urls(void) {
    /* Discovers all URLs on a site without fetching full content */
    KCRAWLScrape* result = scrape("{\"max_depth\":0,\"respect_robots_txt\":false}", NULL);
    assert(result != NULL && "expected call to succeed");
    KCRAWLUrls* urls_handle = kcrawl_scrape_urls(result);
    assert(urls_handle != NULL);
    char* urls_length = kcrawl_urls_length(urls_handle);
    // skipped: field 'urls.length' not available on result type
    kcrawl_free_string(urls_length);
    kcrawl_urls_free(urls_handle);
    kcrawl_scrape_free(result);
}

void test_map_exclude_patterns(void) {
    /* Excludes URLs matching patterns from URL map */
    KCRAWLScrape* result = scrape("{\"exclude_paths\":[\"/private/.*\",\"/api/.*\"],\"max_depth\":0,\"respect_robots_txt\":false}", NULL);
    assert(result != NULL && "expected call to succeed");
    KCRAWLUrls* urls_handle = kcrawl_scrape_urls(result);
    assert(urls_handle != NULL);
    char* urls_length = kcrawl_urls_length(urls_handle);
    // skipped: field 'urls.length' not available on result type
    kcrawl_free_string(urls_length);
    kcrawl_urls_free(urls_handle);
    kcrawl_scrape_free(result);
}

void test_map_include_subdomains(void) {
    /* Includes subdomain URLs in URL map discovery */
    KCRAWLScrape* result = scrape("{\"allow_subdomains\":true,\"max_depth\":0,\"respect_robots_txt\":false}", NULL);
    assert(result != NULL && "expected call to succeed");
    KCRAWLUrls* urls_handle = kcrawl_scrape_urls(result);
    assert(urls_handle != NULL);
    char* urls_length = kcrawl_urls_length(urls_handle);
    char* urls = kcrawl_scrape_urls(result);
    // skipped: field 'urls.length' not available on result type
    // skipped: field 'urls' not available on result type
    kcrawl_free_string(urls_length);
    kcrawl_free_string(urls);
    kcrawl_urls_free(urls_handle);
    kcrawl_scrape_free(result);
}

void test_map_large_sitemap(void) {
    /* Handles large sitemap with 100+ URLs */
    KCRAWLScrape* result = scrape("{\"respect_robots_txt\":false}", NULL);
    assert(result != NULL && "expected call to succeed");
    KCRAWLUrls* urls_handle = kcrawl_scrape_urls(result);
    assert(urls_handle != NULL);
    char* urls_length = kcrawl_urls_length(urls_handle);
    // skipped: field 'urls.length' not available on result type
    kcrawl_free_string(urls_length);
    kcrawl_urls_free(urls_handle);
    kcrawl_scrape_free(result);
}

void test_map_limit_pagination(void) {
    /* Limits map result count to specified maximum */
    KCRAWLScrape* result = scrape("{\"map_limit\":5,\"max_depth\":0,\"respect_robots_txt\":false}", NULL);
    assert(result != NULL && "expected call to succeed");
    KCRAWLUrls* urls_handle = kcrawl_scrape_urls(result);
    assert(urls_handle != NULL);
    char* urls_length = kcrawl_urls_length(urls_handle);
    // skipped: field 'urls.length' not available on result type
    kcrawl_free_string(urls_length);
    kcrawl_urls_free(urls_handle);
    kcrawl_scrape_free(result);
}

void test_map_search_filter(void) {
    /* Filters map results by search keyword */
    KCRAWLScrape* result = scrape("{\"map_search\":\"blog\",\"max_depth\":0,\"respect_robots_txt\":false}", NULL);
    assert(result != NULL && "expected call to succeed");
    KCRAWLUrls* urls_handle = kcrawl_scrape_urls(result);
    assert(urls_handle != NULL);
    char* urls_length = kcrawl_urls_length(urls_handle);
    char* urls = kcrawl_scrape_urls(result);
    // skipped: field 'urls.length' not available on result type
    // skipped: field 'urls' not available on result type
    kcrawl_free_string(urls_length);
    kcrawl_free_string(urls);
    kcrawl_urls_free(urls_handle);
    kcrawl_scrape_free(result);
}
