/*
 * This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5579fe333dc183413fc9a403566915cc9e4b6e65be0d92ecb4b7488fd293429b
 * To regenerate: alef generate
 * To verify freshness: alef verify --exit-code
 * Issues & docs: https://github.com/kreuzberg-dev/alef
 */
/* E2e tests for category: browser */

#include <assert.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "kreuzcrawl.h"
#include "test_runner.h"

void test_browser_config_auto_no_feature(void) {
    /* Browser mode 'auto' without browser feature enabled does not use browser */
    KCRAWLScrape* result = scrape("{\"browser\":{\"mode\":\"auto\"}}", NULL);
    assert(result != NULL && "expected call to succeed");
    char* status_code = kcrawl_scrape_status_code(result);
    KCRAWLBrowser* browser_handle = kcrawl_scrape_browser(result);
    assert(browser_handle != NULL);
    char* browser_js_render_hint = kcrawl_browser_js_render_hint(browser_handle);
    char* browser_browser_used = kcrawl_browser_browser_used(browser_handle);
    assert(strcmp(status_code, 200) == 0 && "equals assertion failed");
    // skipped: field 'browser.js_render_hint' not available on result type
    // skipped: field 'browser.browser_used' not available on result type
    kcrawl_free_string(status_code);
    kcrawl_free_string(browser_js_render_hint);
    kcrawl_free_string(browser_browser_used);
    kcrawl_browser_free(browser_handle);
    kcrawl_scrape_free(result);
}

void test_browser_config_never_mode(void) {
    /* Browser mode 'never' prevents browser fallback even for SPA shell content */
    KCRAWLScrape* result = scrape("{\"browser\":{\"mode\":\"never\"}}", NULL);
    assert(result != NULL && "expected call to succeed");
    char* status_code = kcrawl_scrape_status_code(result);
    KCRAWLBrowser* browser_handle = kcrawl_scrape_browser(result);
    assert(browser_handle != NULL);
    char* browser_js_render_hint = kcrawl_browser_js_render_hint(browser_handle);
    char* browser_browser_used = kcrawl_browser_browser_used(browser_handle);
    assert(strcmp(status_code, 200) == 0 && "equals assertion failed");
    // skipped: field 'browser.js_render_hint' not available on result type
    // skipped: field 'browser.browser_used' not available on result type
    kcrawl_free_string(status_code);
    kcrawl_free_string(browser_js_render_hint);
    kcrawl_free_string(browser_browser_used);
    kcrawl_browser_free(browser_handle);
    kcrawl_scrape_free(result);
}

void test_browser_crawl_mode_always(void) {
    /* Crawl with browser mode 'always' follows links using browser rendering */
    KCRAWLScrape* result = scrape("{\"browser\":{\"mode\":\"always\"},\"max_depth\":1,\"respect_robots_txt\":false}", NULL);
    assert(result != NULL && "expected call to succeed");
    KCRAWLPages* pages_handle = kcrawl_scrape_pages(result);
    assert(pages_handle != NULL);
    char* pages_length = kcrawl_pages_length(pages_handle);
    KCRAWLBrowser* browser_handle = kcrawl_scrape_browser(result);
    assert(browser_handle != NULL);
    char* browser_browser_used = kcrawl_browser_browser_used(browser_handle);
    // skipped: field 'pages.length' not available on result type
    // skipped: field 'browser.browser_used' not available on result type
    kcrawl_free_string(pages_length);
    kcrawl_free_string(browser_browser_used);
    kcrawl_browser_free(browser_handle);
    kcrawl_pages_free(pages_handle);
    kcrawl_scrape_free(result);
}

void test_browser_crawl_waf_fallback(void) {
    /* Crawl with browser mode 'auto' falls back to browser when encountering WAF 403 */
    KCRAWLScrape* result = scrape("{\"browser\":{\"mode\":\"auto\"},\"max_depth\":1,\"respect_robots_txt\":false}", NULL);
    assert(result != NULL && "expected call to succeed");
    KCRAWLPages* pages_handle = kcrawl_scrape_pages(result);
    assert(pages_handle != NULL);
    char* pages_length = kcrawl_pages_length(pages_handle);
    // skipped: field 'pages.length' not available on result type
    kcrawl_free_string(pages_length);
    kcrawl_pages_free(pages_handle);
    kcrawl_scrape_free(result);
}

void test_browser_detect_minimal_page(void) {
    /* Does NOT flag a short but real content page as needing JS rendering */
    KCRAWLScrape* result = scrape("{}", NULL);
    assert(result != NULL && "expected call to succeed");
    char* status_code = kcrawl_scrape_status_code(result);
    KCRAWLBrowser* browser_handle = kcrawl_scrape_browser(result);
    assert(browser_handle != NULL);
    char* browser_js_render_hint = kcrawl_browser_js_render_hint(browser_handle);
    char* browser_browser_used = kcrawl_browser_browser_used(browser_handle);
    assert(strcmp(status_code, 200) == 0 && "equals assertion failed");
    // skipped: field 'browser.js_render_hint' not available on result type
    // skipped: field 'browser.browser_used' not available on result type
    kcrawl_free_string(status_code);
    kcrawl_free_string(browser_js_render_hint);
    kcrawl_free_string(browser_browser_used);
    kcrawl_browser_free(browser_handle);
    kcrawl_scrape_free(result);
}

void test_browser_detect_next_empty(void) {
    /* Detects Next.js page with __NEXT_DATA__ but no rendered content as needing JS rendering */
    KCRAWLScrape* result = scrape("{}", NULL);
    assert(result != NULL && "expected call to succeed");
    char* status_code = kcrawl_scrape_status_code(result);
    KCRAWLBrowser* browser_handle = kcrawl_scrape_browser(result);
    assert(browser_handle != NULL);
    char* browser_js_render_hint = kcrawl_browser_js_render_hint(browser_handle);
    char* browser_browser_used = kcrawl_browser_browser_used(browser_handle);
    assert(strcmp(status_code, 200) == 0 && "equals assertion failed");
    // skipped: field 'browser.js_render_hint' not available on result type
    // skipped: field 'browser.browser_used' not available on result type
    kcrawl_free_string(status_code);
    kcrawl_free_string(browser_js_render_hint);
    kcrawl_free_string(browser_browser_used);
    kcrawl_browser_free(browser_handle);
    kcrawl_scrape_free(result);
}

void test_browser_detect_next_rendered(void) {
    /* Does NOT flag Next.js page with full SSR content as needing JS rendering */
    KCRAWLScrape* result = scrape("{}", NULL);
    assert(result != NULL && "expected call to succeed");
    char* status_code = kcrawl_scrape_status_code(result);
    char* html_not_empty = kcrawl_scrape_html_not_empty(result);
    KCRAWLBrowser* browser_handle = kcrawl_scrape_browser(result);
    assert(browser_handle != NULL);
    char* browser_js_render_hint = kcrawl_browser_js_render_hint(browser_handle);
    char* browser_browser_used = kcrawl_browser_browser_used(browser_handle);
    assert(strcmp(status_code, 200) == 0 && "equals assertion failed");
    // skipped: field 'html_not_empty' not available on result type
    // skipped: field 'browser.js_render_hint' not available on result type
    // skipped: field 'browser.browser_used' not available on result type
    kcrawl_free_string(status_code);
    kcrawl_free_string(html_not_empty);
    kcrawl_free_string(browser_js_render_hint);
    kcrawl_free_string(browser_browser_used);
    kcrawl_browser_free(browser_handle);
    kcrawl_scrape_free(result);
}

void test_browser_detect_normal_page(void) {
    /* Does NOT flag a normal server-rendered page as needing JS rendering */
    KCRAWLScrape* result = scrape("{}", NULL);
    assert(result != NULL && "expected call to succeed");
    char* status_code = kcrawl_scrape_status_code(result);
    KCRAWLBrowser* browser_handle = kcrawl_scrape_browser(result);
    assert(browser_handle != NULL);
    char* browser_js_render_hint = kcrawl_browser_js_render_hint(browser_handle);
    char* browser_browser_used = kcrawl_browser_browser_used(browser_handle);
    assert(strcmp(status_code, 200) == 0 && "equals assertion failed");
    // skipped: field 'browser.js_render_hint' not available on result type
    // skipped: field 'browser.browser_used' not available on result type
    kcrawl_free_string(status_code);
    kcrawl_free_string(browser_js_render_hint);
    kcrawl_free_string(browser_browser_used);
    kcrawl_browser_free(browser_handle);
    kcrawl_scrape_free(result);
}

void test_browser_detect_nuxt_shell(void) {
    /* Detects Nuxt SPA shell with empty #__nuxt div as needing JS rendering */
    KCRAWLScrape* result = scrape("{}", NULL);
    assert(result != NULL && "expected call to succeed");
    char* status_code = kcrawl_scrape_status_code(result);
    KCRAWLBrowser* browser_handle = kcrawl_scrape_browser(result);
    assert(browser_handle != NULL);
    char* browser_js_render_hint = kcrawl_browser_js_render_hint(browser_handle);
    char* browser_browser_used = kcrawl_browser_browser_used(browser_handle);
    assert(strcmp(status_code, 200) == 0 && "equals assertion failed");
    // skipped: field 'browser.js_render_hint' not available on result type
    // skipped: field 'browser.browser_used' not available on result type
    kcrawl_free_string(status_code);
    kcrawl_free_string(browser_js_render_hint);
    kcrawl_free_string(browser_browser_used);
    kcrawl_browser_free(browser_handle);
    kcrawl_scrape_free(result);
}

void test_browser_detect_react_shell(void) {
    /* Detects React SPA shell with empty #root div as needing JS rendering */
    KCRAWLScrape* result = scrape("{}", NULL);
    assert(result != NULL && "expected call to succeed");
    char* status_code = kcrawl_scrape_status_code(result);
    char* html_not_empty = kcrawl_scrape_html_not_empty(result);
    KCRAWLBrowser* browser_handle = kcrawl_scrape_browser(result);
    assert(browser_handle != NULL);
    char* browser_js_render_hint = kcrawl_browser_js_render_hint(browser_handle);
    char* browser_browser_used = kcrawl_browser_browser_used(browser_handle);
    assert(strcmp(status_code, 200) == 0 && "equals assertion failed");
    // skipped: field 'html_not_empty' not available on result type
    // skipped: field 'browser.js_render_hint' not available on result type
    // skipped: field 'browser.browser_used' not available on result type
    kcrawl_free_string(status_code);
    kcrawl_free_string(html_not_empty);
    kcrawl_free_string(browser_js_render_hint);
    kcrawl_free_string(browser_browser_used);
    kcrawl_browser_free(browser_handle);
    kcrawl_scrape_free(result);
}

void test_browser_detect_vue_shell(void) {
    /* Detects Vue SPA shell with empty #app div as needing JS rendering */
    KCRAWLScrape* result = scrape("{}", NULL);
    assert(result != NULL && "expected call to succeed");
    char* status_code = kcrawl_scrape_status_code(result);
    KCRAWLBrowser* browser_handle = kcrawl_scrape_browser(result);
    assert(browser_handle != NULL);
    char* browser_js_render_hint = kcrawl_browser_js_render_hint(browser_handle);
    char* browser_browser_used = kcrawl_browser_browser_used(browser_handle);
    assert(strcmp(status_code, 200) == 0 && "equals assertion failed");
    // skipped: field 'browser.js_render_hint' not available on result type
    // skipped: field 'browser.browser_used' not available on result type
    kcrawl_free_string(status_code);
    kcrawl_free_string(browser_js_render_hint);
    kcrawl_free_string(browser_browser_used);
    kcrawl_browser_free(browser_handle);
    kcrawl_scrape_free(result);
}

void test_browser_endpoint_invalid(void) {
    /* Browser endpoint must be a valid ws:// or wss:// URL, not http:// */
    KCRAWLScrape* result = scrape("{\"browser\":{\"endpoint\":\"http://not-websocket:3000\",\"mode\":\"always\"}}", NULL);
    assert(result == NULL && "expected call to fail");
}

void test_browser_extra_wait(void) {
    /* Browser extra_wait adds additional time after network_idle to ensure all async operations complete */
    KCRAWLScrape* result = scrape("{\"browser\":{\"extra_wait\":200,\"mode\":\"always\",\"wait\":\"network_idle\"}}", NULL);
    assert(result != NULL && "expected call to succeed");
    KCRAWLBrowser* browser_handle = kcrawl_scrape_browser(result);
    assert(browser_handle != NULL);
    char* browser_browser_used = kcrawl_browser_browser_used(browser_handle);
    // skipped: field 'browser.browser_used' not available on result type
    kcrawl_free_string(browser_browser_used);
    kcrawl_browser_free(browser_handle);
    kcrawl_scrape_free(result);
}

void test_browser_fallback_spa_render(void) {
    /* Browser auto re-fetches SPA shell when JS rendering is detected */
    KCRAWLScrape* result = scrape("{\"browser\":{\"mode\":\"auto\"}}", NULL);
    assert(result != NULL && "expected call to succeed");
    KCRAWLBrowser* browser_handle = kcrawl_scrape_browser(result);
    assert(browser_handle != NULL);
    char* browser_js_render_hint = kcrawl_browser_js_render_hint(browser_handle);
    char* browser_browser_used = kcrawl_browser_browser_used(browser_handle);
    // skipped: field 'browser.js_render_hint' not available on result type
    // skipped: field 'browser.browser_used' not available on result type
    kcrawl_free_string(browser_js_render_hint);
    kcrawl_free_string(browser_browser_used);
    kcrawl_browser_free(browser_handle);
    kcrawl_scrape_free(result);
}

void test_browser_fallback_waf_blocked(void) {
    /* Browser fallback triggers when WAF blocks the HTTP request (Cloudflare 403) */
    KCRAWLScrape* result = scrape("{\"browser\":{\"mode\":\"auto\"}}", NULL);
    assert(result != NULL && "expected call to succeed");
    KCRAWLBrowser* browser_handle = kcrawl_scrape_browser(result);
    assert(browser_handle != NULL);
    char* browser_browser_used = kcrawl_browser_browser_used(browser_handle);
    // skipped: field 'browser.browser_used' not available on result type
    kcrawl_free_string(browser_browser_used);
    kcrawl_browser_free(browser_handle);
    kcrawl_scrape_free(result);
}

void test_browser_mode_always(void) {
    /* Browser mode 'always' uses browser even for normal server-rendered pages */
    KCRAWLScrape* result = scrape("{\"browser\":{\"mode\":\"always\"}}", NULL);
    assert(result != NULL && "expected call to succeed");
    KCRAWLBrowser* browser_handle = kcrawl_scrape_browser(result);
    assert(browser_handle != NULL);
    char* browser_browser_used = kcrawl_browser_browser_used(browser_handle);
    // skipped: field 'browser.browser_used' not available on result type
    kcrawl_free_string(browser_browser_used);
    kcrawl_browser_free(browser_handle);
    kcrawl_scrape_free(result);
}

void test_browser_profile_basic(void) {
    /* Browser profile configuration persists and reuses browser state across crawl sessions */
    KCRAWLScrape* result = scrape("{\"browser\":{\"mode\":\"always\"},\"browser_profile\":\"test-profile\"}", NULL);
    assert(result != NULL && "expected call to succeed");
    KCRAWLBrowser* browser_handle = kcrawl_scrape_browser(result);
    assert(browser_handle != NULL);
    char* browser_browser_used = kcrawl_browser_browser_used(browser_handle);
    char* status_code = kcrawl_scrape_status_code(result);
    // skipped: field 'browser.browser_used' not available on result type
    assert(strcmp(status_code, 200) == 0 && "equals assertion failed");
    kcrawl_free_string(browser_browser_used);
    kcrawl_free_string(status_code);
    kcrawl_browser_free(browser_handle);
    kcrawl_scrape_free(result);
}

void test_browser_wait_fixed(void) {
    /* Browser wait strategy 'fixed' waits for a specific duration after page navigation */
    KCRAWLScrape* result = scrape("{\"browser\":{\"extra_wait\":100,\"mode\":\"always\",\"wait\":\"fixed\"}}", NULL);
    assert(result != NULL && "expected call to succeed");
    KCRAWLBrowser* browser_handle = kcrawl_scrape_browser(result);
    assert(browser_handle != NULL);
    char* browser_browser_used = kcrawl_browser_browser_used(browser_handle);
    char* status_code = kcrawl_scrape_status_code(result);
    // skipped: field 'browser.browser_used' not available on result type
    assert(strcmp(status_code, 200) == 0 && "equals assertion failed");
    kcrawl_free_string(browser_browser_used);
    kcrawl_free_string(status_code);
    kcrawl_browser_free(browser_handle);
    kcrawl_scrape_free(result);
}

void test_browser_wait_selector(void) {
    /* Browser wait strategy 'selector' waits for specific CSS selector before considering page loaded */
    KCRAWLScrape* result = scrape("{\"browser\":{\"mode\":\"always\",\"wait\":\"selector\",\"wait_selector\":\"#content\"}}", NULL);
    assert(result != NULL && "expected call to succeed");
    KCRAWLBrowser* browser_handle = kcrawl_scrape_browser(result);
    assert(browser_handle != NULL);
    char* browser_browser_used = kcrawl_browser_browser_used(browser_handle);
    char* status_code = kcrawl_scrape_status_code(result);
    // skipped: field 'browser.browser_used' not available on result type
    assert(strcmp(status_code, 200) == 0 && "equals assertion failed");
    kcrawl_free_string(browser_browser_used);
    kcrawl_free_string(status_code);
    kcrawl_browser_free(browser_handle);
    kcrawl_scrape_free(result);
}
