// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// Result from a single page action execution.
/// </summary>
public sealed class ActionResult
{
    /// <summary>
    /// Zero-based index of the action in the sequence.
    /// </summary>
    [JsonPropertyName("actionIndex")]
    public required nuint ActionIndex { get; set; }

    /// <summary>
    /// The type of action that was executed.
    /// </summary>
    [JsonPropertyName("actionType")]
    public required string ActionType { get; set; }

    /// <summary>
    /// Whether the action completed successfully.
    /// </summary>
    [JsonPropertyName("success")]
    public required bool Success { get; set; }

    /// <summary>
    /// Action-specific return data (screenshot bytes, JS return value, scraped HTML).
    /// </summary>
    [JsonPropertyName("data")]
    public string? Data { get; set; } = null;

    /// <summary>
    /// Error message if the action failed.
    /// </summary>
    [JsonPropertyName("error")]
    public string? Error { get; set; } = null;

}
