// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f59672cb20633a6857265f34334abf792bf74c109366dbcdf3b1dbfe4027dc4e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// The category of a downloaded asset.
/// </summary>
public enum AssetCategory
{
    /// <summary>
    /// A document file (PDF, DOC, etc.).
    /// </summary>
    [JsonPropertyName("document")]
    Document,
    /// <summary>
    /// An image file.
    /// </summary>
    [JsonPropertyName("image")]
    Image,
    /// <summary>
    /// An audio file.
    /// </summary>
    [JsonPropertyName("audio")]
    Audio,
    /// <summary>
    /// A video file.
    /// </summary>
    [JsonPropertyName("video")]
    Video,
    /// <summary>
    /// A font file.
    /// </summary>
    [JsonPropertyName("font")]
    Font,
    /// <summary>
    /// A CSS stylesheet.
    /// </summary>
    [JsonPropertyName("stylesheet")]
    Stylesheet,
    /// <summary>
    /// A JavaScript file.
    /// </summary>
    [JsonPropertyName("script")]
    Script,
    /// <summary>
    /// An archive file (ZIP, TAR, etc.).
    /// </summary>
    [JsonPropertyName("archive")]
    Archive,
    /// <summary>
    /// A data file (JSON, XML, CSV, etc.).
    /// </summary>
    [JsonPropertyName("data")]
    Data,
    /// <summary>
    /// An unrecognized asset type.
    /// </summary>
    [JsonPropertyName("other")]
    Other,
}
