// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0ca68837f600b021a368d04031b3f179c23e61b420b44a4e62afb4090be69525
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// A bad gateway error occurred (HTTP 502).
/// </summary>
public class BadGatewayException : CrawlErrorException
{
    public BadGatewayException(string message) : base(message) { }

    public BadGatewayException(string message, Exception innerException) : base(message, innerException) { }
}
