// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5fe7349bb6652c47fba5231171bbafdd1bf743e1c6c68fe6b52bcecda7a5f8c1
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// A bad gateway error occurred (HTTP 502).
/// </summary>
public class BadGatewayException : CrawlErrorException
{
    public BadGatewayException(string message) : base(message) { }

    public BadGatewayException(string message, Exception innerException) : base(message, innerException) { }
}
