// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2bde9479ae393f06202462239c9e4827bbd70eaa8b07b217fe06aa66c02c19cc
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// A bad gateway error occurred (HTTP 502).
/// </summary>
public class BadGatewayException : CrawlErrorException
{
    public BadGatewayException(string message) : base(message) { }

    public BadGatewayException(string message, Exception innerException) : base(message, innerException) { }
}
