// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c7ccb8950f448d5ad65e78649c618fb261c896faa19f3af6273aa19a09c8d4b9
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;
/// <summary>
/// Browser backend used for JavaScript rendering.
/// </summary>
[JsonConverter(typeof(BrowserBackendJsonConverter))]
public enum BrowserBackend
{
    /// <summary>
    /// Existing Chromium/CDP backend powered by chromiumoxide.
    /// </summary>
    [JsonPropertyName("chromiumoxide")]
    Chromiumoxide,
    /// <summary>
    /// Kreuzcrawl-owned native browser backend derived from Obscura.
    /// </summary>
    [JsonPropertyName("native")]
    Native,
}


/// <summary>
/// Custom JSON converter for <see cref="BrowserBackend"/> that respects explicit variant names.
/// </summary>
internal sealed class BrowserBackendJsonConverter : JsonConverter<BrowserBackend>
{
    public override BrowserBackend Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "chromiumoxide" => BrowserBackend.Chromiumoxide,
            "native" => BrowserBackend.Native,
            _ => throw new JsonException($"Unknown BrowserBackend value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, BrowserBackend value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            BrowserBackend.Chromiumoxide => "chromiumoxide",
            BrowserBackend.Native => "native",
            _ => throw new JsonException($"Unknown BrowserBackend value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
