// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0070221070bfc845d4cd03259048f84aee7675d5ea463a83e36621bd4b9656e4
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The browser page load or rendering timed out.
/// </summary>
public class BrowserTimeoutException : CrawlErrorException
{
    public BrowserTimeoutException(string message) : base(message) { }

    public BrowserTimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
