// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8b342312994c200c31887452a5ad22f8673b2e1634e9a5593bf410b8f31e82e0
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The browser page load or rendering timed out.
/// </summary>
public class BrowserTimeoutException : CrawlErrorException
{
    public BrowserTimeoutException(string message) : base(message) { }

    public BrowserTimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
