// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7a3564010524b642a0db1ce18b1aeb45f2e4be06aa654f009ec79fd73e44a49a
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The browser failed to launch, connect, or navigate.
/// </summary>
public class BrowserErrorException : CrawlErrorException
{
    public BrowserErrorException(string message) : base(message) { }

    public BrowserErrorException(string message, Exception innerException) : base(message, innerException) { }
}
