// This file is auto-generated by alef. DO NOT EDIT.

namespace Kreuzcrawl;

/// <summary>
/// When to use the headless browser fallback.
/// </summary>
public enum BrowserMode
{
    /// <summary>
    /// Automatically detect when JS rendering is needed and fall back to browser.
    /// </summary>
    Auto,
    /// <summary>
    /// Always use the browser for every request.
    /// </summary>
    Always,
    /// <summary>
    /// Never use the browser fallback.
    /// </summary>
    Never,
}
