// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7c65798781ca233bac69e3babc3b17deed8ea5ca292bafb454978e88af199c38
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The browser page load or rendering timed out.
/// </summary>
public class BrowserTimeoutException : CrawlErrorException
{
    public BrowserTimeoutException(string message) : base(message) { }

    public BrowserTimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
