// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9895b60f6d5fb095c6d1779bde7879c8e27380ad73a146ca4a5888f7696c339d
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;
/// <summary>
/// When to use the headless browser fallback.
/// </summary>
[JsonConverter(typeof(BrowserModeJsonConverter))]
public enum BrowserMode
{
    /// <summary>
    /// Automatically detect when JS rendering is needed and fall back to browser.
    /// </summary>
    [JsonPropertyName("auto")]
    Auto,
    /// <summary>
    /// Always use the browser for every request.
    /// </summary>
    [JsonPropertyName("always")]
    Always,
    /// <summary>
    /// Never use the browser fallback.
    /// </summary>
    [JsonPropertyName("never")]
    Never,
}


/// <summary>
/// Custom JSON converter for <see cref="BrowserMode"/> that respects explicit variant names.
/// </summary>
internal sealed class BrowserModeJsonConverter : JsonConverter<BrowserMode>
{
    public override BrowserMode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "auto" => BrowserMode.Auto,
            "always" => BrowserMode.Always,
            "never" => BrowserMode.Never,
            _ => throw new JsonException($"Unknown BrowserMode value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, BrowserMode value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            BrowserMode.Auto => "auto",
            BrowserMode.Always => "always",
            BrowserMode.Never => "never",
            _ => throw new JsonException($"Unknown BrowserMode value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
