// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:81733f5689c735737ec649ced3c4a751ff2180276000ddfc8fdea9b128ea9eca
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;
/// <summary>/// When to use the headless browser fallback./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum BrowserMode
{    /// <summary>    /// Automatically detect when JS rendering is needed and fall back to browser.    /// </summary>
    [JsonPropertyName("auto")]
    Auto,    /// <summary>    /// Always use the browser for every request.    /// </summary>
    [JsonPropertyName("always")]
    Always,    /// <summary>    /// Never use the browser fallback.    /// </summary>
    [JsonPropertyName("never")]
    Never,
}
