// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7c8d9bd3224292bb7edf8554faafc8d14d919c1d65ed449eee7806a47a111ef6
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;
/// <summary>
/// Browser backend used for JavaScript rendering.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum BrowserBackend
{    /// <summary>
     /// Existing Chromium/CDP backend powered by chromiumoxide.
     /// </summary>
    [JsonPropertyName("chromiumoxide")]
    Chromiumoxide,    /// <summary>
                      /// Kreuzcrawl-owned native browser backend derived from Obscura.
                      /// </summary>
    [JsonPropertyName("native")]
    Native,
}
