// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e0b048907e4acd1bff8132ca9fab8a2ec941d36e30e70ac1f6ce3cd337219c92
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The browser failed to launch, connect, or navigate.
/// </summary>
public class BrowserErrorException : CrawlErrorException
{
    public BrowserErrorException(string message) : base(message) { }

    public BrowserErrorException(string message, Exception innerException) : base(message, innerException) { }
}
