// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:26ec3c6966a218eafbf75bfee4f615f5e6ed43a791019493e432c91c667ca90d
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;
/// <summary>
/// Browser backend used for JavaScript rendering.
/// </summary>
[JsonConverter(typeof(BrowserBackendJsonConverter))]
public enum BrowserBackend
{    /// <summary>
     /// Existing Chromium/CDP backend powered by chromiumoxide.
     /// </summary>
    [JsonPropertyName("chromiumoxide")]
    Chromiumoxide,    /// <summary>
                      /// Kreuzcrawl-owned native browser backend derived from Obscura.
                      /// </summary>
    [JsonPropertyName("native")]
    Native,
}


/// <summary>Custom JSON converter for <see cref="BrowserBackend"/> that respects explicit variant names.</summary>
internal sealed class BrowserBackendJsonConverter : JsonConverter<BrowserBackend>
{
    public override BrowserBackend Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "chromiumoxide" => BrowserBackend.Chromiumoxide,
            "native" => BrowserBackend.Native,
            _ => throw new JsonException($"Unknown BrowserBackend value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, BrowserBackend value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            BrowserBackend.Chromiumoxide => "chromiumoxide",
            BrowserBackend.Native => "native",
            _ => throw new JsonException($"Unknown BrowserBackend value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
