// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d0875c4eff80f4b4aa7f1d2cc39dfb24e7839258c9b4893ebdd1529c47cba6cc
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The browser failed to launch, connect, or navigate.
/// </summary>
public class BrowserErrorException : CrawlErrorException
{
    public BrowserErrorException(string message) : base(message) { }

    public BrowserErrorException(string message, Exception innerException) : base(message, innerException) { }
}
