// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

public sealed class CitationReference
{
    [JsonPropertyName("index")]
    public ulong Index { get; set; } = 0;

    [JsonPropertyName("url")]
    public string Url { get; set; } = "";

    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

}
