// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:65b63a6245754d8675ea7bcef440e762ce10d2dca0c3159c06c9abcd9ef58d45
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// A connection error occurred.
/// </summary>
public class ConnectionException : CrawlErrorException
{
    public ConnectionException(string message) : base(message) { }

    public ConnectionException(string message, Exception innerException) : base(message, innerException) { }
}
