// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a4f9b8071effc1575c41711eb26e77752547f9a379c62b408058b380763250aa
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// A connection error occurred.
/// </summary>
public class ConnectionException : CrawlErrorException
{
    public ConnectionException(string message) : base(message) { }

    public ConnectionException(string message, Exception innerException) : base(message, innerException) { }
}
