// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// Information about an HTTP cookie received from a response.
/// </summary>
public sealed class CookieInfo
{
    /// <summary>
    /// The cookie name.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    /// <summary>
    /// The cookie value.
    /// </summary>
    [JsonPropertyName("value")]
    public string Value { get; set; } = "";

    /// <summary>
    /// The cookie domain, if specified.
    /// </summary>
    [JsonPropertyName("domain")]
    public string? Domain { get; set; } = null;

    /// <summary>
    /// The cookie path, if specified.
    /// </summary>
    [JsonPropertyName("path")]
    public string? Path { get; set; } = null;

}
