// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:455c860e9721455a31185f8584cf938ee8faec638767e29944968e84e86be7ff
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// Errors that can occur during crawling, scraping, or mapping operations.
/// </summary>
public class CrawlErrorException : KreuzcrawlException
{
    public CrawlErrorException(string message) : base(message) { }

    public CrawlErrorException(string message, Exception innerException) : base(message, innerException) { }
}
