// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fced693bde80386ea9407ef3ff4876dcfb37ececce19becec06a496f86099891
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// Errors that can occur during crawling, scraping, or mapping operations.
/// </summary>
public class CrawlErrorException : KreuzcrawlException
{
    public CrawlErrorException(string message) : base(message) { }

    public CrawlErrorException(string message, Exception innerException) : base(message, innerException) { }
}
