// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:6487ae34593b6758d39def87238768733218de7862b01d3b724add4c4efddad2
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// Errors that can occur during crawling, scraping, or mapping operations.
/// </summary>
public class CrawlErrorException : KreuzcrawlException
{
    public CrawlErrorException(string message) : base(message) { }

    public CrawlErrorException(string message, Exception innerException) : base(message, innerException) { }
}
