// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:046006c9c535ab6a0ecaa1b7ff90e95aae2b11fc446ea68adae07d5f9bdd3af2
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// Data was lost or truncated during transfer.
/// </summary>
public class DataLossException : CrawlErrorException
{
    public DataLossException(string message) : base(message) { }

    public DataLossException(string message, Exception innerException) : base(message, innerException) { }
}
