// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b0da2f779427adb8164a650ae13f4bff7e5d612f1be06c12b5229fb65238455b
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// Data was lost or truncated during transfer.
/// </summary>
public class DataLossException : CrawlErrorException
{
    public DataLossException(string message) : base(message) { }

    public DataLossException(string message, Exception innerException) : base(message, innerException) { }
}
