// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:bdb701df0967a71ad55f33851f6cb2fc1adbe06fecfd322979c96c076e6e33e4
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// Data was lost or truncated during transfer.
/// </summary>
public class DataLossException : CrawlErrorException
{
    public DataLossException(string message) : base(message) { }

    public DataLossException(string message, Exception innerException) : base(message, innerException) { }
}
