// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8896b7e192e408f916c81acf04c97fc5ee10b269fe22c287e9eefab02fada615
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// URL denied by SSRF policy: private IP, metadata IP, etc.
/// </summary>
public class DeniedByPolicyException : SsrfErrorException
{
    public DeniedByPolicyException(string message) : base(message) { }

    public DeniedByPolicyException(string message, Exception innerException) : base(message, innerException) { }
}
