// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:6de2d7a3fff7e34a7488334afa8e014e203513905446c2f051c0110b98c25d84
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// URL denied by SSRF policy: private IP, metadata IP, etc.
/// </summary>
public class DeniedByPolicyException : SsrfErrorException
{
    public DeniedByPolicyException(string message) : base(message) { }

    public DeniedByPolicyException(string message, Exception innerException) : base(message, innerException) { }
}
