// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c71da313df7b9a37bdd4f997f05150b92dfa5e723d3e2a4db0adafea6f951837
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// URL scheme not in allowlist (e.g., `ftp://` when only `http`/`https` allowed).
/// </summary>
public class DisallowedSchemeException : SsrfErrorException
{
    public DisallowedSchemeException(string message) : base(message) { }

    public DisallowedSchemeException(string message, Exception innerException) : base(message, innerException) { }
}
