// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b98764eed9e96431aff145f24a6d4e7b9070a8f8550c23508a96b387827f5f1f
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// URL scheme not in allowlist (e.g., `ftp://` when only `http`/`https` allowed).
/// </summary>
public class DisallowedSchemeException : SsrfErrorException
{
    public DisallowedSchemeException(string message) : base(message) { }

    public DisallowedSchemeException(string message, Exception innerException) : base(message, innerException) { }
}
