// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1c6361a6307834ec7afdcb4b3fc05f3d85697190f1447cf677d8848f76f24af1
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// A DNS resolution error occurred.
/// </summary>
public class DnsException : CrawlErrorException
{
    public DnsException(string message) : base(message) { }

    public DnsException(string message, Exception innerException) : base(message, innerException) { }
}
