// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b98764eed9e96431aff145f24a6d4e7b9070a8f8550c23508a96b387827f5f1f
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// A DNS resolution error occurred.
/// </summary>
public class DnsException : CrawlErrorException
{
    public DnsException(string message) : base(message) { }

    public DnsException(string message, Exception innerException) : base(message, innerException) { }
}
