// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d3670365d214947a88669c8a2175ad32f20d28523c590f4d4e7441d50311b4e1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// A downloaded asset from a page.
/// </summary>
public sealed record DownloadedAsset
{
    /// <summary>
    /// The original URL of the asset.
    /// </summary>
    [JsonPropertyName("url")]
    public string URL { get; init; } = "";

    /// <summary>
    /// The SHA-256 content hash of the asset.
    /// </summary>
    [JsonPropertyName("content_hash")]
    public string ContentHash { get; init; } = "";

    /// <summary>
    /// The MIME type from the Content-Type header.
    /// </summary>
    [JsonPropertyName("mime_type")]
    public string? MimeType { get; init; } = null;

    /// <summary>
    /// The size of the asset in bytes.
    /// </summary>
    [JsonPropertyName("size")]
    public ulong Size { get; init; } = 0;

    /// <summary>
    /// The category of the asset.
    /// </summary>
    [JsonPropertyName("asset_category")]
    public AssetCategory? AssetCategory { get; init; } = null;

    /// <summary>
    /// The HTML tag that referenced this asset (e.g., "link", "script", "img").
    /// </summary>
    [JsonPropertyName("html_tag")]
    public string? HTMLTag { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="DownloadedAsset"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzcrawlException">When the JSON cannot be deserialised.</exception>
    public static DownloadedAsset FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<DownloadedAsset>(json, JsonOptions)
                ?? throw new KreuzcrawlException($"Failed to parse DownloadedAsset from JSON: deserializer returned null");
        }
        catch (KreuzcrawlException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzcrawlException($"Failed to parse DownloadedAsset from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
