// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:43b15cf030dbb64af70326952867d1b0ce799095369579bbc5fca849c6c2c0cc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// A downloaded asset from a page.
/// </summary>
public sealed class DownloadedAsset
{
    /// <summary>
    /// The original URL of the asset.
    /// </summary>
    [JsonPropertyName("url")]
    public string Url { get; set; } = "";

    /// <summary>
    /// The SHA-256 content hash of the asset.
    /// </summary>
    [JsonPropertyName("content_hash")]
    public string ContentHash { get; set; } = "";

    /// <summary>
    /// The MIME type from the Content-Type header.
    /// </summary>
    [JsonPropertyName("mime_type")]
    public string? MimeType { get; set; } = null;

    /// <summary>
    /// The size of the asset in bytes.
    /// </summary>
    [JsonPropertyName("size")]
    public ulong Size { get; set; } = 0;

    /// <summary>
    /// The category of the asset.
    /// </summary>
    [JsonPropertyName("asset_category")]
    public AssetCategory? AssetCategory { get; set; } = null;

    /// <summary>
    /// The HTML tag that referenced this asset (e.g., "link", "script", "img").
    /// </summary>
    [JsonPropertyName("html_tag")]
    public string? HtmlTag { get; set; } = null;

}
