// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// Information about a favicon or icon link.
/// </summary>
public sealed class FaviconInfo
{
    /// <summary>
    /// The icon URL.
    /// </summary>
    [JsonPropertyName("url")]
    public string Url { get; set; } = "";

    /// <summary>
    /// The `rel` attribute (e.g., "icon", "apple-touch-icon").
    /// </summary>
    [JsonPropertyName("rel")]
    public string Rel { get; set; } = "";

    /// <summary>
    /// The `sizes` attribute, if present.
    /// </summary>
    [JsonPropertyName("sizes")]
    public string? Sizes { get; set; } = null;

    /// <summary>
    /// The MIME type, if present.
    /// </summary>
    [JsonPropertyName("mime_type")]
    public string? MimeType { get; set; } = null;

}
