// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5c3dfb14b1481a22f06a1c42085c64e4d3c08f679ce6266531eadf1b3539b9cb
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;
/// <summary>/// The type of a feed (RSS, Atom, or JSON Feed)./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum FeedType
{    /// <summary>    /// RSS feed.    /// </summary>
    [JsonPropertyName("rss")]
    Rss,    /// <summary>    /// Atom feed.    /// </summary>
    [JsonPropertyName("atom")]
    Atom,    /// <summary>    /// JSON Feed.    /// </summary>
    [JsonPropertyName("json_feed")]
    JsonFeed,
}
