// This file is auto-generated by alef. DO NOT EDIT.

namespace Kreuzcrawl;

/// <summary>
/// The type of a feed (RSS, Atom, or JSON Feed).
/// </summary>
public enum FeedType
{
    /// <summary>
    /// RSS feed.
    /// </summary>
    Rss,
    /// <summary>
    /// Atom feed.
    /// </summary>
    Atom,
    /// <summary>
    /// JSON Feed.
    /// </summary>
    JsonFeed,
}
