// This file is auto-generated by alef. DO NOT EDIT.
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// The type of a feed (RSS, Atom, or JSON Feed).
/// </summary>
public enum FeedType
{
    /// <summary>
    /// RSS feed.
    /// </summary>
    [JsonPropertyName("rss")]
    Rss,
    /// <summary>
    /// Atom feed.
    /// </summary>
    [JsonPropertyName("atom")]
    Atom,
    /// <summary>
    /// JSON Feed.
    /// </summary>
    [JsonPropertyName("json_feed")]
    JsonFeed,
}
