// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b6d32a8b35a6178b72719fd414ce1a2d64007f64af48bf3f185f5a3e98de47d8
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The request was forbidden (HTTP 403).
/// </summary>
public class ForbiddenException : CrawlErrorException
{
    public ForbiddenException(string message) : base(message) { }

    public ForbiddenException(string message, Exception innerException) : base(message, innerException) { }
}
