// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:447781c69c20f3b557b4d09f0278d882995d190d6cb6cabbdb79221daf703981
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The request was forbidden (HTTP 403).
/// </summary>
public class ForbiddenException : CrawlErrorException
{
    public ForbiddenException(string message) : base(message) { }

    public ForbiddenException(string message, Exception innerException) : base(message, innerException) { }
}
