// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e54f9396d633e17bc614209551236a2d46b0b5deaf5bcdc81d97844bd5c3420f
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The request was forbidden (HTTP 403).
/// </summary>
public class ForbiddenException : CrawlErrorException
{
    public ForbiddenException(string message) : base(message) { }

    public ForbiddenException(string message, Exception innerException) : base(message, innerException) { }
}
