// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:844df915154f680a35d6cba0bf29ade937e5ffa63c54639d604b2c0c18bd6a79
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The resource is permanently gone (HTTP 410).
/// </summary>
public class GoneException : CrawlErrorException
{
    public GoneException(string message) : base(message) { }

    public GoneException(string message, Exception innerException) : base(message, innerException) { }
}
