// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:15d02c69c38615e96464c441d5b862382f273470e44d070f76004da0d2cf8812
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The resource is permanently gone (HTTP 410).
/// </summary>
public class GoneException : CrawlErrorException
{
    public GoneException(string message) : base(message) { }

    public GoneException(string message, Exception innerException) : base(message, innerException) { }
}
