// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2993fbc38a96c38ce794c49583670e23ac73a921000d5a5ded6511494275a798
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The resource is permanently gone (HTTP 410).
/// </summary>
public class GoneException : CrawlErrorException
{
    public GoneException(string message) : base(message) { }

    public GoneException(string message, Exception innerException) : base(message, innerException) { }
}
