// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:10fd8884dc42e20590862b58827e77a095a19786603d0504744b5cace12add36
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// Information about an image found on a page.
/// </summary>
public sealed class ImageInfo
{
    /// <summary>
    /// The image URL.
    /// </summary>
    [JsonPropertyName("url")]
    public string Url { get; set; } = "";

    /// <summary>
    /// The alt text, if present.
    /// </summary>
    [JsonPropertyName("alt")]
    public string? Alt { get; set; } = null;

    /// <summary>
    /// The width attribute, if present and parseable.
    /// </summary>
    [JsonPropertyName("width")]
    public uint? Width { get; set; } = null;

    /// <summary>
    /// The height attribute, if present and parseable.
    /// </summary>
    [JsonPropertyName("height")]
    public uint? Height { get; set; } = null;

    /// <summary>
    /// The source of the image reference.
    /// </summary>
    [JsonConverter(typeof(ImageSourceJsonConverter))]
    [JsonPropertyName("source")]
    public ImageSource? Source { get; set; } = null;

}
