// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:74de99d78969665be7fe561ee6d23a4e7e7ea97f70348c560fde67fa2e8a6017
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// Invalid URL format.
/// </summary>
public class InvalidUrlException : SsrfErrorException
{
    public InvalidUrlException(string message) : base(message) { }

    public InvalidUrlException(string message, Exception innerException) : base(message, innerException) { }
}
