// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:80d384c69e5651b68cbc9598622abc07929ee231b10601ac4dfc026450803069
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The provided configuration is invalid.
/// </summary>
public class InvalidConfigException : CrawlErrorException
{
    public InvalidConfigException(string message) : base(message) { }

    public InvalidConfigException(string message, Exception innerException) : base(message, innerException) { }
}
