// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4a1130eaa7f8e3312e90b66f3eb0a52e657e6378ee013ed7eeaada8817434913
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The provided configuration is invalid.
/// </summary>
public class InvalidConfigException : CrawlErrorException
{
    public InvalidConfigException(string message) : base(message) { }

    public InvalidConfigException(string message, Exception innerException) : base(message, innerException) { }
}
