// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:6de2d7a3fff7e34a7488334afa8e014e203513905446c2f051c0110b98c25d84
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// Invalid URL format.
/// </summary>
public class InvalidUrlException : SsrfErrorException
{
    public InvalidUrlException(string message) : base(message) { }

    public InvalidUrlException(string message, Exception innerException) : base(message, innerException) { }
}
