// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:689137b0ed6ef11560caf21444ae822de5314052bfb7cb5d27829dfb1e7c80ed
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// Invalid URL format.
/// </summary>
public class InvalidUrlException : SsrfErrorException
{
    public InvalidUrlException(string message) : base(message) { }

    public InvalidUrlException(string message, Exception innerException) : base(message, innerException) { }
}
