// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:27185243ffb8b9dd7aa000047ac6570987e13460b13692990410af82a75d4159
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The provided configuration is invalid.
/// </summary>
public class InvalidConfigException : CrawlErrorException
{
    public InvalidConfigException(string message) : base(message) { }

    public InvalidConfigException(string message, Exception innerException) : base(message, innerException) { }
}
