// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5e5c08a93e7bd5d6e87496873e5b02702a8e2524e421da0847d0b3a6a8611beb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// A JSON-LD structured data entry found on a page.
/// </summary>
public sealed class JsonLdEntry
{
    /// <summary>
    /// The `@type` value from the JSON-LD object.
    /// </summary>
    [JsonPropertyName("schema_type")]
    public string SchemaType { get; set; } = "";

    /// <summary>
    /// The `name` value, if present.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; } = null;

    /// <summary>
    /// The raw JSON-LD string.
    /// </summary>
    [JsonPropertyName("raw")]
    public string Raw { get; set; } = "";

}
