// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4a1130eaa7f8e3312e90b66f3eb0a52e657e6378ee013ed7eeaada8817434913
#nullable enable

using System;

namespace Kreuzcrawl;

public class KreuzcrawlException : Exception
{
    public int Code { get; }

    public KreuzcrawlException(int code, string message) : base(message)
    {
        Code = code;
    }

    public KreuzcrawlException(string message) : base(message)
    {
        Code = 0;
    }

    public KreuzcrawlException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
