// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b0da2f779427adb8164a650ae13f4bff7e5d612f1be06c12b5229fb65238455b
#nullable enable

using System;

namespace Kreuzcrawl;

public class KreuzcrawlException : Exception
{
    public int Code { get; }

    public KreuzcrawlException(int code, string message) : base(message)
    {
        Code = code;
    }

    public KreuzcrawlException(string message) : base(message)
    {
        Code = 0;
    }

    public KreuzcrawlException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
