// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b29b6ec2d44186b83cbdaab5608f5f6a606ef3b79dbd8ef6fd0dab8c27c716b2
#nullable enable

using System;

namespace Kreuzcrawl;

public class KreuzcrawlException : Exception
{
    public int Code { get; }

    public KreuzcrawlException(int code, string message) : base(message)
    {
        Code = code;
    }

    public KreuzcrawlException(string message) : base(message)
    {
        Code = 0;
    }

    public KreuzcrawlException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
