// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// The result of a map operation, containing discovered URLs.
/// </summary>
public sealed class MapResult
{
    /// <summary>
    /// The list of discovered URLs.
    /// </summary>
    [JsonPropertyName("urls")]
    public List<SitemapUrl> Urls { get; set; } = [];

}
