// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c9b0d2a3dfb56b9e78a20f2176a3a0d25f8268f22862f6596fca4b7dc0041e17
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The requested page was not found (HTTP 404).
/// </summary>
public class NotFoundException : CrawlErrorException
{
    public NotFoundException(string message) : base(message) { }

    public NotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
