// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:282f81672aefc64f37b375b71cdce514c8b1333f34056afb2247e60ce276a1dc
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The requested page was not found (HTTP 404).
/// </summary>
public class NotFoundException : CrawlErrorException
{
    public NotFoundException(string message) : base(message) { }

    public NotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
