// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:42cba53345bfa03607a118143529cae069edebcd6e06046a0d61ed5a35b20ea3
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The requested page was not found (HTTP 404).
/// </summary>
public class NotFoundException : CrawlErrorException
{
    public NotFoundException(string message) : base(message) { }

    public NotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
