// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b98764eed9e96431aff145f24a6d4e7b9070a8f8550c23508a96b387827f5f1f
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// Host not on allowlist when an allowlist is configured.
/// </summary>
public class NotOnAllowlistException : SsrfErrorException
{
    public NotOnAllowlistException(string message) : base(message) { }

    public NotOnAllowlistException(string message, Exception innerException) : base(message, innerException) { }
}
