// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c7ccb8950f448d5ad65e78649c618fb261c896faa19f3af6273aa19a09c8d4b9
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// Host not on allowlist when an allowlist is configured.
/// </summary>
public class NotOnAllowlistException : SsrfErrorException
{
    public NotOnAllowlistException(string message) : base(message) { }

    public NotOnAllowlistException(string message, Exception innerException) : base(message, innerException) { }
}
