// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a242af7f846968fbb34fa2c3c244dfbbc16d39e8561258ca333542d09b1a4b17
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// An unclassified error occurred.
/// </summary>
public class OtherException : CrawlErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
