// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:80d98aa194cd401b11c8a0b4a61b958eedf5b49dd175b61d50f16bdb3e3fc79b
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// An unclassified error occurred.
/// </summary>
public class OtherException : CrawlErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
