// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8bd81eb14e33677e0e37ebc436b1c1c455be4a08cb544afe99ec3d0d382f3837
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// An unclassified error occurred.
/// </summary>
public class OtherException : CrawlErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
