// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// Metadata extracted from an HTML page's `<meta>` tags and `<title>` element.
/// </summary>
public sealed class PageMetadata
{
    /// <summary>
    /// The page title from the `<title>` element.
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; set; } = null;

    /// <summary>
    /// The meta description.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; } = null;

    /// <summary>
    /// The canonical URL from `<link rel="canonical">`.
    /// </summary>
    [JsonPropertyName("canonicalUrl")]
    public string? CanonicalUrl { get; set; } = null;

    /// <summary>
    /// Keywords from `<meta name="keywords">`.
    /// </summary>
    [JsonPropertyName("keywords")]
    public string? Keywords { get; set; } = null;

    /// <summary>
    /// Author from `<meta name="author">`.
    /// </summary>
    [JsonPropertyName("author")]
    public string? Author { get; set; } = null;

    /// <summary>
    /// Viewport content from `<meta name="viewport">`.
    /// </summary>
    [JsonPropertyName("viewport")]
    public string? Viewport { get; set; } = null;

    /// <summary>
    /// Theme color from `<meta name="theme-color">`.
    /// </summary>
    [JsonPropertyName("themeColor")]
    public string? ThemeColor { get; set; } = null;

    /// <summary>
    /// Generator from `<meta name="generator">`.
    /// </summary>
    [JsonPropertyName("generator")]
    public string? Generator { get; set; } = null;

    /// <summary>
    /// Robots content from `<meta name="robots">`.
    /// </summary>
    [JsonPropertyName("robots")]
    public string? Robots { get; set; } = null;

    /// <summary>
    /// The `lang` attribute from the `<html>` element.
    /// </summary>
    [JsonPropertyName("htmlLang")]
    public string? HtmlLang { get; set; } = null;

    /// <summary>
    /// The `dir` attribute from the `<html>` element.
    /// </summary>
    [JsonPropertyName("htmlDir")]
    public string? HtmlDir { get; set; } = null;

    /// <summary>
    /// Open Graph title.
    /// </summary>
    [JsonPropertyName("ogTitle")]
    public string? OgTitle { get; set; } = null;

    /// <summary>
    /// Open Graph type.
    /// </summary>
    [JsonPropertyName("ogType")]
    public string? OgType { get; set; } = null;

    /// <summary>
    /// Open Graph image URL.
    /// </summary>
    [JsonPropertyName("ogImage")]
    public string? OgImage { get; set; } = null;

    /// <summary>
    /// Open Graph description.
    /// </summary>
    [JsonPropertyName("ogDescription")]
    public string? OgDescription { get; set; } = null;

    /// <summary>
    /// Open Graph URL.
    /// </summary>
    [JsonPropertyName("ogUrl")]
    public string? OgUrl { get; set; } = null;

    /// <summary>
    /// Open Graph site name.
    /// </summary>
    [JsonPropertyName("ogSiteName")]
    public string? OgSiteName { get; set; } = null;

    /// <summary>
    /// Open Graph locale.
    /// </summary>
    [JsonPropertyName("ogLocale")]
    public string? OgLocale { get; set; } = null;

    /// <summary>
    /// Open Graph video URL.
    /// </summary>
    [JsonPropertyName("ogVideo")]
    public string? OgVideo { get; set; } = null;

    /// <summary>
    /// Open Graph audio URL.
    /// </summary>
    [JsonPropertyName("ogAudio")]
    public string? OgAudio { get; set; } = null;

    /// <summary>
    /// Open Graph locale alternates.
    /// </summary>
    [JsonPropertyName("ogLocaleAlternates")]
    public List<string>? OgLocaleAlternates { get; set; } = null;

    /// <summary>
    /// Twitter card type.
    /// </summary>
    [JsonPropertyName("twitterCard")]
    public string? TwitterCard { get; set; } = null;

    /// <summary>
    /// Twitter title.
    /// </summary>
    [JsonPropertyName("twitterTitle")]
    public string? TwitterTitle { get; set; } = null;

    /// <summary>
    /// Twitter description.
    /// </summary>
    [JsonPropertyName("twitterDescription")]
    public string? TwitterDescription { get; set; } = null;

    /// <summary>
    /// Twitter image URL.
    /// </summary>
    [JsonPropertyName("twitterImage")]
    public string? TwitterImage { get; set; } = null;

    /// <summary>
    /// Twitter site handle.
    /// </summary>
    [JsonPropertyName("twitterSite")]
    public string? TwitterSite { get; set; } = null;

    /// <summary>
    /// Twitter creator handle.
    /// </summary>
    [JsonPropertyName("twitterCreator")]
    public string? TwitterCreator { get; set; } = null;

    /// <summary>
    /// Dublin Core title.
    /// </summary>
    [JsonPropertyName("dcTitle")]
    public string? DcTitle { get; set; } = null;

    /// <summary>
    /// Dublin Core creator.
    /// </summary>
    [JsonPropertyName("dcCreator")]
    public string? DcCreator { get; set; } = null;

    /// <summary>
    /// Dublin Core subject.
    /// </summary>
    [JsonPropertyName("dcSubject")]
    public string? DcSubject { get; set; } = null;

    /// <summary>
    /// Dublin Core description.
    /// </summary>
    [JsonPropertyName("dcDescription")]
    public string? DcDescription { get; set; } = null;

    /// <summary>
    /// Dublin Core publisher.
    /// </summary>
    [JsonPropertyName("dcPublisher")]
    public string? DcPublisher { get; set; } = null;

    /// <summary>
    /// Dublin Core date.
    /// </summary>
    [JsonPropertyName("dcDate")]
    public string? DcDate { get; set; } = null;

    /// <summary>
    /// Dublin Core type.
    /// </summary>
    [JsonPropertyName("dcType")]
    public string? DcType { get; set; } = null;

    /// <summary>
    /// Dublin Core format.
    /// </summary>
    [JsonPropertyName("dcFormat")]
    public string? DcFormat { get; set; } = null;

    /// <summary>
    /// Dublin Core identifier.
    /// </summary>
    [JsonPropertyName("dcIdentifier")]
    public string? DcIdentifier { get; set; } = null;

    /// <summary>
    /// Dublin Core language.
    /// </summary>
    [JsonPropertyName("dcLanguage")]
    public string? DcLanguage { get; set; } = null;

    /// <summary>
    /// Dublin Core rights.
    /// </summary>
    [JsonPropertyName("dcRights")]
    public string? DcRights { get; set; } = null;

    /// <summary>
    /// Article metadata from `article:*` Open Graph tags.
    /// </summary>
    [JsonPropertyName("article")]
    public ArticleMetadata? Article { get; set; } = null;

    /// <summary>
    /// Hreflang alternate links.
    /// </summary>
    [JsonPropertyName("hreflangs")]
    public List<HreflangEntry>? Hreflangs { get; set; } = null;

    /// <summary>
    /// Favicon and icon links.
    /// </summary>
    [JsonPropertyName("favicons")]
    public List<FaviconInfo>? Favicons { get; set; } = null;

    /// <summary>
    /// Heading elements (h1-h6).
    /// </summary>
    [JsonPropertyName("headings")]
    public List<HeadingInfo>? Headings { get; set; } = null;

    /// <summary>
    /// Computed word count of the page body text.
    /// </summary>
    [JsonPropertyName("wordCount")]
    public nuint? WordCount { get; set; } = null;

}
