// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9539ee3d14edfaed0ab07a03dbc8c42d608cc5692f0ab312c6f8869d168b8aaf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// Proxy configuration for HTTP requests.
/// </summary>
public sealed record ProxyConfig
{
    /// <summary>
    /// Proxy URL (e.g. "http://proxy:8080", "socks5://proxy:1080").
    /// </summary>
    [JsonPropertyName("url")]
    public string Url { get; init; } = "";

    /// <summary>
    /// Optional username for proxy authentication.
    /// </summary>
    [JsonPropertyName("username")]
    public string? Username { get; init; } = null;

    /// <summary>
    /// Optional password for proxy authentication.
    /// </summary>
    [JsonPropertyName("password")]
    public string? Password { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="ProxyConfig"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzcrawlException">When the JSON cannot be deserialised.</exception>
    public static ProxyConfig FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<ProxyConfig>(json, JsonOptions)
                ?? throw new KreuzcrawlException($"Failed to parse ProxyConfig from JSON: deserializer returned null");
        }
        catch (KreuzcrawlException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzcrawlException($"Failed to parse ProxyConfig from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
