// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b1ec46c33d2b843ef4d8040e33cbff4493ffe1ebf4abfefe5cd9c8299d29db10
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The request was rate-limited (HTTP 429).
/// </summary>
public class RateLimitedException : CrawlErrorException
{
    public RateLimitedException(string message) : base(message) { }

    public RateLimitedException(string message, Exception innerException) : base(message, innerException) { }
}
