// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8b342312994c200c31887452a5ad22f8673b2e1634e9a5593bf410b8f31e82e0
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The request was rate-limited (HTTP 429).
/// </summary>
public class RateLimitedException : CrawlErrorException
{
    public RateLimitedException(string message) : base(message) { }

    public RateLimitedException(string message, Exception innerException) : base(message, innerException) { }
}
