// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:835d6da2fd74ea3e92d27bb3bd18ac61f50e74ada570fba813efb521101172a2
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The request was rate-limited (HTTP 429).
/// </summary>
public class RateLimitedException : CrawlErrorException
{
    public RateLimitedException(string message) : base(message) { }

    public RateLimitedException(string message, Exception innerException) : base(message, innerException) { }
}
