// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2575cfacac8db41b54290ac8262514f77aaedf34e17edc58fb622231e9ae2590
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// Response metadata extracted from HTTP headers.
/// </summary>
public sealed class ResponseMeta
{
    /// <summary>
    /// The ETag header value.
    /// </summary>
    [JsonPropertyName("etag")]
    public string? Etag { get; set; } = null;

    /// <summary>
    /// The Last-Modified header value.
    /// </summary>
    [JsonPropertyName("last_modified")]
    public string? LastModified { get; set; } = null;

    /// <summary>
    /// The Cache-Control header value.
    /// </summary>
    [JsonPropertyName("cache_control")]
    public string? CacheControl { get; set; } = null;

    /// <summary>
    /// The Server header value.
    /// </summary>
    [JsonPropertyName("server")]
    public string? Server { get; set; } = null;

    /// <summary>
    /// The X-Powered-By header value.
    /// </summary>
    [JsonPropertyName("x_powered_by")]
    public string? XPoweredBy { get; set; } = null;

    /// <summary>
    /// The Content-Language header value.
    /// </summary>
    [JsonPropertyName("content_language")]
    public string? ContentLanguage { get; set; } = null;

    /// <summary>
    /// The Content-Encoding header value.
    /// </summary>
    [JsonPropertyName("content_encoding")]
    public string? ContentEncoding { get; set; } = null;

}
