// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d558260d3eab92fa78bb3a6a15959d4511916bbf787a7de7a1b8ef92074fa5d8
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// A server error occurred (HTTP 5xx).
/// </summary>
public class ServerErrorException : CrawlErrorException
{
    public ServerErrorException(string message) : base(message) { }

    public ServerErrorException(string message, Exception innerException) : base(message, innerException) { }
}
