// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0ca68837f600b021a368d04031b3f179c23e61b420b44a4e62afb4090be69525
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// A server error occurred (HTTP 5xx).
/// </summary>
public class ServerErrorException : CrawlErrorException
{
    public ServerErrorException(string message) : base(message) { }

    public ServerErrorException(string message, Exception innerException) : base(message, innerException) { }
}
