// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:10fd8884dc42e20590862b58827e77a095a19786603d0504744b5cace12add36
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// An SSL/TLS error occurred.
/// </summary>
public class SslException : CrawlErrorException
{
    public SslException(string message) : base(message) { }

    public SslException(string message, Exception innerException) : base(message, innerException) { }
}
