// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1942424b53c939b6751bb9d1a31aaa45adb9067acc033a309de8e1d549682b2d
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// An SSL/TLS error occurred.
/// </summary>
public class SslException : CrawlErrorException
{
    public SslException(string message) : base(message) { }

    public SslException(string message, Exception innerException) : base(message, innerException) { }
}
