// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b98764eed9e96431aff145f24a6d4e7b9070a8f8550c23508a96b387827f5f1f
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// SSRF validation error.
/// </summary>
public class SsrfErrorException : KreuzcrawlException
{
    public SsrfErrorException(string message) : base(message) { }

    public SsrfErrorException(string message, Exception innerException) : base(message, innerException) { }
}
