// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:196d90a73fdb96222246064c5dce70f1723a6aca423cdf51502e56a3afefde29
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// A URL was rejected by SSRF policy (private IP, metadata, disallowed scheme, etc).
/// </summary>
public class SsrfPolicyViolationException : CrawlErrorException
{
    public SsrfPolicyViolationException(string message) : base(message) { }

    public SsrfPolicyViolationException(string message, Exception innerException) : base(message, innerException) { }
}
