// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c56b59b6ea36ea384e647b230eed0057f2d0e7ef003ea475f1f9a7ced369ae61
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The request timed out.
/// </summary>
public class TimeoutException : CrawlErrorException
{
    public TimeoutException(string message) : base(message) { }

    public TimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
