// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3c1c2cb7c2f610995b6d15dbf1e1a6e561317ad4f7e441e40ef3a486db0f9e1e
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The request was unauthorized (HTTP 401).
/// </summary>
public class UnauthorizedException : CrawlErrorException
{
    public UnauthorizedException(string message) : base(message) { }

    public UnauthorizedException(string message, Exception innerException) : base(message, innerException) { }
}
