// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a1a1685027ba4a27308f011607a5bc08ef1d9d47f6caaa93530de6531a67464b
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The request was unauthorized (HTTP 401).
/// </summary>
public class UnauthorizedException : CrawlErrorException
{
    public UnauthorizedException(string message) : base(message) { }

    public UnauthorizedException(string message, Exception innerException) : base(message, innerException) { }
}
