// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:aa8c20463c9aec8e53aeabc4d65081bfe7eba38b8b376eb3012ce4e4bc51d78a
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The requested capability is not supported by the active backend or build.
/// </summary>
public class UnsupportedException : CrawlErrorException
{
    public UnsupportedException(string message) : base(message) { }

    public UnsupportedException(string message, Exception innerException) : base(message, innerException) { }
}
