// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:42cba53345bfa03607a118143529cae069edebcd6e06046a0d61ed5a35b20ea3
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The requested capability is not supported by the active backend or build.
/// </summary>
public class UnsupportedException : CrawlErrorException
{
    public UnsupportedException(string message) : base(message) { }

    public UnsupportedException(string message, Exception innerException) : base(message, innerException) { }
}
