// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:78f92010cb53a187403eb06f260e13519dc99ca9b2d70433cdbbbe3fa0d27b05
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The request was blocked by a WAF or bot protection (HTTP 403 with WAF indicators).
/// </summary>
public class WafBlockedException : CrawlErrorException
{
    public WafBlockedException(string message) : base(message) { }

    public WafBlockedException(string message, Exception innerException) : base(message, innerException) { }
}
