// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:153b9e114210e23cebdc0c52f8d31be79d4bd9091c78f216063ff3eb5c982166
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The request was blocked by a WAF or bot protection (HTTP 403 with WAF indicators).
/// </summary>
public class WafBlockedException : CrawlErrorException
{
    public WafBlockedException(string message) : base(message) { }

    public WafBlockedException(string message, Exception innerException) : base(message, innerException) { }
}
