// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fc76bd42d2f4848687c48f2bf0011bc60b7aa96a87e69f400f42037af94c3b25
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// ignore_for_file: unused_local_variable

import 'package:test/test.dart';
import 'dart:io';
import 'package:kreuzcrawl/kreuzcrawl.dart';
import 'package:kreuzcrawl/src/kreuzcrawl_bridge_generated/frb_generated.dart'
    show RustLib;

// E2e tests for category: batch

String _alefE2eText(Object? value) {
  if (value == null) return '';
  // Check if it's an enum by examining its toString representation.
  final str = value.toString();
  if (str.contains('.')) {
    // Enum.toString() returns 'EnumName.variantName'. Extract the variant name.
    final parts = str.split('.');
    if (parts.length == 2) {
      final variantName = parts[1];
      // Convert camelCase variant names to snake_case for serde compatibility.
      // E.g. 'toolCalls' -> 'tool_calls', 'stop' -> 'stop'.
      return _camelToSnake(variantName);
    }
  }
  return str;
}

String _camelToSnake(String camel) {
  final buffer = StringBuffer();
  for (int i = 0; i < camel.length; i++) {
    final char = camel[i];
    if (char.contains(RegExp(r'[A-Z]'))) {
      if (i > 0) buffer.write('_');
      buffer.write(char.toLowerCase());
    } else {
      buffer.write(char);
    }
  }
  return buffer.toString();
}

void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test('Batch crawl of 2 seed URLs with links to discover', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json: r'{"max_depth":1,"respect_robots_txt":false}',
    );
    final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
    final urlsBase =
        Platform.environment["MOCK_SERVER_BATCH_CRAWL_BASIC"] ??
        (Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080") +
            "/fixtures/batch_crawl_basic";
    final urls = <String>[
      '/seed1',
      '/seed2',
    ].map((p) => p.startsWith('http') ? p : urlsBase + p).toList();
    final result = await KreuzcrawlBridge.batchCrawl(engine, urls);
    expect(result.completedCount, equals(2));
    expect(result.failedCount, equals(0));
    expect(result.totalCount, equals(2));
  });

  test('Batch crawl where one seed URL returns 404 error', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json: r'{"max_depth":1,"respect_robots_txt":false}',
    );
    final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
    final urlsBase =
        Platform.environment["MOCK_SERVER_BATCH_CRAWL_PARTIAL_FAILURE"] ??
        (Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080") +
            "/fixtures/batch_crawl_partial_failure";
    final urls = <String>[
      '/good_seed',
      '/bad_seed',
    ].map((p) => p.startsWith('http') ? p : urlsBase + p).toList();
    final result = await KreuzcrawlBridge.batchCrawl(engine, urls);
    expect(result.completedCount, equals(1));
    expect(result.failedCount, equals(1));
    expect(result.totalCount, equals(2));
  });

  test(
    'Batch crawl with max_depth=1 config verifying pages are discovered',
    () async {
      final engineConfig = await createCrawlConfigFromJson(
        json: r'{"max_depth":1,"respect_robots_txt":false}',
      );
      final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
      final urlsBase =
          Platform.environment["MOCK_SERVER_BATCH_CRAWL_WITH_CONFIG"] ??
          (Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080") +
              "/fixtures/batch_crawl_with_config";
      final urls = <String>[
        '/seed1',
        '/seed2',
      ].map((p) => p.startsWith('http') ? p : urlsBase + p).toList();
      final result = await KreuzcrawlBridge.batchCrawl(engine, urls);
      expect(result.completedCount, equals(2));
      expect(result.failedCount, equals(0));
    },
  );

  test('Batch scrape with empty batch_urls array returns error', () async {
    await expectLater(() async {
      final engine = await KreuzcrawlBridge.createEngine();
      final urlsBase =
          Platform.environment["MOCK_SERVER_BATCH_SCRAPE_EMPTY_URLS_ERROR"] ??
          (Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080") +
              "/fixtures/batch_scrape_empty_urls_error";
      final urls = <String>[]
          .map((p) => p.startsWith('http') ? p : urlsBase + p)
          .toList();
      return KreuzcrawlBridge.batchScrape(engine, urls);
    }(), throwsA(anything));
  });

  test('Batch scrape with aggressive preprocessing configuration', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json: r'{"content":{"preprocessing_preset":"aggressive"}}',
    );
    final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
    final urlsBase =
        Platform.environment["MOCK_SERVER_BATCH_SCRAPE_WITH_CONFIG"] ??
        (Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080") +
            "/fixtures/batch_scrape_with_config";
    final urls = <String>[
      '/article1',
      '/article2',
    ].map((p) => p.startsWith('http') ? p : urlsBase + p).toList();
    final result = await KreuzcrawlBridge.batchScrape(engine, urls);
    expect(result.completedCount, equals(2));
    expect(result.failedCount, equals(0));
    expect(result.totalCount, equals(2));
  });

  test('Batch scrape of multiple URLs all succeeding', () async {
    final engine = await KreuzcrawlBridge.createEngine();
    final urlsBase =
        Platform.environment["MOCK_SERVER_SCRAPE_BATCH_BASIC"] ??
        (Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080") +
            "/fixtures/scrape_batch_basic";
    final urls = <String>[
      '/page1',
      '/page2',
      '/page3',
    ].map((p) => p.startsWith('http') ? p : urlsBase + p).toList();
    final result = await KreuzcrawlBridge.batchScrape(engine, urls);
    expect(result.completedCount, equals(3));
    expect(result.failedCount, equals(0));
    expect(result.totalCount, equals(3));
  });

  test('Batch scrape with one URL failing returns partial results', () async {
    final engine = await KreuzcrawlBridge.createEngine();
    final urlsBase =
        Platform.environment["MOCK_SERVER_SCRAPE_BATCH_PARTIAL_FAILURE"] ??
        (Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080") +
            "/fixtures/scrape_batch_partial_failure";
    final urls = <String>[
      '/good1',
      '/bad',
      '/good2',
    ].map((p) => p.startsWith('http') ? p : urlsBase + p).toList();
    final result = await KreuzcrawlBridge.batchScrape(engine, urls);
    expect(result.completedCount, equals(2));
    expect(result.failedCount, equals(1));
    expect(result.totalCount, equals(3));
  });

  test('Batch scrape of 2 URLs completes with 2 results', () async {
    final engine = await KreuzcrawlBridge.createEngine();
    final urlsBase =
        Platform.environment["MOCK_SERVER_SCRAPE_BATCH_PROGRESS"] ??
        (Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080") +
            "/fixtures/scrape_batch_progress";
    final urls = <String>[
      '/target',
      '/other',
    ].map((p) => p.startsWith('http') ? p : urlsBase + p).toList();
    final result = await KreuzcrawlBridge.batchScrape(engine, urls);
    expect(result.totalCount, equals(2));
    expect(result.completedCount, equals(2));
  });
}
