// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e2c6c4051f3c35ede88254aa928c3cc98afb57be298e13c786c8342c1d840721
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// ignore_for_file: unused_local_variable

import 'package:test/test.dart';
import 'dart:io';
import 'package:kreuzcrawl/kreuzcrawl.dart';
import 'package:kreuzcrawl/src/kreuzcrawl_bridge_generated/frb_generated.dart'
    show RustLib;
import 'dart:convert';

// E2e tests for category: interaction
void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test(
    'Execute a sequence of multiple actions (click, type, click) and verify all succeed with correct indices',
    () async {
      final engineConfig = await createCrawlConfigFromJson(
        json: r'{"browser":{"mode":"always"}}',
      );
      final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
      final url =
          "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/interact_action_sequence";
      final result = await KreuzcrawlBridge.interact(engine, url);
      expect(result.actionResults[0].actionIndex, equals(0));
      expect(
        result.actionResults[0].actionType.toString().trim(),
        equals('click'.toString().trim()),
      );
      expect(result.actionResults[0].success, equals(true));
      expect(result.actionResults[1].actionIndex, equals(1));
      expect(
        result.actionResults[1].actionType.toString().trim(),
        equals('type'.toString().trim()),
      );
      expect(result.actionResults[1].success, equals(true));
      expect(result.actionResults[2].actionIndex, equals(2));
      expect(
        result.actionResults[2].actionType.toString().trim(),
        equals('click'.toString().trim()),
      );
      expect(result.actionResults[2].success, equals(true));
    },
  );

  test('Click a button element and verify success', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json: r'{"browser":{"mode":"always"}}',
    );
    final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
    final url =
        "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/interact_click_element";
    final result = await KreuzcrawlBridge.interact(engine, url);
    expect(result.actionResults[0].success, equals(true));
    expect(
      result.actionResults[0].actionType.toString().trim(),
      equals('click'.toString().trim()),
    );
    expect(result.actionResults[0].actionIndex, equals(0));
  });

  test(
    'Execute JavaScript that returns document.title and verify success with data',
    () async {
      final engineConfig = await createCrawlConfigFromJson(
        json: r'{"browser":{"mode":"always"}}',
      );
      final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
      final url =
          "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/interact_execute_js";
      final result = await KreuzcrawlBridge.interact(engine, url);
      expect(result.actionResults[0].success, equals(true));
      expect(
        result.actionResults[0].actionType.toString().trim(),
        equals('executeJs'.toString().trim()),
      );
      expect(result.actionResults[0].data, contains('JS Test Page'));
    },
  );

  test(
    'Click on a non-existent selector and verify error in action_results',
    () async {
      final engineConfig = await createCrawlConfigFromJson(
        json: r'{"browser":{"mode":"always"}}',
      );
      final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
      final url =
          "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/interact_invalid_selector";
      final result = await KreuzcrawlBridge.interact(engine, url);
      expect(result.actionResults[0].success, equals(false));
      expect(
        result.actionResults[0].actionType.toString().trim(),
        equals('click'.toString().trim()),
      );
      expect(result.actionResults[0].error, contains('not found'));
    },
  );

  test(
    'Submit 101 actions (exceeds MAX_ACTIONS=100) and verify validation error',
    () async {
      await expectLater(() async {
        final engineConfig = await createCrawlConfigFromJson(
          json: r'{"browser":{"mode":"always"}}',
        );
        final engine = await KreuzcrawlBridge.createEngine(
          config: engineConfig,
        );
        final url =
            "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/interact_max_actions_exceeded";
        return KreuzcrawlBridge.interact(engine, url);
      }(), throwsA(anything));
    },
  );

  test('Scroll down on the page and verify success', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json: r'{"browser":{"mode":"always"}}',
    );
    final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
    final url =
        "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/interact_scroll_down";
    final result = await KreuzcrawlBridge.interact(engine, url);
    expect(result.actionResults[0].success, equals(true));
    expect(
      result.actionResults[0].actionType.toString().trim(),
      equals('scroll'.toString().trim()),
    );
    expect(result.actionResults[0].actionIndex, equals(0));
  });

  test('Type text into an input field and verify success', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json: r'{"browser":{"mode":"always"}}',
    );
    final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
    final url =
        "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/interact_type_input";
    final result = await KreuzcrawlBridge.interact(engine, url);
    expect(result.actionResults[0].success, equals(true));
    expect(
      result.actionResults[0].actionType.toString().trim(),
      equals('type'.toString().trim()),
    );
    expect(result.actionResults[0].actionIndex, equals(0));
  });

  test('Wait for a CSS selector that exists on the page', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json: r'{"browser":{"mode":"always"}}',
    );
    final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
    final url =
        "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/interact_wait_selector";
    final result = await KreuzcrawlBridge.interact(engine, url);
    expect(result.actionResults[0].success, equals(true));
    expect(
      result.actionResults[0].actionType.toString().trim(),
      equals('wait'.toString().trim()),
    );
    expect(result.actionResults[0].actionIndex, equals(0));
  });
}
