#!/usr/bin/env bash
# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:64f3ed478eaa504db296e98f9b81ecff44f1094e71d4f14f22961810e08ce4e1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: cookies
set -euo pipefail

test_cookies_per_domain() {
    # Isolates cookies per domain during crawl
    kreuzcrawl scrape "${MOCK_SERVER_URL}/fixtures/cookies_per_domain" --format json --browser-mode never >/dev/null

    # skipped: field 'cookies.length' not available on result type
    # skipped: field 'cookies' not available on result type
}

test_cookies_persistence() {
    # Maintains cookies across multiple crawl requests
    kreuzcrawl scrape "${MOCK_SERVER_URL}/fixtures/cookies_persistence" --format json --browser-mode never >/dev/null

    # skipped: field 'cookies' not available on result type
}

test_cookies_set_cookie_response() {
    # Respects Set-Cookie header from server responses
    kreuzcrawl scrape "${MOCK_SERVER_URL}/fixtures/cookies_set_cookie_response" --format json --browser-mode never >/dev/null

    # skipped: field 'cookies' not available on result type
}

run_tests_cookies() {
    run_test test_cookies_per_domain
    run_test test_cookies_persistence
    run_test test_cookies_set_cookie_response
}
