// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2993fbc38a96c38ce794c49583670e23ac73a921000d5a5ded6511494275a798
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: proxy
package e2e_test

import (
	"encoding/json"
	"os"
	"testing"

	pkg "github.com/kreuzberg-dev/kreuzcrawl/packages/go"
)

func Test_ProxyAuthenticated(t *testing.T) {
	// Proxy with username and password credentials authenticates successfully
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"proxy":{"password":"proxypass","url":"http://127.0.0.1:8889","username":"proxyuser"},"respect_robots_txt":false}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		t.Fatalf("create handle failed: %v", createErr)
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/proxy_authenticated"
	result, err := pkg.Crawl(engine, url)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if len(result.Pages) != 0 {
		t.Errorf("equals mismatch: got %v", len(result.Pages))
	}
}

func Test_ProxyBasicSuccess(t *testing.T) {
	// Configure proxy URL and successfully crawl through it
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"proxy":{"url":"http://127.0.0.1:8888"},"respect_robots_txt":false}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		t.Fatalf("create handle failed: %v", createErr)
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/proxy_basic_success"
	result, err := pkg.Crawl(engine, url)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if len(result.Pages) != 0 {
		t.Errorf("equals mismatch: got %v", len(result.Pages))
	}
}
